### PR TITLE
Update ve.m3u

### PR DESCRIPTION
**Pull request by nickleby**
Fix/Add new channels

### CODE REVIEW

**Review by Carlinhos027 — COMMENTED** [review]
I think these should be added too: #10509 #10510  #10511   #10512  #10513  #10514 
And repair Venezolana de Television with this link: http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/embed/video/x828i6j?autoplay=1

**Comment by nickleby** [comment]
> I think these should be added too: #10509 #10510 #10511 #10512 #10513 #10514 And repair Venezolana de Television with this link: http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.dailymotion.com/embed/video/x828i6j?autoplay=1

ValeTV is already on the playlist. I don't think VTV needs repair, the actual link works (although the freefullspeedtv server is having issues right now). I don't know about the other channels, you can submit a pull request.

**Comment by LaneSh4d0w** [comment]
Channel VPI can be replaced with this : 

#EXTINF:-1 tvg-id="VPItv.ve" status="timeout",VPItv (1080p)
https://ott3.streann.com/loadbalancer/services/public/channels/5d23d5882cdce61dae029fd8/playlist.m3u8

**Comment by LaneSh4d0w** [comment]
CTN TV is looping on a constant "Ya regresamos" (translation : "we're coming back")

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
Avila TV is actually a governmental group of channels, and the Dailymotion link above is an official governmental account.

**Review by BellezaEmporium — APPROVED** [review]

**Review by UltraHDR — APPROVED** [review]

**Pull request merged**
