### PR TITLE
Update cn_streamlink.m3u

### LINKED ISSUE #15134: Broken: Every channels on cn_streamlink
### Broken Link

https://github.com/iptv-org/iptv/blob/master/streams/cn_streamlink.m3u

### What happened to the stream?

Other

### Notes (optional)

I went to the channels to watch ViuTV and Japan news and suddenly pops up with a generic 401 image and translated the image with Google app. It has something to do with the streams only worked in Hong Kong or something. It used to be working before and now it's unwatchable.
IMG_7787

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by freearhey**
Resolves https://github.com/iptv-org/iptv/issues/15134

### CODE REVIEW

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by Dum4G** [comment]
Isn't it worth to tag it as geo-blocked? Viewer claims it works in HK

**Comment by freearhey** [comment]
Updated.

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]
They've recently changed the tokens on the links, and while last time it didn't work, this time I can confirm (from an HK IP) that it does work. 401 on other countries.

**Comment by Jitterdoomer** [comment]
As for "stress-testing" the server, I wouldn't be surprised if that channel will shut down anytime soon.

**Pull request merged**
