### PR TITLE
CN: Remove broken links

### PR DESCRIPTION
**Pull request by freearhey**
Removed links with "error" status.

All links are checked from two different regions at different times of the day with the [playlist:cleaner](https://github.com/iptv-org/iptv/blob/master/scripts/commands/playlist/cleaner.js) script.

Links marked as `[Not 24/7]` or `[Geo-blocked]` were skipped.

### CODE REVIEW

**Comment by freearhey** [comment]
@LaneSh4d0w Here's the latest version.

**Review by its0x08 — DISMISSED** [review]

**Comment by freearhey** [comment]
@LaneSh4d0w Are you finished?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w Are you finished?

The PR i made was done prior the playlist changes, it's not easy to find everything I've done in terms of changes.

**Comment by freearhey** [comment]
Ah, okay, take your time!

**Comment by LaneSh4d0w** [comment]
I'll check the new links I had, you basically cleaned a lot of the mess it had. I think we can even take off the some "timing out" links, especially the ones that are linked to China Mobile's IP addresses, because I don't think they'll ever work again.

**Comment by freearhey** [comment]
Closed in favor #6921

**Pull request closed without merging**
