### PR TITLE
Update cl.m3u

### PR DESCRIPTION
**Pull request by sguinetti**
Rename id of Energeek2 (now Fanpop), see https://github.com/iptv-org/database/issues/765.

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]

**Comment by EnerGeekTeam** [comment]
Was about to create a PR because EnerGeek Fanpop appears on the website but no streams are attached to it.

**Comment by sguinetti** [comment]
Right. When an id is changed in the Database repo, it must also be changed immediately in the playlist. It is necessary for the streams to appear with the new id as possible. As you may understand, this PR requires an admin approval but it won't take long. We appreciate your patience and understanding. Additionally, the whole process is also explained in the FAQ page.

**Comment by sguinetti** [comment]
Feel free to update other channel details in the Database as needed. This will not affect the streams of the playlist generated on the web, except when the id is changed. As this is the first time an owner has done this process, we are happy to receive feedback.

**Review by Alstruit — APPROVED** [review]

**Comment by EnerGeekTeam** [comment]
Well i'm not the founder of the project itself but i am the one that works IT here.

**Pull request merged**
