### PR TITLE
Update clean action

### PR DESCRIPTION
**Pull request by freearhey**
This update:

- adds `channels/unsorted.m3u` to the weekly check list
- fixes the broken link counter
- also the script will remove all links from the playlists that respond with HTTP code 500 (Internal Server Error),  501 (Not Implemented) and 410 (Gone)

### CODE REVIEW

**Comment by Dum4G** [comment]
Errors like 502, 503 and 504 are usually temporal, at this state PR will cause more false-positives than it should. You can add support for a rare case of 410 gone tho

**Comment by freearhey** [comment]
@Dum4G Thank you for pointing that out, I've already updated the script.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
You could look after the link and see if the answering result is either a m3u8 (vnd.apple.mpegurl), either an octet-stream (video/mp2t or application/octet-stream) or ts. This might reduce the number of false positives (200 and there's an url page instead)

**Comment by Dum4G** [comment]
We also have some mpd streams and a few that won't return anything without a proper EXTVLC option. To reduce the number of false positives a script should repeat it's test against found links 8 hours after initial test and counter it's previous commit in the same pull request.

**Pull request merged**
