### PR TITLE
Template : Add additional disclaimer

### PR DESCRIPTION
**Pull request by BellezaEmporium**
It would be actually useful to know when we need to make additional workarounds to  have the playlist link + the website where it originates, so adding a disclaimer on the template directly.

### CODE REVIEW

**Comment by freearhey** [comment]
Could you give some examples of such requests?

**Comment by LaneSh4d0w** [comment]
#3471 as an example would need to get a fresh Anvato token everytime.

Count with this all "Referrer-blocked" links + "livestream.com" streams that we made working by actually grabbing a fresh link from the stream_info JSON.

**Comment by Dum4G** [comment]
Take it easier

**Comment by LaneSh4d0w** [comment]
I first thought about actually adding this, but I didn't know if it was useful, because we could actually put it onto Notes

**Comment by Dum4G** [comment]
I'm also proposing to note this info in tvg-url parameter, this way:

It would be easier to determine origin country and language in questionable situations
It may help to determine if the source has stopped broadcasting or requires a replacement link

**Comment by jkemp814** [comment]
I edited the request at #3471 should I swap the mediaManifest data with the data in External Link (optional):?

**Comment by LaneSh4d0w** [comment]
> 
> 
> I edited the ADD request at #3471 should I swap the mediaManifest data with the data in External Link (optional):?

Since this PR hasn't been approved yet, you're good to keep your issue as is.

Thanks by the way for completing it with more data. It'll give us a better look on this stream.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
