### PR TITLE
AR : Reinstate América TV

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Trying something.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
> I'm not sure if we can consider m3u-editor links as public, AFAIK that's a service that allows you to make your own playlist and then serve a particular channel with a particular link. Can easily redirect to an Xcode stream or smth. Tell me if I'm wrong

Yep, but I'm the one who created the link, I've actually took the links I had out of the iptv-all service.

**Review by Dum4G — DISMISSED** [review]

**Review by dct-infra — COMMENTED** [review]
link doesn't work for lme

**Comment by LaneSh4d0w** [comment]
> link doesn't work for lme

OK, i'll put them in GH.

**Comment by LaneSh4d0w** [comment]
@dct-infra Try now.

**Comment by dct-infra** [comment]
> @dct-infra Try now.

hls_america Failed reading https://prepublish.f.qaotic.net:443/a07/americahls-100056/segment_360p_116247.ts: HTTP/1.1 403 Access denied.

**Comment by LaneSh4d0w** [comment]
> > @dct-infra Try now.
> 
> hls_america Failed reading https://prepublish.f.qaotic.net:443/a07/americahls-100056/segment_360p_116247.ts: HTTP/1.1 403 Access denied.

If there's not the user-agent fix it won't work. Please take the modified playlist directly.

**Comment by LaneSh4d0w** [comment]
Referer not needed if user-agent iPhone is given in.

**Review by Dum4G — DISMISSED** [review]

**Review by sguinetti — DISMISSED** [review]

**Review by Dum4G — APPROVED** [review]

**Review by sguinetti — APPROVED** [review]

**Review by MapGuy11 — APPROVED** [review]

**Pull request merged**
