### PR TITLE
Update hu.m3u

### PR DESCRIPTION
**Pull request by kristoft13**
Added Duna World

### CODE REVIEW

**Review by BellezaEmporium — DISMISSED** [review]

**Review by Alstruit — CHANGES_REQUESTED** [review]
Tokenized. Probably needs a scraper.
Reference: https://github.com/iptv-org/iptv/issues/9421#issuecomment-1273235814

**Comment by LaneSh4d0w** [comment]
Welp lol... seems I have found the way to automate this one, but it's quite crazy.

**Comment by LaneSh4d0w** [comment]
free.fullspeed is struggling right now, will try later.

**Comment by Alstruit** [comment]
> Welp lol... seems I have found the way to automate this one, but it's quite crazy.

Sorry if it's bothersome, but I believe streamlink already implemented Duna World under ["Mediaklikk"](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/mediaklikk.py). 
I did not realize it until just now. I added the links via fullspeed.tv.
So far only M3 uses widevine DRM.

**Comment by LaneSh4d0w** [comment]
> > Welp lol... seems I have found the way to automate this one, but it's quite crazy.
> 
> Sorry if it's bothersome, but I believe streamlink already implemented Duna World under ["Mediaklikk"](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/mediaklikk.py). I did not realize it until just now. I added the links via fullspeed.tv. So far only M3 uses widevine DRM.

Better have official links instead of a provider anyway. For now I think dct is doing some maintenance over his servers as they don't answer for now.

**Review by Alstruit — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
I prefer deleting the mytvback links for now, as they all don't work now.

**Review by BellezaEmporium — APPROVED** [review]

**Review by Alstruit — APPROVED** [review]

**Pull request merged**
