### PR TITLE
Add The Country Network

### PR DESCRIPTION
**Pull request by UltraHDR**

### CODE REVIEW

**Review by BellezaEmporium — DISMISSED** [review]
Interestingly enough, it *only* streams in 4K. No adaptive playlists around ?

**Comment by UltraHDR** [comment]
> Interestingly enough, it _only_ streams in 4K. No adaptive playlists around ?

Added a 1080p stream

**Review by BellezaEmporium — APPROVED** [review]
Perfect. LGTM.

**Review by freearhey — APPROVED** [review]

**Comment by TKList** [comment]
Getting audio only.

**Pull request merged**
