### PR TITLE
IR : Add French version of Press TV / Fix old one

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Taking into consideration comment https://github.com/iptv-org/iptv/issues/3294#issuecomment-867905963 and https://github.com/iptv-org/iptv/issues/3294#issuecomment-867907373

Both links work for me.

### CODE REVIEW

**Review by Sphinxroot — APPROVED** [review]

**Comment by jkemp814** [comment]
For the French version of PressTV should the language be French? 

```
#EXTINF:-1 tvg-id="PressTV.ir" tvg-name="Press TV" tvg-country="IR" tvg-language="English" tvg-logo="https://i.imgur.com/TNQKahI.png" group-title="News",Press TV French (720p)
https://live1.presstv.ir/live/presstvfr/index.m3u8
```

I'm still learning how these edit work so I can help out building pull requests, instead of asking others to fix things.

**Comment by LaneSh4d0w** [comment]
Indeed it should. I've catched it out at the last moment lol. I'll fix it when I can.

**Comment by jkemp814** [comment]
The link [https @ 0x7f1bac001780] HTTP error 404 Not Found sq=    0B f=0/0   
https://live1.presstv.ir/live/presstvfr/index.m3u8: Server returned 404 Not Found

**Comment by jkemp814** [comment]
Started working again.

**Pull request merged**
