### PR TITLE
Add Another Weather Channel feed

### PR DESCRIPTION
**Pull request by MapGuy11**

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
i must say the IP behind it hasn't hidden his proxy, there's 3 programs behind it if you want !

http://168.138.70.50:5080/channel/n104f84b1/index.m3u8 TWC English
http://168.138.70.50:5080/channel/n70486ae7/index.m3u8 TWC en Espanol
http://168.138.70.50:5080/channel/6f5ab1d7/index.m3u8 TWC Special

**Comment by MapGuy11** [comment]
I mean the bottom 2 we already have so...

**Comment by LaneSh4d0w** [comment]
Ah good for us then. Was only pointing those out.

**Comment by MapGuy11** [comment]
> Ah good for us then. Was only pointing those out.
> 
> is it yours @MapGuy11 ? I see some other things being added in...

No, I just found it.

**Comment by LaneSh4d0w** [comment]
> > Ah good for us then. Was only pointing those out.
> > is it yours @MapGuy11 ? I see some other things being added in...
> 
> No, I just found it.

Okay, it's because it's adding some WCTV links right now, the old ones we had.

**Comment by LaneSh4d0w** [comment]
Okay, you won't believe me... the IP you've found, if you use port 80, it says "https://www.localbtv.com"

I believe you've found something that belongs to MyBTV.

**Comment by MapGuy11** [comment]
> Okay, you won't believe me... the IP you've found, if you use port 80, it says "https://www.localbtv.com"
> 
> I believe you've found something that belongs to MyBTV.

oh really anything else you see on there?

**Comment by LaneSh4d0w** [comment]
Location says Quebec, Canada but is registered to the US.

They seem to change channels a lot, just go to the root of the link and you have their unprotected HLS-Proxy.

(for similar links, you can use censys and look after links that have "#EXTM3U " as an response body)

Port 8080 also seem to have something, but only show "Unsupported Media Type)

**Comment by MapGuy11** [comment]
> Location says Quebec, Canada but is registered to the US.
> 
> They seem to change channels a lot, just go to the root of the link and you have their unprotected HLS-Proxy.
> 
> (for similar links, you can use censys and look after links that have "#EXTM3U " as an response body)
> 
> Port 8080 also seem to have something, but only shows "Unsupported Media Type"
> 
> EDIT : Seems they've found out, it's now locked with a login.

Not for me

**Comment by LaneSh4d0w** [comment]
> > Location says Quebec, Canada but is registered to the US.
> > They seem to change channels a lot, just go to the root of the link and you have their unprotected HLS-Proxy.
> > (for similar links, you can use censys and look after links that have "#EXTM3U " as an response body)
> > Port 8080 also seem to have something, but only shows "Unsupported Media Type"
> > EDIT : Seems they've found out, it's now locked with a login.
> 
> Not for me

Yeah it's weird as hell, it locked and now i got it. Now I see way more channels.

**Comment by MapGuy11** [comment]
> > > Location says Quebec, Canada but is registered to the US.
> > > They seem to change channels a lot, just go to the root of the link and you have their unprotected HLS-Proxy.
> > > (for similar links, you can use censys and look after links that have "#EXTM3U " as an response body)
> > > Port 8080 also seem to have something, but only shows "Unsupported Media Type"
> > > EDIT : Seems they've found out, it's now locked with a login.
> > 
> > 
> > Not for me
> 
> Yeah it's weird as hell, it locked and now i got it. Now I see way more channels. There's some channels that we don't see in myBTV that are in there. Interesting. (there's like 10+ channels now)
> 
> There's a new market in town also it seems... Columbus. They've made the space for a last one...
> 
> EDIT : Okay now I see 5 pages of channels, all categorized... Aaaaaand... they've locked it again, to put it back again. Let me take all those out before it locks out for good.

I think you can right-click and just copy the link. But obv removing the token crap as it does nothing.

**Comment by LaneSh4d0w** [comment]
PCN HD http://168.138.70.50:5080/channel/4367b311/index.m3u8
REELZ HD http://168.138.70.50:5080/channel/n4d667d90/index.m3u8
Movies! SD http://168.138.70.50:5080/channel/n76f63fc1/index.m3u8
Bounce SD http://168.138.70.50:5080/channel/d9f859d/index.m3u8
getTV SD http://168.138.70.50:5080/channel/n5a7f0a3b/index.m3u8
WTOG HD http://168.138.70.50:5080/channel/2443ab5b/index.m3u8
WVEA HD http://168.138.70.50:5080/channel/271db755/index.m3u8
WTVT HD http://168.138.70.50:5080/channel/24ac38b5/index.m3u8
WXPX HD http://168.138.70.50:5080/channel/2b2cdfa7/index.m3u8
LATV SD http://168.138.70.50:5080/channel/n41bfabd2/index.m3u8
Ovation HD http://168.138.70.50:5080/channel/n3bd3d0db/index.m3u8
A&E http://168.138.70.50:5080/channel/n10ad5cd4/index.m3u8
MeTV http://168.138.70.50:5080/channel/n4f7da92/index.m3u8
History Channel http://168.138.70.50:5080/channel/21100583/index.m3u8
Hallmark Channel http://168.138.70.50:5080/channel/n9f07d63/index.m3u8
Hallmark Movies & Mysteries http://168.138.70.50:5080/channel/406c974c/index.m3u8
UPtv http://168.138.70.50:5080/channel/n4f4826f/index.m3u8

**Comment by MapGuy11** [comment]
> PCN HD http://168.138.70.50:5080/channel/4367b311/index.m3u8 REELZ HD http://168.138.70.50:5080/channel/n4d667d90/index.m3u8 Movies! SD http://168.138.70.50:5080/channel/n76f63fc1/index.m3u8 Bounce SD http://168.138.70.50:5080/channel/d9f859d/index.m3u8 getTV SD http://168.138.70.50:5080/channel/n5a7f0a3b/index.m3u8 WTOG HD http://168.138.70.50:5080/channel/2443ab5b/index.m3u8 WVEA HD http://168.138.70.50:5080/channel/271db755/index.m3u8 WTVT HD http://168.138.70.50:5080/channel/24ac38b5/index.m3u8 WXPX HD http://168.138.70.50:5080/channel/2b2cdfa7/index.m3u8 LATV SD http://168.138.70.50:5080/channel/n41bfabd2/index.m3u8 Ovation HD http://168.138.70.50:5080/channel/n3bd3d0db/index.m3u8 A&E http://168.138.70.50:5080/channel/n10ad5cd4/index.m3u8 MeTV http://168.138.70.50:5080/channel/n4f7da92/index.m3u8 History Channel http://168.138.70.50:5080/channel/21100583/index.m3u8 Hallmark Channel http://168.138.70.50:5080/channel/n9f07d63/index.m3u8 Hallmark Movies & Mysteries http://168.138.70.50:5080/channel/406c974c/index.m3u8 UPtv http://168.138.70.50:5080/channel/n4f4826f/index.m3u8

Any more?

**Comment by LaneSh4d0w** [comment]
> > PCN HD http://168.138.70.50:5080/channel/4367b311/index.m3u8 REELZ HD http://168.138.70.50:5080/channel/n4d667d90/index.m3u8 Movies! SD http://168.138.70.50:5080/channel/n76f63fc1/index.m3u8 Bounce SD http://168.138.70.50:5080/channel/d9f859d/index.m3u8 getTV SD http://168.138.70.50:5080/channel/n5a7f0a3b/index.m3u8 WTOG HD http://168.138.70.50:5080/channel/2443ab5b/index.m3u8 WVEA HD http://168.138.70.50:5080/channel/271db755/index.m3u8 WTVT HD http://168.138.70.50:5080/channel/24ac38b5/index.m3u8 WXPX HD http://168.138.70.50:5080/channel/2b2cdfa7/index.m3u8 LATV SD http://168.138.70.50:5080/channel/n41bfabd2/index.m3u8 Ovation HD http://168.138.70.50:5080/channel/n3bd3d0db/index.m3u8 A&E http://168.138.70.50:5080/channel/n10ad5cd4/index.m3u8 MeTV http://168.138.70.50:5080/channel/n4f7da92/index.m3u8 History Channel http://168.138.70.50:5080/channel/21100583/index.m3u8 Hallmark Channel http://168.138.70.50:5080/channel/n9f07d63/index.m3u8 Hallmark Movies & Mysteries http://168.138.70.50:5080/channel/406c974c/index.m3u8 UPtv http://168.138.70.50:5080/channel/n4f4826f/index.m3u8
> 
> Any more? The streams seem to buffer really well.

Going batch by batch, 4 more to go.

**Comment by LaneSh4d0w** [comment]
We're good to go.

**Comment by MapGuy11** [comment]
> We're good to go.
> 
> EDIT : Lucky me it seems... they've locked it.

Probably all done.

**Comment by LaneSh4d0w** [comment]
> > We're good to go.
> > EDIT : Lucky me it seems... they've locked it.
> 
> Probably all done.

Yup, hopefully they didn't add anything between the time I've scraped and the time they've locked.

**Comment by MapGuy11** [comment]
> > > We're good to go.
> > > EDIT : Lucky me it seems... they've locked it.
> > 
> > 
> > Probably all done.
> 
> Yup, hopefully they didn't add anything between the time I've scraped and the time they've locked.

I think it's unlocked again.

**Comment by LaneSh4d0w** [comment]
> > > > We're good to go.
> > > > EDIT : Lucky me it seems... they've locked it.
> > > 
> > > 
> > > Probably all done.
> > 
> > 
> > Yup, hopefully they didn't add anything between the time I've scraped and the time they've locked.
> 
> I think it's unlocked again. @LaneSh4d0w. Do you see anything new? EDIT: it's locked again I wonder if I can guess the password.

On last check nothing new apart of the 2 channels mentioned above.

**Comment by MapGuy11** [comment]
> ?q=1664646028362

I found this will it help? 
http://168.138.70.50:5080/playlist.m3u8?q=eyJ1c2VySWQiOiJtYXhfbG9jYWxidHYifQ.17JmnZ9lL3DQ2pnsBUZVtIyoMD3r6fR-7dkRA3Bhbyk22IrbC_s7BXEXCwBm0_S3hlMoi41UiZcvxEszd5Lp5g

**Comment by MapGuy11** [comment]
@LaneSh4d0w the streams work for me. Also it seems that you can get to them without a password. 

I found these:
image
image

Very cryptic names

**Review by Central302 — APPROVED** [review]
Playable in Safari on iOS, Thanks!
8493E907-9817-45D1-BAB0-52BB6170B652

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w the streams work for me. Also it seems that you can get to them without a password.
> 
> I found these: image image
> 
> Very cryptic names

Yup I've seen that.

It seems they've dumped some streams from the Frontier ISP/streaming service.
Sort of "NAME_SERVICE_STATE"
FL being Florida... sounds like there's something being prepared along those lines.

**Pull request merged**
