### PR TITLE
TL: creation & add RTTL East Timor

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Not 24/7, seems to stream every hour.

Has Tetum, Portuguese and Indonesian news panels.

### CODE REVIEW

**Comment by UltraHDR** [comment]
Hasn't streamed in 8 hours but I'll approve anyway

**Review by UltraHDR — APPROVED** [review]

**Review by freearhey — COMMENTED** [review]
The original link works:
https://www.youtube.com/channel/UCtwMP_IzEm3r9PDuaYRUKLA/live
image

Streamlink does not.

**Comment by LaneSh4d0w** [comment]
> The original link works: https://www.youtube.com/channel/UCtwMP_IzEm3r9PDuaYRUKLA/live image
> 
> Streamlink does not

The channel doesn't stream all the time, it seems they do get online once it's news or anything related to it.

**Comment by freearhey** [comment]
The problem is that the link does not work even when the source is online.

**Comment by LaneSh4d0w** [comment]
> The problem is that the link does not work even when the source is online.

That's odd, I'll try when it comes back online.

**Comment by UltraHDR** [comment]
> The problem is that the link does not work even when the source is online.

It worked for me in VLC

**Review by UltraHDR — APPROVED** [review]

**Review by freearhey — APPROVED** [review]
I just checked again:

- without VPN via VLC, it worked for me too
- with US VPN still gives me an error

But maybe it's just a problem on my end.

**Pull request merged**
