### PR TITLE
Update in.m3u

### PR DESCRIPTION
**Pull request by hoooooman**

### CODE REVIEW

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Disney Channel is an American channel, it must be in the US playlist.

**Comment by hoooooman** [comment]
> Disney Channel is an American channel, it must be in the US playlist.

But this is an indian channel.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Disney Channel is an American channel, it must be in the US playlist.
> 
> But this is an indian channel.

It's for Indian people, but Disney is an American company. We classify them by their origin.

**Comment by Sphinxroot** [comment]
and it a xtreme code from a paid or tryout  its not free to view channel

**Pull request closed without merging**
