### PR TITLE
CH : Update "Rouge TV"

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Precising that this channel also streams adult content around 12 AM / 1 AM (UTC+2)

image

### CODE REVIEW

**Comment by freearhey** [comment]
Multiple values in the group-title attribute are currently not supported.

**Comment by LaneSh4d0w** [comment]
Well then I guess we'll classify it at XXX for safety purposes.

**Comment by Dum4G** [comment]
> Well then I guess we'll classify it at XXX for safety purposes.

That's too much for safety purposes

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Well then I guess we'll classify it at XXX for safety purposes.
> 
> That's too much for safety purposes

Quite right, i'll classify it as XXX.

**Pull request closed without merging**
