### PR TITLE
Add http://www.channelbox.tv

### PR DESCRIPTION
**Pull request by UltraHDR**

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]
Rather interesting find. Will try to see from their "channel list" if I can deduct up more.

**Comment by UltraHDR** [comment]
@LaneSh4d0w you can do a mitm on https://apkcombo.com/channelbox/com.synapsetv.channelbox/ . There are more channels but I'm lazy.

**Comment by LaneSh4d0w** [comment]
http://78.129.193.17/tsstreamer/TwistedMirrorLDAI_SD.ts
http://188.227.164.31/tsstreamer/VoxAfrica_SD.ts

**Comment by UltraHDR** [comment]
@LaneSh4d0w Added in https://github.com/iptv-org/iptv/pull/8143

**Pull request merged**
