### PR TITLE
Boing channels

### LINKED ISSUE #4188: Boing France
**Channel Name:** Boing France
**Country:** France
**Language:** France
**Website:** boing.fr
**Stream URL (optional):** none
**Notes (optional):** none

### PR DESCRIPTION
**Pull request by Dum4G**
Closes https://github.com/iptv-org/iptv/issues/4188
https://en.wikipedia.org/wiki/Boing_(TV_channel)

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
While Boing France is in the correct place, Boing Spain's operated by Mediaset, so it should be placed into the Italian playlist.

**Comment by Dum4G** [comment]
We don't care about co-owners AFAIK

**Comment by LaneSh4d0w** [comment]
image
Even if it's said ?

**Comment by Dum4G** [comment]
image

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
