### PR TITLE
JP : Move server

### LINKED ISSUE #5848: Add: Cartoon Network Japan
### Channel Name

Cartoon Network Japan (カートゥーン ネットワーク)

### Country

Japan

### Language

Japanese

### Website

https://www.cartoonnetwork.jp/

### Stream URL

http://50.7.74.29:8080/hlsok/j00024/index.m3u8

### Notes

_No response_

### PR DESCRIPTION
**Pull request by BellezaEmporium**
A Japanese user wrote to me by email telling me that the channels from the other host weren't working.

- Moving channels to another host (coordinated efforts by @LaneSh4d0w, @Central302 for channel names additions / Verifications, @GiovanniSebastian for link findings, @what-a for channel verification in US)
- Added TV Osaka & Kansai TV
- Need verification for NHK E & G channels (to know if it's Osaka or Tokyo)

Resolves #5848

### CODE REVIEW

**Review by Dum4G — DISMISSED** [review]

**Review by dct-infra — DISMISSED** [review]

**Comment by Central302** [comment]
ID "32" NHK-G Osaka (Confirmed)
    "33" NHK-G Tokyo (Confirmed)

**Review by freearhey — DISMISSED** [review]

**Review by Dum4G — APPROVED** [review]

**Comment by Central302** [comment]
34 = NHK-E Osaka (Confirmed)
35 = NHK-E Tokyo (Confirmed)
BE2A1857-FA2E-44AD-96DC-0F20D684D09F

**Review by freearhey — APPROVED** [review]

**Comment by luongz** [comment]
The channel are looping at the same position

**Comment by nyanzilla** [comment]
1 - 衛星劇場 (Eisei Gekijou)
2 - 時代劇専門チャンネル (Jidaigeki Senmon Channel)
3 - 日本映画専門チャンネル (Nihon Eiga)
5 - 日テレジータス (Hontere Gtasu)
7 - ytv (yomiuri tv)
8 - Toei Channel
9 - ホームドラマチャンネル (Home Drama Channel)
15 - Disney Channel
16 - Disney Junior
20 - スカイA (Sky-A)
21 - SUN
22 - GOLF Network
23 - KIDS Station
24 - Cartoon Network
25 - animal planet
27 - Wowow Live
28 - Wowow Cinema
29 - Wowow Prime
43 - Wowow Plus
44 - GREEN Channel
46 - 釣りビジョン (Fishing Vision)
53 - ABC (Asahi Broadcasting Corporation)

Network logos verified at: https://www.eiseihoso.org/guide/ch_lineup.html
Service similar to Muji TV ( https://streamingtvasia.com/live-streaming-japanese-tv/#mujitv )

**Review by MapGuy11 — APPROVED** [review]

**Pull request merged**
