### PR TITLE
Update jp.m3u

### LINKED ISSUE #7648: Add:  TV TOKYO
### Channel Name

tv tokyo

### Channel ID

JOTXDTV.jp

### Website

_No response_

### Stream URL

_No response_

### Notes

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #8358: Add: Disney Channel Japan
### Channel ID

DisneyChannelJapan.jp

### Notes

Channel Name: Disney Channel Japan
Country: Japan
Language: Japanese/English
Website: https://www.disney.co.jp
Stream URL (optional): -
Notes (optional): Thank You!

### Please confirm the following

- [x] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### PR DESCRIPTION
**Pull request by Alstruit**
Reference: #9013
Closes #7648, closes #8358

### CODE REVIEW

**Review by BellezaEmporium — DISMISSED** [review]
LGTM

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
@Alstruit 

Kanto Nippon TV : https://cdn.us195.jpnettv.live/jptv/kanto_nippon_540/playlist.m3u8
Kanto NHK G : https://cdn.us195.jpnettv.live/jptv/kanto_nhk_g_540/playlist.m3u8
Kanto NHK E : https://cdn.us195.jpnettv.live/jptv/kanto_nhk_e_540/playlist.m3u8

**Comment by Alstruit** [comment]
Some of the channels which I checked already are 404. I'm not sure if they're 404 temporary or permanently.

**Comment by LaneSh4d0w** [comment]
> 

Interesting, works for me. Though their KR branch is still locked out. good for them.

**Comment by Alstruit** [comment]
Let me know once you're done adding so I can add them all at once.

**Review by UltraHDR — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
> Let me know once you're done adding so I can add them all at once.

Sure thing.

**Comment by LaneSh4d0w** [comment]
@Alstruit Good to add.

**Comment by Alstruit** [comment]
https://cdn.us195.jpnettv.live/jptv/japan_tv_G_540/playlist.m3u8 -> 日テレジータス. (I don't know english equivalent). Let me check if any ID exists if not I'll create and mention in a seperate PR.

**Comment by LaneSh4d0w** [comment]
G+ Sports & News according to the Japanese Wikipedia.

**Comment by Alstruit** [comment]
> G+ Sports & News

NitteleGPlus.jp Nittele G+. Got it

**Comment by LaneSh4d0w** [comment]
> > G+ Sports & News
> 
> NitteleGPlus.jp Nittele G+. Got it

Yep. Linked to Nippon TV as they provide this channel.

**Review by BellezaEmporium — APPROVED** [review]

**Review by freearhey — APPROVED** [review]

**Pull request merged**
