### PR TITLE
CN : Cleaning and investigating foreign streams

### LINKED ISSUE #5869: Replace: FeiCuiTai81.hk
### I have verified that

- [X] I use the GitHub playlist link and not a downloaded/cached version of the file
- [X] My TV player has updated this playlist after 0:00 GMT and is set to update it daily
- [X] I am aware that the channel source may have temporal outages. It is broken/absent from the playlist for couple of hours or days

### Channel Name

翡翠台（81） (1080p)

### What happened to the stream?

It is now offline (disappeared from the playlist)

### Playlist

https://github.com/iptv-org/iptv/blob/master/channels/hk.m3u

### Broken Link

http://61.238.6.49:8000/bysid/1

### Possible Replacement

_No response_

### Notes

Please update if have replacement, thanks.

### LINKED ISSUE #5876: HK channels in Chinese playlist - Misleading placement
### Describe your issue

Some Hong Kong programs were incorrectly added to mainland China.
Such as 翡翠台.
(Taiwan Province, Macau also has the same problem)

### PR DESCRIPTION
**Pull request by BellezaEmporium**
13 CCTV 1 streams, that's nice eh ?

- Take off redirecting links to streams, since it's not useful.
- Adaptive links for all CGTN channels.
- Delete offline streams, as we got tons of alternatives
- Fix CHC stream + add 2 alternative ones
- Add official links for CETV 1, 2, 3 and 4 (referer needed to get them working)
- Moved HK channels to their playlist, per remark from @Lemonawa (Resolves #5876 + Resolves #5869)
- Adds a set of Yunnan channels (YNTV) including one from pull #6254 (courtesy of @shensven)

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
https://cctvtxyhwh5c.liveplay.myqcloud.com/live/cdrmcctv1_1/index.m3u8 is the official CCTV 1 stream (Widevine protected, given as a .gif file ?)
https://cctvtxyhwh5c.liveplay.myqcloud.com/live/cdrmcctv2_1/index.m3u8 is the official CCTV 2 stream (same as the one above)
https://cctvtxyhwh5c.liveplay.myqcloud.com/live/cdrmcctv3_1/index.m3u8 is CCTV 3 etc etc...

**Comment by LaneSh4d0w** [comment]
Blue channel doesn't seem to correspond to the program.
```
#EXTINF:-1 tvg-id="BlueMeiJu.cn" tvg-country="CN" tvg-language="Chinese" tvg-logo="https://parco-zh.github.io/demo/BLUE.png" group-title="",Blue 美剧 (360p) [Not 24/7]
http://210.210.155.35/dr9445/h/h16/02.m3u8
```
streams another channel : 
rk

**Comment by fotvnetwork** [comment]
> Blue channel doesn't seem to correspond to the program.
> 
> ```
> #EXTINF:-1 tvg-id="BlueMeiJu.cn" tvg-country="CN" tvg-language="Chinese" tvg-logo="https://parco-zh.github.io/demo/BLUE.png" group-title="",Blue 美剧 (360p) [Not 24/7]
> http://210.210.155.35/dr9445/h/h16/02.m3u8
> ```
> 
> streams another channel : rk

Maybe it was Blue Ant Entertainment

**Comment by LaneSh4d0w** [comment]
> > Blue channel doesn't seem to correspond to the program.
> > 
> > ```
> > #EXTINF:-1 tvg-id="BlueMeiJu.cn" tvg-country="CN" tvg-language="Chinese" tvg-logo="https://parco-zh.github.io/demo/BLUE.png" group-title="",Blue 美剧 (360p) [Not 24/7]
> > http://210.210.155.35/dr9445/h/h16/02.m3u8
> > ```
> > 
> > streams another channel : rk
> 
> Maybe it was Blue Ant Entertainment

Can't really tell, I don't reckon any Chinese Channel apart from CCTV (as CGTN + CCTV America) having full-English transmission.

**Comment by LaneSh4d0w** [comment]
> > Blue channel doesn't seem to correspond to the program.
> > ```
> > #EXTINF:-1 tvg-id="BlueMeiJu.cn" tvg-country="CN" tvg-language="Chinese" tvg-logo="https://parco-zh.github.io/demo/BLUE.png" group-title="",Blue 美剧 (360p) [Not 24/7]
> > http://210.210.155.35/dr9445/h/h16/02.m3u8
> > ```
> 
> Maybe it was Blue Ant Entertainment

Found it was Rock Entertainment Indonesia.

**Comment by LaneSh4d0w** [comment]
Reinstated some channels as "Not 24/7"

As a proof, an interesting colorbar stream of a SiTV channel

nt1

**Comment by LaneSh4d0w** [comment]
to analyse 

http://m3u8.channellive.dzxw.net/cms/videos/nmip-media/channellive/channel37/playlist.m3u8 idk what's this one.

**Comment by Dum4G** [comment]
> to analyse
> 
> http://m3u8.channellive.dzxw.net/cms/videos/nmip-media/channellive/channel37/playlist.m3u8 idk what's this one.

And the correct answer is 通川
image

**Comment by Dum4G** [comment]
Upd: 
Screenshot_20220105-145045

And that is: 达州 广播 电视台 通 川 频道
Dazhou Radio and Television Station Tongchuan Channel

**Comment by LaneSh4d0w** [comment]
Thank you, added.

**Comment by Dum4G** [comment]
@LaneSh4d0w are you still able to resolve this?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w are you still able to resolve this?

Was pretty busy recently, going to look at it again.

**Comment by LaneSh4d0w** [comment]
Opening it, making next batch of changes when i'll be able to.

**Pull request closed without merging**
