### PR TITLE
Add Al Yaum

### PR DESCRIPTION
**Pull request by link8k**
Doesn't work with streamtest.in but works in VLC

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Worked for me : https://streamtest.in/logs/http-besttv650-myflix-alyaum-aoslive-it-best-tv-com-egress-bhandler-ikomg-alyaum_tv-manifest-m3u8

**Comment by freearhey** [comment]
@link8k According to [lyngsat](https://www.lyngsat.com/tvchannels/ae/Al-Yawm.html) this channel is from the United Arab Emirates.

**Comment by LaneSh4d0w** [comment]
> @link8k According to [lyngsat](https://www.lyngsat.com/tvchannels/ae/Al-Yawm.html) this channel is from the United Arab Emirates.

Not according to OSN, which possesses rights for Al-Yawn : https://www.osn.com/en-lb/explore/channels/yaw/al-yawm

**Comment by link8k** [comment]
@freearhey It's a channel that focuses on Syrian news but might be broadcasting elsewhere due to the political climate. The YouTube channel says Syria https://www.youtube.com/c/alyaumch/about

@LaneSh4d0w That's a different channel with the same name

**Comment by LaneSh4d0w** [comment]
@link8k Got you. Then, @freearhey might be right.

**Comment by link8k** [comment]
Move to ae.m3u

**Review by freearhey — APPROVED** [review]

**Pull request merged**
