### PR TITLE
Clean up US List

### PR DESCRIPTION
**Pull request by MapGuy11**
1. Remove NOT 24/7 tag - All of my channels are straight from OTA so they are 24/7
2. Change the WWSB link as it is just 54second file (The company listed on the file too doesn't own WWSB anymore)
3. Changed KOTR-LD1 Link
4. Changed KCWX's Link so you can get 720p
5. Removed links from app.mybtv.com that didn't work
6. Changed WPXI link so now it works again
7. Edit KPBS-DT1 so it now works

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Do you block VPNs from accessing your host ? Can't seem to access cdn88.theus6tv.tk. Could you give the IP of this server ?

**Comment by MapGuy11** [comment]
> Do you block VPNs from accessing your host ? Can't seem to access cdn88.theus6tv.tk. Could you give the IP of this server ?

I don't. Granted it is through Cloudflare so that may be it. Try it now.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Do you block VPNs from accessing your host ? Can't seem to access cdn88.theus6tv.tk. Could you give the IP of this server ?
> 
> I don't. Granted it is through Cloudflare so that may be it. Try it now. I can't give you an IP though. I had to self-host it with Argo Tunnels due to everyone DMCA'ing me because they don't like how I have access to all these channels but don't do anything about it.

getaddrinfo failed for cdn88.theus6tv.tk

**Comment by MapGuy11** [comment]
https://www.whatsmydns.net/#A/cdn88.theus6tv.tk
https://www.whatsmydns.net/#A/cdn87.theus6tv.tk
https://www.whatsmydns.net/#A/pa511.theus6tv.tk

**Comment by MapGuy11** [comment]
> https://www.whatsmydns.net/#A/cdn88.theus6tv.tk https://www.whatsmydns.net/#A/cdn87.theus6tv.tk https://www.whatsmydns.net/#A/pa511.theus6tv.tk

Maybe you can put those IP's into your A record and it may work

**Comment by MapGuy11** [comment]
It is working as expected
image

**Comment by MapGuy11** [comment]
> > > Do you block VPNs from accessing your host ? Can't seem to access cdn88.theus6tv.tk. Could you give the IP of this server ?
> > 
> > 
> > I don't. Granted it is through Cloudflare so that may be it. Try it now. I can't give you an IP though. I had to self-host it with Argo Tunnels due to everyone DMCA'ing me because they don't like how I have access to all these channels but don't do anything about it.
> 
> getaddrinfo failed for cdn88.theus6tv.tk

do you have an issue with cdn87?

**Comment by LaneSh4d0w** [comment]
Changed VPN IP, works.

**Comment by MapGuy11** [comment]
> Changed VPN IP, works.

Cool I wish I could give the links though with redirects and some having specific keys on them it's easier if I keep it under this host

**Review by BellezaEmporium — APPROVED** [review]

**Comment by MapGuy11** [comment]
@LaneSh4d0w Make sure you checkout #5244 5244 so you are in the loop.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w Make sure you checkout #5244 so you are in the loop.

Seen.

**Review by Dum4G — APPROVED** [review]

**Comment by DavidBerdik** [comment]
Has the WPXI link been removed? I don't see it in the list now.

**Pull request merged**
