### PR TITLE
Add BBC Red Button links

### PR DESCRIPTION
**Pull request by UltraHDR**

### CODE REVIEW

**Review by its0x08 — APPROVED** [review]

**Review by its0x08 — APPROVED** [review]

**Comment by leapofazzam123** [comment]
Probably kinda useless since it's an interactive service and it's impossible to interact with it without a special program.

**Comment by TKList** [comment]
I get 403. Maybe someone can get them to work:
https://gist.github.com/jhelgert/7594e245e09ec461e4c57cd9a2264fb5

**Comment by UltraHDR** [comment]
> Probably kinda useless since it's an interactive service and it's impossible to interact with it without a special program.

It typically shows other events when they have ran out of channels

**Comment by UltraHDR** [comment]
> I get 403. Maybe someone can get them to work: https://gist.github.com/jhelgert/7594e245e09ec461e4c57cd9a2264fb5

Geo-blocked. Most VPN are blocked

**Review by BellezaEmporium — COMMENTED** [review]
Weren't them deleted months earlier because they didn't show anything ?

**Comment by UltraHDR** [comment]
> Weren't them deleted months earlier because they didn't show anything ?

Not sure but they're working. They only broadcast when there's events.

**Review by BellezaEmporium — APPROVED** [review]

**Review by what-a — APPROVED** [review]

**Pull request merged**
