### PR TITLE
US: Add 3 new channels from Pluto TV.

### PR DESCRIPTION
**Pull request by heroku-miraheze**

### CODE REVIEW

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Adding UK-originated TV shows (24/7 streams) in the US playlist.

**Comment by heroku-miraheze** [comment]
The BBC channels is from UK.

**Comment by heroku-miraheze** [comment]
Fixed.

**Comment by heroku-miraheze** [comment]
@LaneSh4d0w Merge it now.

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
