### PR TITLE
Add new 2 channels in Pluto.TV.

### PR DESCRIPTION
**Pull request by heroku-miraheze**

### CODE REVIEW

**Review by Dum4G — CHANGES_REQUESTED** [review]
New Pluto TV Anime channel is actually different and called Pluto TV Anime Clásico. Consider changing it's name and tvg-id accordingly

**Review by heroku-miraheze — COMMENTED** [review]
Done.

**Comment by heroku-miraheze** [comment]
Changed the name.

**Review by Dum4G — CHANGES_REQUESTED** [review]
Letters like á shouldn't be used in tvg-id

**Review by heroku-miraheze — COMMENTED** [review]
Fixed.

**Comment by heroku-miraheze** [comment]
Fixed.

**Comment by heroku-miraheze** [comment]
GitHub Actions has encountered an internal error when running your job.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
