### PR TITLE
Added more channels and EPG information

### PR DESCRIPTION
**Pull request by MsVibe**

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
All DR channels do not work

**Comment by MsVibe** [comment]
DR channels work well here - maybe they are only available to people with a Danish IP

**Comment by MsVibe** [comment]
By the way here is one more channel:

#EXTINF:-1 tvg-id="TV 2 Lorry DK" tvg-name="TV 2 Lorry DK" group-title="Denmark",TV 2 Lorry DK
https://cdnapisec.kaltura.com/p/2045321/sp/204532100/playManifest/entryId/1_2kojfk4m/format/applehttp/protocol/https/uiConfId/32599481/a.m3u8

**Comment by freearhey** [comment]
The fact is, we are not adding geo-blocked broadcasts to the playlist, since they are too difficult to maintain.

Otherwise, everything seems fine to me, so I will publish all your changes as soon as you remove DR channels from PR.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
