### PR TITLE
Update ir.m3u

### PR DESCRIPTION
**Pull request by data14a**

### CODE REVIEW

**Comment by freearhey** [comment]
Please resolve conflict so we can approve this pull request.

**Comment by data14a** [comment]
Please bear with me as I am pretty new at this. Looking at the conflicts, I am really not sure what the problem is or what I need to do to fix them.

**Comment by freearhey** [comment]
The conflict most likely occurred because the original file was modified before you sent your corrections. To resolve a conflict, you need to choose which changes should remain and which are no longer relevant.

You can read more about the process here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by data14a** [comment]
I have two commits and I only want the latest to be submitted. Is is possible to delete or cancel the older one or delete both of them and start over.

**Comment by freearhey** [comment]
Yeah, it might be easier for you to create a new pull request.

**Pull request closed without merging**
