### PR TITLE
Update ve.m3u

### PR DESCRIPTION
**Pull request by Carlinhos027**
Add few channels and correct link.

### CODE REVIEW

**Comment by nickleby** [comment]
AvilaTV needs referrer to work. Also, the previous link of TV Familia is still working, the new one you're adding it's not TV Familia.

**Comment by Carlinhos027** [comment]
> The previous link of TV Familia is still working, the new one you're adding it's not TV Familia.

Done

**Review by BellezaEmporium — DISMISSED** [review]
I do not know if the Odysee CDN links are made to change over time. Maybe i'll write a plugin for it when I have time.

- free.fullspeed.tv is down since a few months now.

**Comment by Carlinhos027** [comment]
> I do not know if the Odysee CDN links are made to change over time. Maybe i'll write a plugin for it when I have time.
> 
> * free.fullspeed.tv is down since a few months now.

Some ones I've tested are on air since 2 months or so.

**Review by UltraHDR — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
