### PR TITLE
Added ITV1 +1, HorrorXtra, More4, Really

### LINKED ISSUE #12459: Add: ITV1 +1 [UK]
### Channel ID

ITV1Plus1.uk

### Stream URL (optional)

https://cdnuk001.broadcastcdn.net/KUK-ITVPLUS1/tracks-v1a1/playlist.m3u8

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### PR DESCRIPTION
**Pull request by ExperiencersInternational**
Self explanatory.

Resolves #12459

### CODE REVIEW

**Comment by freearhey** [comment]
To link a pull request to an issue you need to use one of these words: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by freearhey — DISMISSED** [review]

**Review by BellezaEmporium — COMMENTED** [review]
Instead of using "/tracks-v1a1/playlist.m3u8" use "playlist.m3u8" directly, for the adaptive part

**Comment by ExperiencersInternational** [comment]
@BellezaEmporium would implement that change but it seems like some of the channels I've added here are now showing a looping video

Thanks broadcastcdn! I'm waiting for an alternative to broadcastcdn for a lot of these channels

**Comment by ExperiencersInternational** [comment]
Seems to be working again now.

**Review by freearhey — APPROVED** [review]

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
