### PR TITLE
Create ru_taurer.m3u

### LINKED ISSUE #16702: Add: Groovezzo
### Channel ID (required)

groovezzo.ru

### Channel Name

Groovezzo

### Stream URL (required)

https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/7.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #16703: Add: Криминал и Полиция (Criminal And Police) [RU]
### Channel ID (required)

criminalpolice.ru

### Channel Name

Криминал и Полиция

### Stream URL (required)

https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/5.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #16704: Add: NINJA [RU]
### Channel ID (required)

ninja.ru

### Channel Name

NINJA

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/3.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #16705: Add: RRTV Europe [RU]
### Channel ID (required)

rrtv.ru

### Channel Name

RRTV Europe

### Stream URL (required)

https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/6.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #16706: Add: World-1 [RU]
### Channel ID (required)

world1.ru

### Channel Name

World-1

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/7.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #16707: Add: KidsPlanet [RU]
### Channel ID (required)

kidsplanet.ru

### Channel Name

KidsPlanet

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/4.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #16708: Add: KidsPlanet+ [RU]
### Channel ID (required)

kidsplanetplus.ru

### Channel Name

KidsPlanet+

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/2.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #16709: Add: Quality HD [RU]
### Channel ID (required)

qualityhd.ru

### Channel Name

Quality HD

### Stream URL (required)

https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/6.m3u8

### Quality

1080p

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Dum4G**
Resolves #16702
Resolves #16703
Resolves #16704
Resolves #16705 
Resolves #16706
Resolves #16707
Resolves #16708
Resolves #16709

### CODE REVIEW

**Review by BellezaEmporium — COMMENTED** [review]
Erh... those are Xtream-Codes servers... I don't know.

**Comment by Dum4G** [comment]
Xtream-Codes servers from official domain?

**Review by BellezaEmporium — APPROVED** [review]

**Comment by PopeyeTheSai10r** [comment]
The following didn't load on my end. All the other ones are good.

```
https://nl2.live-stream.plus.taurer.org/RuCsPSXGYe/DgFExKzqEw/30.m3u8
https://nl2.live-stream.plus.taurer.org/RuCsPSXGYe/DgFExKzqEw/34.m3u8
https://nl2.live-stream.plus.taurer.org/RuCsPSXGYe/DgFExKzqEw/33.m3u8
```

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Please verify all EXTINF entries, they're wrongly formatted.

**Review by BellezaEmporium — APPROVED** [review]

**Review by Sphinxroot — APPROVED** [review]

**Pull request merged**
