### PR TITLE
IN = testing

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Apply workaround said in discussion about Hindi channels not working.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
&Privé won't work because of a weird issue linked to "accents" not being taken properly.

**Review by freearhey — DISMISSED** [review]

**Review by sguinetti — DISMISSED** [review]

**Review by freearhey — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
Server down, changing links to other versions.

**Review by freearhey — DISMISSED** [review]

**Comment by Dum4G** [comment]
image
@LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
> 
> 
> image @LaneSh4d0w

It just got shut down it seems. Gonna look for an alternative.

**Review by Dum4G — APPROVED** [review]

**Review by freearhey — APPROVED** [review]

**Pull request merged**
