### PR TITLE
add more to the mexican list

### PR DESCRIPTION
**Pull request by ghost**
not sure if everything other than the sports channels and cartoonito will be accepted, but a tudn link of the same structure was accepted and merged into the list, so i figured

### CODE REVIEW

**Comment by c4artisan** [comment]
the site hosting fox sports and cartoonito just..... died? it was working yesterday and earlier today, it might not be 24/7

**Comment by c4artisan** [comment]
nevermind lol it just doesn't like http

**Comment by c4artisan** [comment]
cartoonito died

**Comment by c4artisan** [comment]
nevermind, it just came back, this website is so weird

**Review by BellezaEmporium — COMMENTED** [review]
I have a doubt on the use of Astra channels. They might go as fast as they came in.
pop-app.live is a Spanish reseller afaik.
As for the Fox ones... eerh.

**Comment by c4artisan** [comment]
> I have a doubt on the use of Astra channels. They might go as fast as they came in. pop-app.live is a Spanish reseller afaik. As for the Fox ones... eerh.

in this case i have no idea what astra channels exactly are (channels in the satellites? or the links to literally everything except fox, cnito and claro)

i'll try my luck with only claro sports

**Review by BellezaEmporium — APPROVED** [review]
LGTM

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
