### PR TITLE
IR : Not 24/7 markers.

### LINKED ISSUE #4870: iFILM English
**Channel Name:** **ifilm English**
**Country:** Iran
**Language:** Farsi (in dubbed or English subtitle)
**Website:** https://en.ifilmtv.ir/
**Stream URL (optional):** xxx
**Notes (optional):** I have the full iptv-org and indexed by country. I used to have the ifilm English channel but it has disappeared! I have updated the IPTV Client a few times and I do see this channel (and some other ones) missing.

### PR DESCRIPTION
**Pull request by BellezaEmporium**

### CODE REVIEW

**Comment by Dum4G** [comment]
I bet it should be geo-blocked. Doesn't work for me but confirmed working by a Persian I know

**Review by jkemp814 — DISMISSED** [review]

**Comment by Dum4G** [comment]
I was occasionally trying to check those links but still none of them work

**Comment by jkemp814** [comment]
> I was occasionally trying to check those links but still none of them work

Link at line:196 streaming right now.

**Comment by LaneSh4d0w** [comment]
The Persian one works perfectly, however the English one really have bad times going well.

**Review by Dum4G — APPROVED** [review]

**Review by jkemp814 — APPROVED** [review]

**Pull request merged**
