### PR TITLE
Remove Offline Bracket

### PR DESCRIPTION
**Pull request by MapGuy11**

### CODE REVIEW

**Review by Dum4G — APPROVED** [review]

**Comment by jkemp814** [comment]
It will not load. That's why the bot flagged it.

**Comment by Dum4G** [comment]
They fixed it. Was manually flagged by MapGuy

**Comment by MapGuy11** [comment]
> They fixed it. Was manually flagged by MapGuy

Yeah as I was getting help from @LaneSh4d0w on the URL

**Comment by jkemp814** [comment]
I justd checked it. It is not loading.

**Comment by jkemp814** [comment]
The bot just ran 24 minutes ago, probably skipped it, but it will get flagged.

**Comment by MapGuy11** [comment]
Working Right Now
Screenshot from 2021-08-10 21-29-14

**Comment by jkemp814** [comment]
image

**Comment by MapGuy11** [comment]
Ctrl Shift R? maybe you have a cached version?

**Comment by jkemp814** [comment]
image

**Comment by Dum4G** [comment]
Wow. I got it working from the 2nd try

**Comment by MapGuy11** [comment]
Screenshot from 2021-08-10 21-34-55

**Comment by jkemp814** [comment]
Must be something on this end.

**Comment by MapGuy11** [comment]
Try this maybe to bypass Cloudflare: https://cdn88-theus6tv-tk-lmvemeyll-mapguy11.vercel.app/united-states/locals/philadelphia/wfmz-dt2.m3u8

**Comment by jkemp814** [comment]
That works.

image

**Comment by jkemp814** [comment]
As a base yes. Totally pass through. I tunnel thru a VPN and use their DNS.

**Pull request merged**
