### PR TITLE
Update format.js

### PR DESCRIPTION
**Pull request by freearhey**
After this update, links that return a [403 HTTP](https://en.wikipedia.org/wiki/HTTP_403) code will be marked as `[Geo-blocked]`. At the moment such links are marked as `[Offline]` and excluded from public playlists.

Test results: https://github.com/iptv-org/iptv/commit/c2182962eb66fd558dbb13e89aec3e2c7d937771

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Quick notice, some might return 403 because they're tokened and might not work because of this.

**Comment by freearhey** [comment]
If you know how to distinguish one from the other, let me know and I will take it into account in the code.

**Comment by LaneSh4d0w** [comment]
> 
> 
> If you know how to distinguish one from the other, let me know and I will take it into account in the code.

As one example : if your script knows how to read the DOM, if you see a message around those lines "Streamer protection has denied the access to this content", it is the Flussonic stream manager asking a token, and so will return "Forbidden".

**Comment by freearhey** [comment]
No, the script can't check that.

**Comment by LaneSh4d0w** [comment]
> 
> 
> No, the script can't check that.

If you want, I can give it the ability to make verifications inside the DOM. Using node-fetch (a little program) and some regular expressions to look after certain words or patterns, we may put it onto the "403" switch condition.

**Comment by freearhey** [comment]
Have you tested this code?

**Comment by LaneSh4d0w** [comment]
> 
> 
> Have you tested this code?

I'm looking at it. Code should work if placed on "Offline", for verification.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
Until I work on my solution to make it OK for production, i'll approve this.

**Review by dct-infra — APPROVED** [review]

**Pull request merged**
