### PR TITLE
add: YabanTV.tr

### PR DESCRIPTION
**Pull request by ramazansancar**

### CODE REVIEW

**Comment by ramazansancar** [comment]
#17760 fixed.

**Review by BellezaEmporium — COMMENTED** [review]
403 even with a Turkish IP. Are you sure your token isn't linked to your IP ?

**Comment by ramazansancar** [comment]
> 403 even with a Turkish IP. Are you sure your token isn't linked to your IP ?

I ask my friend to check. It may take a while.

**Comment by ramazansancar** [comment]
When he checked, he couldn't open it with a Turkish IP address. As you said, it could be an IP-based hash. @BellezaEmporium

**Pull request closed without merging**
