### PR TITLE
Update tr.m3u

### PR DESCRIPTION
**Pull request by YH7888**
TRT_Cocuk Channel has been updated. Now it is online and working

### CODE REVIEW

**Review by BellezaEmporium — COMMENTED** [review]
Neither link worked for me, even with a VPN set in Istanbul. TRT has slowly been moving his feeds into Amazon Cloudfront.

**Comment by Dum4G** [comment]
> Neither link worked for me, even with a VPN set in Istanbul. TRT has slowly been moving his feeds into Amazon Cloudfront.

Managed to get 403 without https, generated by CloudFront
image

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Comment by YH7888** [comment]
Thank you for updating the list. I am new here. How to update iptv list which is on country section? There is still old link.

**Comment by Dum4G** [comment]
It's gonna update itself in next 3 hours

**Comment by YH7888** [comment]
Thank you

**Pull request merged**
