### PR TITLE
Add BBC Red Button mpd

### PR DESCRIPTION
**Pull request by UltraHDR**

### CODE REVIEW

**Review by BellezaEmporium — COMMENTED** [review]
Precise it's MPD on the title, or else they won't show up.

**Comment by UltraHDR** [comment]
> Precise it's MPD on the title, or else they won't show up.

That's fine, m3u8 is deprecated by the broadcaster so I'm just adding them as a mirror. m3u8 is more supported by players

**Review by BellezaEmporium — APPROVED** [review]

**Review by freearhey — COMMENTED** [review]
I could not connect to any of the broadcasts, even with a VPN. So it's better to ask someone else for a review.

**Comment by sguinetti** [comment]
Sorry. 403 Forbidden for me.

**Comment by UltraHDR** [comment]
I've checked they work. Can you just approve it?

**Review by BellezaEmporium — APPROVED** [review]

**Review by sguinetti — APPROVED** [review]

**Pull request merged**
