### PR TITLE
Gone Gone Gone us.m3u

### PR DESCRIPTION
**Pull request by MapGuy11**
Please remove any streams with the domain theus6tv.tk or the6tv they are NEVER coming back

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]
Farewell, CDN87, CDN88.

**Comment by MapGuy11** [comment]
Please act fast we need these removed pronto.

**Review by Dum4G — APPROVED** [review]

**Comment by what-a** [comment]
😢

**Comment by MapGuy11** [comment]
> 😢

Yup sucks

**Pull request merged**
