### PR TITLE
update links and add channels

### PR DESCRIPTION
**Pull request by senhor-R**

### CODE REVIEW

**Review by Carlinhos027 — COMMENTED** [review]
Why do you delete so many channels? Most of them are working fine

**Comment by senhor-R** [comment]
sorry

**Comment by senhor-R** [comment]
only add this links is possible ?

**Comment by senhor-R** [comment]
what links can be added?

**Comment by Sphinxroot** [comment]
seem a bit messy here 
check link before removing them
use PLUTO TEMPLATE 
http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/xxxxxxxxxxxx/master.m3u8?deviceType=0&deviceModel=0&deviceMake=0&appVersion=0&deviceVersion=0&deviceDNT=0

**Pull request closed without merging**
