### PR TITLE
Update hk.m3u

### PR DESCRIPTION
**Pull request by AzeemHadzrie**

### CODE REVIEW

**Review by dct-infra — DISMISSED** [review]

**Review by BellezaEmporium — DISMISSED** [review]

**Review by Alstruit — DISMISSED** [review]

**Review by Alstruit — COMMENTED** [review]
All 185.207.176.189 links are down.

**Comment by AzeemHadzrie** [comment]
Let me fix that.

**Comment by AzeemHadzrie** [comment]
There, shall now test.

**Review by Alstruit — COMMENTED** [review]
Here's what I found from hkdtmb.com

港台電視31 (官方) ->  https://rthktv31-live.akamaized.net/hls/live/2036818/RTHKTV31/master.m3u8 (1080p) {Adaptive}
港台電視32 (官方) -> https://rthktv32-live.akamaized.net/hls/live/2036819/RTHKTV32/master.m3u8 (1080p) {Adaptive}
港台電視31 -> https://cdn.hklive.tv/xxxx/31/index.m3u8 [Geo-blocked] (1080p)
港台電視32 -> https://cdn.hklive.tv/xxxx/32/index.m3u8 [Geo-blocked] (1080p)
CCTV-1 (港澳版) -> 404 even with Geo IP
CGTN紀錄頻道 -> 404 even with Geo IP
香港國際財經台 -> 404 even with Geo IP
香港開電視 -> https://cdn.hklive.tv/xxxx/77/index.m3u8 [Geo-blocked] (1080p)
奇妙資訊台 -> https://cdn.hklive.tv/xxxx/78/index.m3u8 [Geo-blocked] (1080p) (Channel under development)
翡翠台 -> https://cdn.hklive.tv/xxxx/81/index.m3u8  [Geo-blocked] (1080p)
J2台 -> https://cdn.hklive.tv/xxxx/82/index.m3u8  [Geo-blocked] (1080p)
無綫新聞台 -> 404
明珠台 -> https://cdn.hklive.tv/xxxx/84/index.m3u8  [Geo-blocked] (1080p)
明珠台 (粵語聲道) -> https://cdn.hklive.tv/xxxx/84b/index.m3u8  [Geo-blocked] (1080p)
財經 體育 資訊台 -> 404
ViuTV Six -> https://cdn.hklive.tv/xxxx/96/index.m3u8  [Geo-blocked] (1080p)
ViuTV -> https://cdn.hklive.tv/xxxx/99/index.m3u8  [Geo-blocked] (1080p)
ViuTV (官方) -> DASH MPD DRM

The website returns 404 error if the IP is not in HK.

**Review by Alstruit — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
