### PR TITLE
Update jp.m3u

### PR DESCRIPTION
**Pull request by Alstruit**
Requires iptv-org/database#5073

### CODE REVIEW

**Comment by solo489** [comment]
Add more channels

**Review by Carlinhos027 — DISMISSED** [review]

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
I'm afraid I can't accept the willfonk ones. Been told twice not to add those links, and we've already been asked to remove them in the past. Linked to https://github.com/iptv-org/iptv/issues/7160

**Comment by Alstruit** [comment]
> I'm afraid I can't accept the willfonk ones. Been told twice not to add those links, and we've already been asked to remove them in the past. Linked to #7160

Ok sorry I did not see that. I made a comment regarding about that.

**Comment by BellezaEmporium** [comment]
> > I'm afraid I can't accept the willfonk ones. Been told twice not to add those links, and we've already been asked to remove them in the past. Linked to #7160
> 
> Ok sorry I did not see that. I made a comment regarding about that.

I'll check the vthanhtivi ones.

**Comment by Alstruit** [comment]
Hmm it looks like the vthanhtivi no longer work.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by Alstruit** [comment]
Ok now vthanhtivi works. I'll add it later in another PR if it is stable.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
