### PR TITLE
Updated languages and logos for few MAL Channels

### LINKED ISSUE #4152: Jeevan TV
**Channel Name:** Jeevan TV
**Country:** IN
**Language:** Malayalam
**Website:** http://jeevannewsonline.com/
**Stream URL (optional):** https://mhdtvworld.xyz/fcbb59e4-1e00-40a3-b854-a9655d8d53a4
**Notes (optional):** xxx

### PR DESCRIPTION
**Pull request by Niyasmkkv**
Closes https://github.com/iptv-org/iptv/issues/4152

### CODE REVIEW

**Comment by Dum4G** [comment]
It's better not to use tvg logos exceeding 300x300 size and avoid redirects. Imagine additional loading times of such a massive playlist because your player has to resolve and resize those pics

**Comment by Niyasmkkv** [comment]
> It's better not to use tvg logos exceeding 300x300 size and avoid redirects. Imagine additional loading times of such a massive playlist because your player has to resolve and resize those pics

Will change it.

**Comment by Dum4G** [comment]
I'd recommend to reupload them all and check the ones that are way to big like the first one. You can keep pushing commits into patch-5 branch, any change will appear in this PR

**Comment by Dum4G** [comment]
Strange world we live in. My ISP is blocking logolynx.com. That's why it's a good measure to reupload logos on imgur

**Comment by Niyasmkkv** [comment]
All logos were uploaded with Imgur. But it was not reflecting. That's why I re-uploaded them.

**Comment by Dum4G** [comment]
> All logos were uploaded with Imgur. But it was not reflecting. That's why I re-uploaded them.

That's because someone posted them as album. And unfortunately some of them were still way too big.

After uploading images to imgur it's needed to:
Refresh page
Open an image in a new tab
Use that link

**Review by heroku-miraheze — APPROVED** [review]

**Review by Sphinxroot — APPROVED** [review]

**Comment by Dum4G** [comment]
Good. If you wish, you can start adding channels that have been found for you or I'll merge it as it is

**Comment by Niyasmkkv** [comment]
> Good. If you wish, you may start adding channels that have been found for you or I'll merge it as it is

You do that. I'm still a noob here.

**Pull request merged**
