### PR TITLE
CN: Remove broken links

### PR DESCRIPTION
**Pull request by freearhey**
Removed links with "error" status.

All links are checked from two different regions at different times of the day with the [playlist:cleaner](https://github.com/iptv-org/iptv/blob/master/scripts/commands/playlist/cleaner.js) script.

Links marked as `[Not 24/7]` or `[Geo-blocked]` were skipped.

### CODE REVIEW

**Review by its0x08 — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
To be honest the Chinese playlist is a big mess of dupes and non-working links. I had a dormant PR that had loooots of things changed. Maybe we shall make a fusion of those 2 to have, in one case duped links deleted, in another case new links and some channels moved to HK, and some new channels.

**Comment by freearhey** [comment]
Maybe you can run the script on your machine

```
npm run playlist:cleaner -- streams/cn.m3u
```

and do a PR with all the changes?

**Comment by LaneSh4d0w** [comment]
> Maybe you can run the script on your machine
> 
> ```
> npm run playlist:cleaner -- streams/cn.m3u
> ```
> 
> and do a PR with all the changes?

I'll look at it.

**Comment by freearhey** [comment]
Then I'll close this for now.

**Comment by LaneSh4d0w** [comment]
> Then I'll close this for now.

I'll make the necessary changes directly into your PR. Mine dates from before playlist changes

**Pull request closed without merging**
