### PR TITLE
Add Rodja TV

### PR DESCRIPTION
**Pull request by liimee**
Added Rodja TV channel to id.m3u

### CODE REVIEW

**Review by F640 — COMMENTED** [review]
It seems geo-blocked to Indonesia, but it works.

**Comment by liimee** [comment]
Oh, right

**Review by what-a — APPROVED** [review]

**Review by BellezaEmporium — COMMENTED** [review]
Doesn't seem to answer for me now, Not 24/7 ?

**Review by its0x08 — APPROVED** [review]

**Comment by liimee** [comment]
> Doesn't seem to answer for me now, Not 24/7 ?

let me check

**Review by BellezaEmporium — APPROVED** [review]
Confirmed working afterwards.

**Pull request merged**
