### PR TITLE
Update bf.m3u

### PR DESCRIPTION
**Pull request by capiou**
Update m3u8 link for the RTB channel.
Previous link no longer working

### CODE REVIEW

**Comment by capiou** [comment]
please update the link as requested.
Thank You

**Comment by MapGuy11** [comment]
It's not geoblocked for me in the U.S. also change to playlist.m3u8 instead of manifest.m3u8

**Review by MapGuy11 — COMMENTED** [review]
It's not geoblocked for me in the U.S. also change to playlist.m3u8 instead of manifest.m3u8

**Review by dct-infra — DISMISSED** [review]

**Review by Dum4G — COMMENTED** [review]
Isn't geo-blocked for me too

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
Works for me, not geo-locked.

**Comment by LaneSh4d0w** [comment]
Did the same for Impact TV, and fixed another channel in the same instance.

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
