### PR TITLE
PE : Modify link for Latina

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Reason : wrong link + redirects to a 42 seconds video saying that content isn't available outside of the Peruvian territory

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
+ Asking @sguinetti to confirm that link does not work

**Comment by sguinetti** [comment]
New tv online website: https://www.latina.pe/tvenvivo

**Comment by LaneSh4d0w** [comment]
Works for me. It's using MDSTRM, that does the link with the actual source. Changing link.

**Comment by LaneSh4d0w** [comment]
@sguinetti Verify if this link works.

**Comment by sguinetti** [comment]
Wait if this link will be preserved for hours, because the web may use token.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Wait if this link will be preserved for hours, because the web may use token.

This link was tokened, i took them off and it still works.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
