### PR TITLE
JP : Add lots of channels

### PR DESCRIPTION
**Pull request by BellezaEmporium**
From BS12 : it's foreign channels, dubbed in Japanese (Red Bull TV / Disney Channel as an example for BS12-BS13)

### CODE REVIEW

**Comment by Dum4G** [comment]
Don't forget those are all geo-blocked and require user-agent, at least for me

**Comment by LaneSh4d0w** [comment]
Interesting, those work for me.
vlcsnap-2021-07-17-00h27m21s228
vlcsnap-2021-07-17-01h19m31s436
vlcsnap-2021-07-17-01h42m30s154

**Comment by Dum4G** [comment]
Wow, a tried one from a phone and it just worked. Maybe some of them are geo-blocked

**Comment by LaneSh4d0w** [comment]
Probably.

I'll try everything. But even TV Tokyo worked for me without anything, when
you had issues with it.

It's like the reverse situation of last time's issues.

**Comment by LaneSh4d0w** [comment]
I confirm, Tokyo MX1 and TV Tokyo works perfectly for me.

(I'm even more surprised, the Ryowa streams did really step up ! They work perfectly fine !)

**Comment by LaneSh4d0w** [comment]
@Dum4G I'll let you verify them one by one. You can add the "Geo-blocked" and user-agent on your own if you think there's the need to add it.

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
