### PR TITLE
Update sd.m3u

### PR DESCRIPTION
**Pull request by UltraHDR**

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]

**Review by freearhey — COMMENTED** [review]
The `status` attribute is updated automatically during daily checks, there is no need to update it manually.

**Comment by LaneSh4d0w** [comment]
> The `status` attribute is updated automatically during daily checks, there is no need to update it manually.

I was thinking maybe we could port our channel verification trigger up to the PRs too. It could render a message telling if the channel is online / offline. Thus we can easily get a geo-block or if it's an issue server or script-related.

**Comment by freearhey** [comment]
@LaneSh4d0w This is a good idea! I can't do it myself yet, but you can post it in the Discussions and maybe someone will implement it sooner.

**Comment by UltraHDR** [comment]
> The `status` attribute is updated automatically during daily checks, there is no need to update it manually.

Thanks. I'm aware. I noticed it was always wrong.. Is it online for you now?

**Comment by freearhey** [comment]
> Is it online for you now?

Yes.

**Pull request closed without merging**
