### PR TITLE
Update pe.m3u

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request adds television station from Radio Tropical, Genios TV, Gaceta Ucayalina and other peruvian channels.

### CODE REVIEW

**Review by BellezaEmporium — COMMENTED** [review]
Seems good for now.

**Comment by sguinetti** [comment]
I added other local channels for review. Not yet ready to merge.

**Review by BellezaEmporium — COMMENTED** [review]
Perfect, all links work for me. Keep it up :)

**Comment by sguinetti** [comment]
Thank you, ready to review and merge.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
Thank you !

**Pull request merged**
