### PR TITLE
Fix Brazil EPG

### PR DESCRIPTION
**Pull request by allanf181**

### CODE REVIEW

**Comment by freearhey** [comment]
Where exactly did you get the new tvg-id from?

**Comment by allanf181** [comment]
https://siptv.app/codes/

Enviado do Yahoo Mail no Android 
 
  Em ter., 21 21e set. 21e 2021 às 4:57, Aleksandr ***@***.***> escreveu:   


Where exactly did you get the new tvg-id from?

**Review by freearhey — CHANGES_REQUESTED** [review]
The thing is that we try to use our own [code list](https://iptv-org.github.io/epg/index.html) where possible to add a program to as many channels as possible.

**Comment by allanf181** [comment]
I don't know if it has a standard but other iptv providers in Brazil use the same codes as https://siptv.app/codes/

**Comment by allanf181** [comment]
anyway there are other things in my fix like channels with wrong name and duplicate channels

**Comment by freearhey** [comment]
There is no standard and each provider can use any list of codes.

What duplicates are we talking about?

**Comment by allanf181** [comment]
https://github.com/iptv-org/iptv/blob/master/channels/br.m3u#L100
https://github.com/iptv-org/iptv/blob/master/channels/br.m3u#L222

**Comment by freearhey** [comment]
Now I see.

**Comment by freearhey** [comment]
@allanf181 you still need to bring back the old id so we can approve the rest of the changes

**Comment by allanf181** [comment]
done

**Comment by freearhey** [comment]
please check again

**Review by freearhey — APPROVED** [review]

**Pull request merged**
