### PR TITLE
Rework other issue templates

### PR DESCRIPTION
**Pull request by Dum4G**
Modernization continues

### CODE REVIEW

**Comment by Dum4G** [comment]
I'm out of ideas why brokean stream template is having issues, help is needed

**Comment by LaneSh4d0w** [comment]
Maybe not assign @freearhey directly on any bug that happens. If the bug is concerning the scripts, I might understand, as he created the code and understands it more than anyone else. But for the streams it's a bad idea I think. He's most certainly busy with other things at the same time =).

**Comment by Dum4G** [comment]
For problematic streams we have a broken stream tag

**Comment by LaneSh4d0w** [comment]
Please review the new broken_stream.yml, as I have given a few corrections myself, in terms of certain formulations.

**Comment by Dum4G** [comment]
I'm fine with them

**Review by BellezaEmporium — APPROVED** [review]

**Review by MapGuy11 — APPROVED** [review]

**Pull request merged**
