### PR TITLE
Delete streams/us_moveonjoy.m3u

### LINKED ISSUE #17153: Add: Starz East (US)
### Channel ID (required)

StarzEast.us

### Channel Name

Starz East

### Stream URL (required)

http://fl2.moveonjoy.com/STARZ/index.m3u8

### Quality

None

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #17164: Add: MGM+ Hits East (US)
### Channel ID (required)

MGMPlusHitsEast.us

### Channel Name

MGM+ Hits East

### Stream URL (required)

http://fl2.moveonjoy.com/EPIX_HITS/index.m3u8

### Quality

None

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #17274: Add: TV One (US)
### Channel ID (required)

TVOne.us

### Channel Name

TV One

### Stream URL (required)

http://fl2.moveonjoy.com/TV_ONE/index.m3u8

### Quality

None

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #17277: Add: Crave 2 (CA)
### Channel ID (required)

Crave2.ca

### Channel Name

Crave 2

### Stream URL (required)

http://fl2.moveonjoy.com/CRAVE_2/index.m3u8

### Quality

None

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #17278: Add: Crave 1 (CA)
### Channel ID (required)

Crave1.ca

### Channel Name

Crave 1

### Stream URL (required)

http://fl3.moveonjoy.com/CRAVE_1/index.m3u8

### Quality

None

### Label

None

### Timeshift

_No response_

### HTTP User Agent

_No response_

### HTTP Referrer

_No response_

### Notes

_No response_

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by ghost**
Also Closes #17278, Closes #17277, Closes #17276, Closes #17275, Closes #17274, Closes #17164, Closes #17153

Reason: If we don't remove these links then mother of @ILIKECATS187 will cry while waiting for his son (the owner of these links) to get out of prison

### CODE REVIEW

**Comment by ILIKECATS187** [comment]
but since dude is a dick i forwared this to all USA cable companie and every network possible just sop you guys eat shit  from this one dude that racist ! 


ALLL [boogabooga841](https://github.com/boogabooga841) fault !

**Review by BellezaEmporium — APPROVED** [review]
Witty discussion for witty results.

**Review by Sphinxroot — APPROVED** [review]
as they are leaked  they are everywhere since a while

https://github.com/search?q=http%3A%2F%2Ffl2.moveonjoy.com%2F&type=code
https://www.google.com/search?client=firefox-b-d&q=http%3A%2F%2Ffl2.moveonjoy.com%2F

**Comment by ILIKECATS187** [comment]
moveon joy is just a redirect you guys made ...... the channels all come  from cvalley chariton cable .......

**Pull request merged**
