### PR TITLE
RO : Add Mooz music channels

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Found them out while going around.
vlcsnap-2021-10-02-16h50m17s796
vlcsnap-2021-10-02-16h50m41s609
vlcsnap-2021-10-02-16h50m51s655

### CODE REVIEW

**Review by dct-infra — CHANGES_REQUESTED** [review]
403 error on the 3 streams. maybe geoblocked?

**Comment by jkemp814** [comment]
Same here. Will not stream.

**Comment by LaneSh4d0w** [comment]
Possibly, I am in RO, so that might explain why x)

**Comment by LaneSh4d0w** [comment]
Try now.

**Comment by jkemp814** [comment]
All three work using vlc https://rtmp.digitalbroadcast.ro/moozhits/moozhits.m3u8 :http-referrer=https://mooz.tv/

Is that how you use it at command line?

**Comment by LaneSh4d0w** [comment]
> 
> 
> All three work using:
> 
> vlc https://rtmp.digitalbroadcast.ro/moozhits/moozhits.m3u8 :http-referrer=https://mooz.tv/
> 
> Is that how you use it at command line?

The #EXTVLCOPT does the same basically, yes. Glad it worked out for you with the referrer.

**Review by jkemp814 — DISMISSED** [review]

**Review by dct-infra — DISMISSED** [review]
works with the referrer

**Comment by LaneSh4d0w** [comment]
Added image + type

**Review by freearhey — APPROVED** [review]

**Review by jkemp814 — APPROVED** [review]

**Pull request merged**
