### PR TITLE
Update list of supported categories

### PR DESCRIPTION
**Pull request by freearhey**
Inspired by #2224

Renamed:
- Food to Cooking
- Hobby to Outdoor
- Sport to Sports

Merge:
- Fashion with Lifestyle
- History with Documentary
- Quiz with Entertainment
- Sci-Fi with Movies

Added:
- Animation
- Culture
- Relax
- Science
- Series

Removed:
- Fashion
- Health
- History
- Quiz
- Sci-Fi

The final version of the list can be found [here](https://github.com/iptv-org/iptv/blob/master/.readme/supported-categories.md).

### CODE REVIEW

**Comment by Dum4G** [comment]
Crime, Drama and Horror mostly fall into Movies category. In fact, I know only a single channel that falls into Crime category and it won't be in the playlist (Зал суда). Animation wording isn't meaningful to me, I'd used Cartoon instead. Food category can be renamed as Cooking.

**Comment by LaneSh4d0w** [comment]
>
>     * Do we have to consider Relax channels that show nothing but fireplace, waterfall or nature views as channels worth being in playlist?

Yup, channels like "Nature 24h" or some stuff.

**Comment by LaneSh4d0w** [comment]
> 
> 
>     * Crime, Drama and Horror mostly fall into Movies category. In fact, I know only a single channel that falls into Crime category and it won't be in the playlist (Зал суда).
> 
>     * Shall we separate Series as a category?
> 
>     * Shall we rename Quiz into Shows or consider Зал суда as a Series?
> 
>     * **Entertainment is okay category** and should be associated with channels that fall into Comedy, Movies, Series, Cartoons and maybe Travel categories at the same time (ТНТ, Стс, Пятница, Рен, ТВ3)
> 
>     * Animation wording isn't meaningful to me, I'd use Cartoon instead.
> 
>     * Food category should be renamed as Cooking.
> 
>     * Culture related to art and culture was also a great addition, perhaps it's a better naming and explanation for Classic category.
> 
>     * Do we have to consider Relax channels that show nothing but fireplace, waterfall or nature views as channels worth being in playlist?

Basically all versions of A+E Crime are into the Crime section.

About the choices : 

- I would say the same, or at least regroup all of them into an single "Horror" category
- It would be better for those channels that only air TV shows (some AMC variants as an example)
- Hmmm... i don't even understand why we have a Quiz category... is there **really** a channel that exists that only broadcasts Quizzes ?
- Entertainment is also OK for me
- Well, Cartoon (per se) would be limited to drawn things (the essence of cartoons comes from drawn characters). Animation englobes both 2D and 3D worlds.
- OK for that.
- Well, "Classic" has got no meaning... what would we consider as "Classic" today might not be the same tastes tomorrow.

**Comment by Dum4G** [comment]
> Hmmm... i don't even understand why we have a Quiz category... is there really a channel that exists that only broadcasts Quizzes?

I do know a channel like that. But there's not so many of them, so I guess we need a category not only for Quizz channels but for any channel that broadcast TV shows only.

> I would say the same, or at least regroup all of them into an single "Horror" category

We have keep one thing in mind - categories should not become a pain in the ass. Out of 11442 channels present in the index list 9020(!) channels are not caterigorized. That's 79% of playlist. In my opinion some categories should cover as much cases as they can, much like the laws are being written. 

Also what kind of content is considered as family-friendly? It's just 16 channels and as far as I can tell those show movies and literally have family in the name.

**Comment by LaneSh4d0w** [comment]
> > Hmmm... i don't even understand why we have a Quiz category... is there really a channel that exists that only broadcasts Quizzes?
> 
> I do know a channel like that. But there's not so many of them, so I guess we need a category not only for Quizz channels but for any channel that broadcast TV shows only. I think that's different from an actual series that have a plot and fixed casting
> 
> > I would say the same, or at least regroup all of them into an single "Horror" category
> 
> We have keep one thing in mind - categories should not become a pain in the ass. Out of 11442 channels present in the index list 9020(!) channels are not caterigorized. That's 79% of playlist. In my opinion some categories should cover as much cases as they can, much like the laws are being written. 
> 
> Also what exactly is a family-friendly content? It's just 16 channels and as far as I can tell those show movies and literally have family in the name. 

Family Friendly would be basically anything that can be seen by everyone (kids stuff and movies rated E (Everyone) basically)

**Comment by freearhey** [comment]
List updated.

Renamed:
- Food to Cooking

Added:
- Culture
- Entertainment
- Series

Removed:
- Crime
- Quiz

**Comment by Dum4G** [comment]
Since only one person is vocal in this thread here's my final vision

Category | Definition
-- | --
Auto | Programming related to automobiles and motorbikes
Business | Programming related to business
Cartoon | Anime, cartoons and similar that is not suitable for all ages (refer to PEGI12 or ESRB Everyone 10+)
Cooking | Programs related to cooking or food in general
Culture | Programming is mostly about art and culture from earlier decades
Comedy | Programming is mostly comedy
Documentary | Programming that depicts a person, real-world event, cultures or nature
Education | Programming is intended to be educational
Entertainment | Programming that falls into Comedy, Movies, Series, Cartoons and Shows categories altogether
Family | Programming that is purposely "Family Friendly" (refer to PEGI12 or ESRB Everyone 10+)
General | Provides a variety of different programming
Kids | Programming targeted to children
Legislative | Programming specific to the operation of government
Lifestyle | Health, fitness, leisure, fashion, decor and etc.
Local | Channels that are targeted for a local area or region
Movies | Channels that only show movies
Music | Programming is music or music related
News | Programming is news, analytics or weather forecasts
Outdoor | Programming related to outdoor activities like fishing, hunting etc.
Series | Channels that only show series
Shows | Programming is mostly seasoned or thematic shows and quizzes
Relax | Programming is calm sounding and beautiful views
Religious | Religious Programming
Science | Science and Technology
Shop | Programming is for shopping
Sport | Programming is sports
Travel | Programming is travel related
XXX | Programming is adult oriented and x-rated
Other | No category assigned

What has been done:
Series category is added and described
Relax category is added and described
Entertainment category is added and described
Relax category is added and described

Classic category is replaced with Culture and redescribed
Quiz category is replaced with Shows and redescribed

Animation category is renamed to Cartoon as it's more popular style and wording (refer Cartoon Network)
Food category is renamed as Cooking.

Removed Crime, Drama and Horror categories
Removed Weather category. Seriously, is there a single human being interested in forecast playlist in foreign languages?
Removed Reality category. I suppose channels of this kind fit Lifestyle and Shows categories

**Comment by LaneSh4d0w** [comment]
> 
> 
> Here's my final vision
> Category 	Definition
> Auto 	Programming related to automobiles and motorbikes
> Business 	Programming related to business
> Cartoons 	Anime, cartoons and similar that is not suitable for all ages (refer to PEGI12 or ESRB Everyone 10+)
> Cooking 	Programs related to cooking or food in general
> Culture 	Programming is mostly about art and culture from earlier decades
> Comedy 	Programming is mostly comedy
> Documentary 	Programming that depicts a person, real-world event, cultures or nature
> Education 	Programming is intended to be educational
> Entertainment 	Programming that falls into Comedy, Movies, Series, Cartoons and Shows categories altogether
> Family 	Programming that is purposely "Family Friendly" (refer to PEGI12 or ESRB Everyone 10+)
> General 	Provides a variety of different programming
> Kids 	Programming targeted to children
> Legislative 	Programming specific to the operation of government
> Lifestyle 	Health, fitness, leisure, fashion, decor and etc.
> Local 	Channels that are targeted for a local area or region
> Movies 	Channels that only show movies
> Music 	Programming is music or music related
> News 	Programming is news, analytics or weather forecasts
> Outdoor 	Programming related to outdoor activities like fishing, hunting etc.
> Series 	Channels that only show series
> Shows 	Programming is mostly seasoned or thematic shows and quizzes
> Relax 	Programming is calm sounding and beautiful views
> Religious 	Religious Programming
> Science 	Science and Technology
> Shop 	Programming is for shopping
> Sport 	Programming is sports
> Travel 	Programming is travel related
> XXX 	Programming is adult oriented and x-rated
> Other 	No category assigned
> 
> What has been done:
> Series category is added and described
> Entertainment category is added and described
> Relax category is added and described
> 
> Classic category is replaced with Culture and redescribed
> Quiz category is replaced with Shows and redescribed
> 
> Animation category is renamed to Cartoon as it's more popular style and wording (refer Cartoon Network)
> Food category is renamed as Cooking.
> 
> Removed Crime, Drama and Horror categories
> Removed Weather category. Seriously, is there a single human being interested in forecast playlist in foreign languages?
> Removed Reality category. I suppose channels of this kind fit Lifestyle and Shows categories

Well there's some weather channels existing (for example WNI in Japan, or La Chaîne Météo in France), so no purpose of deleting it.

**Comment by Dum4G** [comment]
> Well there's some weather channels existing (for example WNI in Japan, or La Chaîne Météo in France), so no purpose of deleting it.

Can you imagine someone who's watching those channels all day no matter what? In my POV those channels belong to News category

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Well there's some weather channels existing (for example WNI in Japan, or La Chaîne Météo in France), so no purpose of deleting it.
> 
> Can you imagine someone who's watching those channels all day no matter what? In my POV those channels belong to News category

We might not see it everyday, but the purpose of the channel is basically informing about weather and nothing else basically... so well.

**Comment by Dum4G** [comment]
I feel like Auto category is all about reviews and motorized sports, so technically we can have it as a separated category

**Comment by LaneSh4d0w** [comment]
> 
> 
> I feel like Auto category is all about reviews and motorized sports, so technically we can have it as a separated category

Same as for the outdoor section when you think about it.

**Comment by LaneSh4d0w** [comment]
Here's my personal view on this : 

Category | Definition
-- | --
Animation | Program is mainly axed on animated cartoons and/or not limited to 2D/3D animation. 
Business | Programming related to business
Cooking | Programs related to cooking or food in general
Culture | Programming is mostly about art and culture from earlier decades
Comedy | Program is axed on comedy / humor
Documentary | Programming that depicts a person, real-world event, cultures or nature
Education | Programming is mostly axed on educational content
Entertainment | Programming that is mostly made for entertaining in any way (not to confound with Adult entertainment, that is XXX)
Family | Programming that is purposely "Family Friendly" (refer to PEGI12 or ESRB Everyone 10+)
General | Programming is diverse and do not enter in any of those categories in particular.
Kids | Programming targeted to children
Legislative | Programming specific to governmental operations
Lifestyle | Programming axed on health, fitness, leisure, fashion, decor and etc.
Local | Channels that are targeted for a local area or region
Movies | Channels that only show movies
Music | Program is axed on music-related shows
News | Programming is news, analytics or weather forecasts
Outdoor | Programming related to outdoor activities like fishing, hunting etc.
Relax | Programming is calm sounding and beautiful views
Religious | Religious Programming
Science | Science and Technology
Series | Program is axed on TV shows, actual or old.
Shop | Program is axed on shopping
Shows | Programming is mostly seasoned or thematic shows and quizzes
Sports | Programming is mainly axed on sports (live sports, news etc..)
Travel | Programming is travel related
XXX | Programming is adult oriented and X-rated
Other | No category assigned

**Comment by freearhey** [comment]
List updated.

Renamed:
- Sport to Sports

Added:
- Relax

Removed:
- Reality

**Pull request merged**
