### PR TITLE
Remove id-tv.kz

### PR DESCRIPTION
**Pull request by Dum4G**
It's finally... dead? Returns 403. May have become geo-blocked, needs verification from kz

### CODE REVIEW

**Review by freearhey — DISMISSED** [review]

**Review by BellezaEmporium — COMMENTED** [review]
Simply GEO.

https://smart-tv.id-tv.kz / https://online.id-tv.kz/

**Comment by Dum4G** [comment]
> Simply GEO.

But did you manage to get any of those channels working? Any channel on their website is throwing an error, even with VPN
`Access to XMLHttpRequest at 'https://sc.id-tv.kz/1KanalEvraziya.m3u8' from origin 'https://smart-tv.id-tv.kz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by BellezaEmporium** [comment]
> > Simply GEO.
> 
> But did you manage to get any of those channels working? Any channel on their website is throwing an error, even with VPN `Access to XMLHttpRequest at 'https://sc.id-tv.kz/1KanalEvraziya.m3u8' from origin 'https://smart-tv.id-tv.kz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I have a CORS plugin in order to fix that. Tells me "403 Forbidden".

**Comment by Dum4G** [comment]
They also have some shady plugin that they want to install via .msi file

**Review by freearhey — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
