### PR TITLE
Remove broken Tele Liban link

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by heroku-miraheze** [comment]
The link works in an origin country, so, don't delete it.

**Comment by Dum4G** [comment]
> The link works in an origin country, so, don't delete it.

Are you Palestinian to confirm that? Show proves then

**Comment by LaneSh4d0w** [comment]
> 
> 
> > The link works in an origin country, so, don't delete it.
> 
> Are you Palestinian to confirm that? Show proves then

Lebanese*, not Palestinian.

If he thinks the link works, then we'll let him show proof of what he says.

**Comment by Dum4G** [comment]
> Lebanese*, not Palestinian.

I did a bit of a research yesterday, an IP adress belongs to BCI Telecommunication & Advanced Technology Company located in Palestine. The links were definitely not supposed to be publically available

https://apps.db.ripe.net/db-web-ui/query?bflag=false&dflag=false&rflag=true&searchtext=93.184.1.247&source=RIPE
https://www.ripe.net/membership/indices/data/ps.bnet.html

**Comment by LaneSh4d0w** [comment]
> 
> 
> > Lebanese*, not Palestinian.
> 
> I did a bit of a research yesterday, the IP adress belongs to BCI Telecommunication & Advanced Technology Company located in Palestine. Provided links were definitely not supposed to be publicly available
> 
> https://apps.db.ripe.net/db-web-ui/query?bflag=false&dflag=false&rflag=true&searchtext=93.184.1.247&source=RIPE
> https://www.ripe.net/membership/indices/data/ps.bnet.html

Maybe this channel is hosted in Palestine and geo-locked to Liban.

Seems to me that's a telecom service / provider. Could be possible that someone hosted it before finding out that it should be geo-locked.

**Pull request merged**
