### PR TITLE
UY: Update Latino Kids

### PR DESCRIPTION
**Pull request by sguinetti**
The PR uses a aditional url from m3u.cl.

### CODE REVIEW

**Comment by Dum4G** [comment]
Is it something that belongs to them or specifically hosted for them?

**Comment by LaneSh4d0w** [comment]
Well... I must say I don't understand why the additional query parameter would lock/unlock anything.

**Comment by sguinetti** [comment]
The url stream is now inaccessible with strict origin, but addding parameter would make the stream works without problems.

**Comment by LaneSh4d0w** [comment]
I personally don't have issues with the original link. What's your player ?

**Comment by sguinetti** [comment]
> I personally don't have issues with the original link. What's your player ?

VLC, yesterday.

**Comment by sguinetti** [comment]
I close for now. However, for this possible problem, this solution may be invoked.

**Pull request closed without merging**
