### PR TITLE
Add some channels

### PR DESCRIPTION
**Pull request by BellezaEmporium**

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
About Canal + HD : it is an Astra version, so whenever it is on encrypted mode, it'll only stream sound. When they're on decrypted mode, video starts to show up. The pleasure of their own encryption system.

**Comment by LaneSh4d0w** [comment]
GitHub Desktop decided that the new line at the end of the document wasn't useful...

**Comment by heroku-miraheze** [comment]
@LaneSh4d0w This pull request will add all channels worldwide???

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w This pull request will add all channels worldwide???

Not the intention to, but it's going to be a huge pack.

**Comment by LaneSh4d0w** [comment]
Will be good for now. R2R.

**Review by Sphinxroot — APPROVED** [review]
TF1 

http://cdn.gledaitv.co:2200/EX/FR_TF1_HD-fr/playlist.m3u8?token=

Nice Finding :)

**Comment by LaneSh4d0w** [comment]
Nice one :)

**Comment by Sphinxroot** [comment]
> Nice one :)

i will play arround whit naming . im sure there plenty  . i just wonder how mutch time they will be online

**Comment by LaneSh4d0w** [comment]
I didn't even expect seeing beIN Sports channels in it, and they're working pretty well with a 1080p quality. Quite impressed.

**Comment by LaneSh4d0w** [comment]
From what I've seen from a website having the same name (bg-gledai.co) they seem to be Russian.

**Pull request merged**
