### PR TITLE
US: TVS fixes

### PR DESCRIPTION
**Pull request by Dum4G**
From https://github.com/iptv-org/iptv/pull/3151/ with some more changes

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Are you sure the TVS fixes needed 13k changes on the list ? haha

**Comment by Dum4G** [comment]
Since I broke diff here's what I did
#EXTINF:-1 tvg-id="NewsNOWfromFox.us" tvg-name="NewsNOW from Fox" tvg-country="US" tvg-language="" tvg-logo="" group-title="",NewsNOW from Fox
http://fox-foxnewsnow-samsungus.amagi.tv/playlist360p.m3u8 to playlist360p.m3u8 
Fixed TVS channels with proper index links

**Comment by Dum4G** [comment]
Sorted everything out, however, US list needs some massive cleanup

**Comment by LaneSh4d0w** [comment]
I'm working on that, in my massive cleanup PR.

By the way, you don't even need to have the "tracksa1-v1" parts, try without that and you'll see that'll work :p

**Pull request merged**
