### PR TITLE
Update us.m3u

### PR DESCRIPTION
**Pull request by what-a**
The Sci-Fi 4U stream is actually 480p and not 720p. I double checked.

### CODE REVIEW

**Review by Dum4G — APPROVED** [review]

**Review by dct-infra — COMMENTED** [review]
shows 720p for me...

**Comment by Dum4G** [comment]
> shows 720p for me...

I think he means upscaled content this channel is broadcasting
image

**Comment by LaneSh4d0w** [comment]
#EXT-X-STREAM-INF:BANDWIDTH=3264551,CODECS="avc1.66.13,mp4a.40.2",RESOLUTION=1137x720

in playlist.m3u8. Might be upscaled, but the resolution is 720p whatsoever.

**Comment by what-a** [comment]
Thanks for the feedback.  Yeah, I'm now seeing 720p as well. 
image

**Pull request closed without merging**
