### PR TITLE
Add more ID stations

### PR DESCRIPTION
**Pull request by Hans5958**
Hello. In this PR I have added some channels from Indonesia, one is the regional stations of TVRI (state-sponsored TV channel), and the legislative channels of TVR Parlemen. This is the first time I contribute on this repo. Any assistance and/or comments are appreciated.

I also renamed some channels for safe keeping.

Some notes:
- I have added a backup of all TVRI channels based on what it has currently. I have tried to add `(Backup)`, but I saw that it is removed a lot of commits ago, so, if there's a need to change related to this, please let me know.
- Some channels of TVR Parlemen are only online occasionally. I know for the fact that the operation time is 09.00 to 22.00 Western Indonesian Time (GMT+07), but there are some that uses a placeholder when it is offline (all the commisions), and there are some that are outright offline (the others).  So, let this be a consideration.
  For example, here's the current state of the channels. Different time of day will have different states.
  - Online: Main (TVR Parlemen), Komisi II, V, VIII, XI, BAKN
  - Offline with online placeholder: Komisi I, III, IV, VI, VII
  - Offline: Komisi X, Badan Legislatif, Badan Anggaran, Badan Musyawarah, BKSAP

### CODE REVIEW

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
If the Parlimen channels do not stream 24/7, add the [Not 24/7] tag next to the names of the channels that don't.

I see you've moved some links when adding some others, make sure you've moved them well, 'cause all of the moved links still work.

**Comment by Hans5958** [comment]
Hey, I have added all of the variations TV Parlemen channels with [Not 24/7]. I know select channels are not down, but I have added it for safekeeping purposes.

Also, I added some missing metadata, if you don't mind

**Comment by Hans5958** [comment]
I just saw that you could do YouTube streams using streamlink. I might add some to it.

**Review by freearhey — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]
Perfect. Thank you !

**Pull request merged**
