### PR TITLE
Update am_ucom.m3u

### PR DESCRIPTION
**Pull request by AntiPontifex**
See title

### CODE REVIEW

**Review by Udihg — COMMENTED** [review]
Ff

**Comment by Dum4G** [comment]
I do like the tvg-id part but what's wrong with local naming?

**Comment by AntiPontifex** [comment]
Nothing is wrong with the local naming: I was attempting to establish a standard with the Roman alphabet. We do have the Alternate Name field in the database to accommodate for other alphabets. Would it be amiss to make the Roman alphabet standard in other .m3us as well? Please discuss.

**Comment by AntiPontifex** [comment]
Discussion?

**Comment by Dum4G** [comment]
I believe local namings is what language-speaking viewers expect and what's fine for now. My other thoughts go way over current implementation.

**Comment by AntiPontifex** [comment]
Unfortunately, non-Roman alphabets do not meet ISO standards: therein lies the problem.

**Comment by Dum4G** [comment]
> Unfortunately, non-Roman alphabets do not meet ISO standards: therein lies the problem.

For the time being, as we can't distinguish what viewers have in generated playlists and what maintainers see to help them maintain better, I would prefer to stick with naming that is native and comfortable to viewers

**Comment by AntiPontifex** [comment]
My vote is maintaining the standard that IPTV github is supposedly following: ISO.

**Pull request closed without merging**
