### PR TITLE
TZ: Azam links

### LINKED ISSUE #2730: Tanzanian Channel Requests
List of requests for Tanzanian channels from other issues:

- [ ] Azam Sports (#2728)
- [ ] Azam Sports 2 (#2728)

### PR DESCRIPTION
**Pull request by Dum4G**
Back from the dead. Closes https://github.com/iptv-org/iptv/issues/2730

### CODE REVIEW

**Review by jkemp814 — APPROVED** [review]
Both channel play well from here. Tags looks good.

**Review by MapGuy11 — COMMENTED** [review]
Works from the US!

**Comment by rkefi84** [comment]
Hi Team
I am looking for a link for Azam Sports 1 HD but this one seems not working anymore and cannot find the channel in the list too

**Comment by Gpark02** [comment]
Hello Team,
Is there any updated iptv .m3u playlist for Tanzania AzamTV Channels that is working? Please share, and thanks in advance.

**Pull request merged**
