### PR TITLE
Update id.m3u

### PR DESCRIPTION
**Pull request by F640**
Fixed rcti, mnctv, gtv, inews channel using their old stream

They also have stream that currently used in [RCTI+](https://rctiplus.com/) but needs referrer header to that site. I probably use their old stream and might will stop soon.
Here is the links that currently used by their site:
- RCTI: https://d35d0ifx19oopq.cloudfront.net/RCTI_2021.m3u8
- MNCTV: https://d33j155pv2xyba.cloudfront.net/MNCTV_2021.m3u8
- GTV: https://d322b885qvsbxg.cloudfront.net/GTV2021.m3u8
- INews: https://d2hfpzcndkyscp.cloudfront.net/INEWS_2021.m3u8

EDIT: Working links are in my commit, not this comment

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
```
#EXTINF:-1 tvg-id="",RCTI
#EXTVLCOPT:http-referrer=https://www.rctiplus.com/
https://d35d0ifx19oopq.cloudfront.net/RCTI_2021.m3u8
#EXTINF:-1 tvg-id="",MNCTV
#EXTVLCOPT:http-referrer=https://www.rctiplus.com/
https://d33j155pv2xyba.cloudfront.net/MNCTV_2021.m3u8
#EXTINF:-1 tvg-id="",GTV
#EXTVLCOPT:http-referrer=https://www.rctiplus.com/
https://d322b885qvsbxg.cloudfront.net/GTV2021.m3u8
#EXTINF:-1 tvg-id="",INEWS
#EXTVLCOPT:http-referrer=https://www.rctiplus.com/
https://d2hfpzcndkyscp.cloudfront.net/INEWS_2021.m3u8
```

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
10-second video for GTV
Same for iNews

**Comment by F640** [comment]
> 10-second video for GTV
> Same for iNews

This actually already happens since my first use of this playlist, but still pretty hesitate to report this. Not only for these two ,channels

**Review by BellezaEmporium — APPROVED** [review]

**Review by its0x08 — APPROVED** [review]

**Review by freearhey — APPROVED** [review]

**Comment by ba-bam** [comment]
RCTI https://d1p83s84hrxz1t.cloudfront.net/RCTI2022.m3u8

**Pull request merged**
