### PR TITLE
Channel edits: Sorting News streams

### PR DESCRIPTION
**Pull request by jkemp814**
Putting network affiliate first, moving call signs to end of line

### CODE REVIEW

**Comment by jkemp814** [comment]
I don't know how that first commit got in there. I had already sent it in another pull request. Set up a new branch to keep that from happening.

**Comment by LaneSh4d0w** [comment]
According to https://github.com/iptv-org/epg, the US EPGs are represented by their call signs. I wonder why you rollbacked the changes.

**Comment by jkemp814** [comment]
I did that because I was instructed to match the tvg-id with the name and description when filling in tags or adding logos. I asked in the discussion area how to handle this. The majority of links in the list are like that (matching the name. Let me know what I should do.

**Comment by jkemp814** [comment]
I will delete the pull request. It's going to be in conflict with the master now anyway. Something changed overnight.

**Comment by LaneSh4d0w** [comment]
MapGuy's PR was merged, and it adds links, so yeah. No need to take down this PR, I'll take care of it.

**Comment by jkemp814** [comment]
I looked at the list you linked to, and you are right. Because I added, the channel number and city name that was missing, I will revert the call sign in the xmltv_id (tvg-id)

**Comment by jkemp814** [comment]
When checking out the conflict, it is all my changes. Not MapGuy's PR, so I will delete this. It's easier to start over and leave the original call signs in tack

**Pull request closed without merging**
