### PR TITLE
JP : Catto vs. Mausso

### LINKED ISSUE #5459: Fix: xxx
Both the Japanese stream are unable to play for now I wish it is just by this day because I want to know if there's maintenance on your side ma'am/sir

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Resolves #5459

### CODE REVIEW

**Review by Dum4G — DISMISSED** [review]

**Comment by freearhey** [comment]
All links return a 403 error (VPN does not help)

image

**Comment by LaneSh4d0w** [comment]
> All links return a 403 error (VPN does not help)
> 
> image
> 

Interesting... they worked on my browser on last testing.

**Comment by LaneSh4d0w** [comment]
> > All links return a 403 error (VPN does not help)
> > image
> 
> Interesting... they worked on my browser on last testing.

EDIT : They work using the browser extension, but when you launch using VLC, it blocks automatically, maybe an user-agent issue.

**Comment by Dum4G** [comment]
Must have it's own file anyways

**Comment by JefferyHus** [comment]
@LaneSh4d0w can you share the extension please

**Review by freearhey — DISMISSED** [review]

**Comment by Dum4G** [comment]
> Must have it's own file anyways

@LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
You would prefer me making a jp_redlab.m3u file for this one ?

**Comment by Dum4G** [comment]
> You would prefer me making a jp_redlab.m3u file for this one ?

Yeah. Let's hope it will last longer for this time.

**Review by Dum4G — DISMISSED** [review]

**Comment by freearhey** [comment]
@LaneSh4d0w I can't find any information about a service called "Redlab". Could you add a link to their channel list?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w I can't find any information about a service called "Redlab". Could you add a link to their channel list?

It's a CDN only, Dum wanted me to sort them into a specific playlist. Would be the almost the same case as SSH101, except that it does not have a website.

**Comment by freearhey** [comment]
@LaneSh4d0w In this case, I cannot approve this.

**Comment by Dum4G** [comment]
Why? That's literally the only source of interesting channels from Japan. It probably comes from a provider we don't know and history tells it needs special treatment

**Comment by LaneSh4d0w** [comment]
He meant he disapproves creating another file dedicated to it. He's OK with
the PR but since Redlab isn't a service (it's a CDN), he disapproves the
fact of making another file for this.

**Comment by Dum4G** [comment]
We may not ever find what service uses this CDN but that doesn't mean it's not hosted by a service to me

**Comment by cloud90** [comment]
animax with sub is offline?!

**Comment by cloud90** [comment]
> I can confirm that it works from a web player 




can I ask you for the code to use it too on my site,so i can see animax from my tv browser! :D

**Comment by LaneSh4d0w** [comment]
To add maybe : Animax (Japanese Subtitles) http://211.23.114.106:8516/http/61.221.81.94:8088/hls/70/812/ch39.m3u8

**Comment by cloud90** [comment]
> To add maybe : Animax (Japanese Subtitles) http://211.23.114.106:8516/http/61.221.81.94:8088/hls/70/812/ch39.m3u8

sorry my error animax ok but sub english

**Review by Dum4G — DISMISSED** [review]

**Review by Dum4G — APPROVED** [review]

**Comment by Dum4G** [comment]
@freearhey

**Review by freearhey — APPROVED** [review]

**Comment by JefferyHus** [comment]
> > I can confirm that it works from a web player
> 
> @JefferyHus can I ask you for the code to use it too on my site,so i can see animax from my tv browser! :D

HLS player https://github.com/video-dev/hls.js/

**Pull request merged**
