### PR TITLE
Update sn.m3u

### PR DESCRIPTION
**Pull request by Sphinxroot**
added a couple channel

### CODE REVIEW

**Comment by Sphinxroot** [comment]
@LaneSh4d0w please if you have time   there a couple more  to be added thanks :)

#EXTINF:-1 tvg-id="7tv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/62Fn7pN.png" group-title="",7TV (480p)
http://7tv.sn/livetv/sevenlive token and need to be streamlinked
#EXTINF:-1 tvg-id="Dtv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/jYI00r3.png" group-title="",DTV (480p)
http://dtv.sn/home/dtvlive  token and need to be streamlinked
#EXTINF:-1 tvg-id="Labeltv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/xp5hAWq.png" group-title="",Label TV (480p)
http://www.labeltelevision.com/direct token and need to be streamlinked
#EXTINF:-1 tvg-id="Sen.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/mjFTE8v.png" group-title="",SenTv (480p)
https://sentv.sn/direct token and need to be streamlinked

**Comment by taodicakhia** [comment]
> @LaneSh4d0w please if you have time there a couple more to be added thanks :)
> 
> #EXTINF:-1 tvg-id="7tv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/62Fn7pN.png" group-title="",7TV (480p)
> http://7tv.sn/livetv/sevenlive token and need to be streamlinked
> #EXTINF:-1 tvg-id="Dtv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/jYI00r3.png" group-title="",DTV (480p)
> http://dtv.sn/home/dtvlive token and need to be streamlinked
> #EXTINF:-1 tvg-id="Sen.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/mjFTE8v.png" group-title="",SenTv (480p)
> https://sentv.sn/direct token and need to be streamlinked
Can't get them (token contains IP)

**Review by Dum4G — APPROVED** [review]

**Comment by Sphinxroot** [comment]
> > @LaneSh4d0w please if you have time there a couple more to be added thanks :)
> > #EXTINF:-1 tvg-id="7tv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/62Fn7pN.png" group-title="",7TV (480p)
> > http://7tv.sn/livetv/sevenlive token and need to be streamlinked
> > #EXTINF:-1 tvg-id="Dtv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/jYI00r3.png" group-title="",DTV (480p)
> > http://dtv.sn/home/dtvlive token and need to be streamlinked
> > #EXTINF:-1 tvg-id="Sen.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/mjFTE8v.png" group-title="",SenTv (480p)
> > https://sentv.sn/direct token and need to be streamlinked
> 
> Can't get them (token contains IP)

No IP Enforcement   base64 token that have : server time , Hash  and Valid Minute access token

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w please if you have time there a couple more to be added thanks :)
> 
> #EXTINF:-1 tvg-id="7tv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/62Fn7pN.png" group-title="",7TV (480p)
> http://7tv.sn/livetv/sevenlive token and need to be streamlinked
> #EXTINF:-1 tvg-id="Dtv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/jYI00r3.png" group-title="",DTV (480p)
> http://dtv.sn/home/dtvlive token and need to be streamlinked
> #EXTINF:-1 tvg-id="Labeltv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/xp5hAWq.png" group-title="",Label TV (480p)
> http://www.labeltelevision.com/direct token and need to be streamlinked
> #EXTINF:-1 tvg-id="Sen.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/mjFTE8v.png" group-title="",SenTv (480p)
> https://sentv.sn/direct token and need to be streamlinked

Gonna see.

**Comment by taodicakhia** [comment]
> > > @LaneSh4d0w please if you have time there a couple more to be added thanks :)
> > > #EXTINF:-1 tvg-id="7tv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/62Fn7pN.png" group-title="",7TV (480p)
> > > http://7tv.sn/livetv/sevenlive token and need to be streamlinked
> > > #EXTINF:-1 tvg-id="Dtv.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/jYI00r3.png" group-title="",DTV (480p)
> > > http://dtv.sn/home/dtvlive token and need to be streamlinked
> > > #EXTINF:-1 tvg-id="Sen.sn" tvg-country="SN" tvg-language="Wolof;French" tvg-logo="https://i.imgur.com/mjFTE8v.png" group-title="",SenTv (480p)
> > > https://sentv.sn/direct token and need to be streamlinked
> > 
> > 
> > Can't get them (token contains IP)
> 

Hash token contains IP but it had encrypted by md5

**Comment by LaneSh4d0w** [comment]
The first website oh my god.

It's a very awkward way of making it work, really.

**Pull request merged**
