### PR TITLE
Update uk.m3u

### LINKED ISSUE #12446: Broken: STV / STV+1
### Broken Link

https://csm-e-stv.tls1.yospace.com/csm/live/139900483.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

+1 link: https://csm-e-stv.tls1.yospace.com/csm/live/181023311.m3u8

Channel no longer loads when trying to play it, and navigating to the link shows a content not found error 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### PR DESCRIPTION
**Pull request by freearhey**
Closes #12446

### CODE REVIEW

**Review by ExperiencersInternational — COMMENTED** [review]
Should really add the links that fixes the issues, which was suggested in a reply that someone had made.

https://github.com/iptv-org/iptv/issues/12446#issuecomment-1518364100

**Comment by freearhey** [comment]
@ExperiencersInternational If you have working links to these channels feel free to add it via a [pull request](https://github.com/iptv-org/iptv/pulls).

**Comment by BellezaEmporium** [comment]
PR #12461 when merged will close this one.

**Comment by freearhey** [comment]
Closed in favor of https://github.com/iptv-org/iptv/pull/12461

**Pull request closed without merging**
