### PR TITLE
Sort Unsorted

### PR DESCRIPTION
**Pull request by themak1985**

### CODE REVIEW

**Review by Zhoro-111 — COMMENTED** [review]
Change at least tvg-logo to look different from IPTV-Free/Countries files where you stealing from.SO LAME!!!

**Comment by Raspifan2020** [comment]
It's incredible, the next idiot to stupidly copy the work of Free-IPTV. How good that more and more people notice how dubious IPTV-ORG is!

**Comment by Zhoro-111** [comment]
"SORT THE STEALING LINKS" could be more appropriate!!!

**Review by freearhey — APPROVED** [review]

**Comment by Zhoro-111** [comment]
You blocking people huuh....the truth hurts damn it !!!

**Pull request merged**
