### PR TITLE
Add CGTN France

### PR DESCRIPTION
**Pull request by cheznewa**
Add CGTN In French The URL I Found A JS config.

### CODE REVIEW

**Comment by cheznewa** [comment]
Ouuppss I Is Duplicated Sorry...

**Comment by cheznewa** [comment]
OK The Duplicated Is Down in cn.m3u

**Comment by cheznewa** [comment]
Ouuppss ... I See A Duplicated I Too Speed, I Hope A Another Add Channel?

**Comment by MoonSyria** [comment]
#EXTINF:0 tvg-name="CGTN French" tvg-language="French" tvg-country="CN" tvg-id="CGTN-fr " group-title="News" tvg-logo="https://i.imgur.com/Pb7DplW.png",CGTN (French)
https://news.cgtn.com/resource/live/french/cgtn-f.m3u8

**Pull request closed without merging**
