### PR TITLE
IN + BD + UK + AU: Plethora of channels

### LINKED ISSUE #4071: UBL HD
**Channel Name:** **UBL HD**
**Country:** **India**
**Language:** **Malayalam**
**Website:** http://www.ubltv.com
**Stream URL (optional):** http://www.ubltv.com/d63d760d-09e4-4e15-b197-8fcff3bc1667
**Notes (optional):** xxx

### LINKED ISSUE #4107: Kannur One
**Channel Name:** Kannur One
**Country:** India
**Language:** Malayalam
**Website:** http://kannurone.com/
**Stream URL (optional):** 
**Notes (optional):** Live stream is available on the website, not able to copy paste it here.

### LINKED ISSUE #4108: Kite Victers
**Channel Name:** Kite Victers
**Country:** India
**Language:** Malayalam
**Website:** https://victers.kite.kerala.gov.in/pages/index.html
**Stream URL (optional):** :https://victers.kite.kerala.gov.in/cafc29ac-a62d-4e2d-b479-cb0f6c766bad
**Notes (optional):**

### LINKED ISSUE #4109: Real News Kerala
**Channel Name:** Real News Kerala
**Country:** India
**Language:** Malayalam
**Website:** https://realnewskerala.com/
**Stream URL (optional):** https://realnewskerala.com/live/
**Notes (optional):** xxx

### LINKED ISSUE #4110: Shekinah TV
**Channel Name:** Shekinah Tv
**Country:** India
**Language:** Malayalam
**Website:** http://www.shekinahchannel.tv/
**Stream URL (optional):** https://www.youtube.com/watch?v=in4Cn5v9hYE
**Notes (optional):** xxx

### LINKED ISSUE #4111: Pulari TV
**Channel Name:** Pulari TV
**Country:** India
**Language:** Malayalam
**Website:** https://pularitv.com/index.php
**Stream URL (optional):** :https://royalstarindia.co.in/ee3a5ab0-4103-4130-9ffe-21890137d3e9
**Notes (optional):** xxx

### LINKED ISSUE #4112: Safari TV
**Channel Name:** Safari Tv
**Country:** India
**Language:** Malayalam
**Website:** https://www.safaritvchannel.com/
**Stream URL (optional):** 
**Notes (optional):** Live stream is available on the website

### LINKED ISSUE #4113: KCL TV
**Channel Name:** KCL TV
**Country:** India
**Language:** Malayalam
**Website:** http://kcltv.com/
**Stream URL (optional):** http://kcltv.livebox.co.in/livebox/player/?url=http://kcltv.livebox.co.in/kclhls/live.m3u8
**Notes (optional):** xxx

### LINKED ISSUE #4114: Kerala Vision News
**Channel Name:** Kerala Vision News
**Country:** India
**Language:** Malayalam
**Website:** https://keralavisiontv.com/
**Stream URL (optional):** https://youtu.be/OmIQGinjmnY
**Notes (optional):** xxx

### LINKED ISSUE #4117: M4TV Malayalam
**Channel Name:** M4TV
**Country:** Australia
**Language:** Malayalam
**Website:** http://m4malayalam.tv/
**Stream URL (optional):** https://www.m4.live/
**Notes (optional):** Also available on https://mhdtvworld.xyz/

### LINKED ISSUE #4118: Surya TV
**Channel Name:** Surya TV
**Country:** India
**Language:** Malayalam
**Website:** https://sunnetwork.in/Default.aspx?Lang=malayalam
**Stream URL (optional):** https://mhdtvworld.xyz/live/surya-tv-hd/
**Notes (optional):** The current one has Sun Tv hd's link.

### LINKED ISSUE #4119: Zee Keralam HD
**Channel Name:** Zee Keralam
**Country:** India
**Language:** Malayalam
**Website:** https://zeekeralam.zee5.com/
**Stream URL (optional):** https://mhdtvworld.xyz/live/zee-keralam-hd/
**Notes (optional):** xxx

### LINKED ISSUE #4130: Garshom TV
**Channel Name:** Garshom TV
**Country:** UK
**Language:** Malayalam
**Website:** http://www.garshom.tv/
**Stream URL (optional):** http://www.garshom.tv/
**Notes (optional):** Stream is available on the website

### LINKED ISSUE #4131: Anand TV
**Channel Name:** Anand TV
**Country:** US
**Language:** Malayalam
**Website:** https://anandmedia.net/
**Stream URL (optional):** https://anandmedia.net/livetv
**Notes (optional):** xxx

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Thanks to @Niyasmkkv for the propositions/issues, and @Sphinxroot for getting links. Personal additions also included.

Closes #4131
Closes #4130
Closes #4119
Closes #4118
Closes #4117
Closes #4114
Closes #4113
Closes #4112
Closes #4111
Closes #4110
Closes #4109
Closes #4108
Closes #4107
Closes #4071

### CODE REVIEW

**Comment by Niyasmkkv** [comment]
@LaneSh4d0w Please update the logos as well.
Here are the logos for few channels.

Kannur One - https://imgur.com/a/6666SeT
KCL TV - https://imgur.com/a/YSGQSYI
Anand Tv - https://imgur.com/a/qet3ute
Safari Tv - https://imgur.com/a/XY0chTz
Kite Victers - https://imgur.com/a/0gle4W9

**Comment by Niyasmkkv** [comment]
Logo Links
UBL HD - https://imgur.com/a/ihdZEpK
Surya Tv  - https://imgur.com/a/TQOTw75

**Comment by Niyasmkkv** [comment]
M4TV Malayalam - https://imgur.com/a/xg2BMrZ
Shekinah TV - https://imgur.com/a/uhdKNX3
Pulari TV - https://imgur.com/a/mHFzQv9

**Comment by Niyasmkkv** [comment]
Real News Kerala - https://imgur.com/a/Zdwlvln
Zee Keralam HD - https://imgur.com/a/3sujIBx

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
