### PR TITLE
Delete Local Now channels

### PR DESCRIPTION
**Pull request by freearhey**
As required by the copyright holder, we must remove all links to Local Now channels from the repository.

>Hi IPTV,
>
>I'm contacting you on behalf of GitHub because we've received a DMCA takedown notice regarding the following content:
>
>https://github.com/iptv-org/iptv/blob/master/channels/us_localnow.m3u
>
>We're giving you 1 business day to make the changes identified in the following notice:
>
>https://github.zendesk.com/attachments/token/qCOIlhjNbuhARY64ffpnzv9Ef/?name=2022-01-06-localnow.rtf
>
>If you need to remove specific content from your repository, simply making the repository private or deleting it via a commit won't resolve the alleged infringement. Instead, you must follow these instructions to remove the content from your repository's history, even if you don't think it's sensitive:
>
>https://docs.github.com/articles/remove-sensitive-data
>
>Once you've made changes, please reply to this message and let us know. If you don't tell us that you've made changes within the next 1 business day, we'll need to disable the entire repository according to our GitHub DMCA Takedown Policy:
>
>https://docs.github.com/articles/dmca-takedown-policy/
>
>If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described in our DMCA Takedown Policy.
>
>PLEASE NOTE: It is important that you reply to this message within 1 business day to tell us whether you've made changes. If you do not, the repository will be disabled.

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]

**Review by MapGuy11 — APPROVED** [review]

**Comment by Daniel15** [comment]
I'm tempted to send my standard DMCA counternotice to them... These URLs are all publically available, and we're simply linking to them, which does NOT constitute a breach of DMCA rules (DMCA applies to the content itself, not to *links* to the content)

**Comment by freearhey** [comment]
@Daniel15 To be honest, I don't think they understand the difference. The notice itself is not about links to their resources, but about "streaming" their channels. But if you think we should send a counternotice, let's do that.

**Comment by LaneSh4d0w** [comment]
> @Daniel15 To be honest, I don't think they understand the difference. The notice itself is not about links to their resources, but about "streaming" their channels. But if you think we should send a counternotice, let's do that.

Even the notion of "streaming" is incorrect. GitHub does not **host** the streams. The whole point of this repo is to scrape the links from all around the world to give all users the possibility to watch them, not using GitHub as a massive streaming server and get all the channels out.

**Comment by sguinetti** [comment]
I am of the same opinion, the DCMA note talks about the exclusivity of the transmissions, but "what transmissions is talked in this takedown notice". If Local Now is a paid service and not openly available, it would be understandable because of the "unfair competition" issue (I don't know if it is a crime in the US, sorry), but if Local Now is a streaming service offered from their client's official website (like Opencaster o iblus), I don't see it as illegal. 

A fictitious example, if Bloomberg has an alternative url on their website that is available on the web for anyone to reuse, it is not a crime.

**Comment by Sphinxroot** [comment]
MNXXK3DEEBRGKIDUNBSSAZ3FOJWWC3RAM52XSIDTMVSW2IDUN4QGEZJAMEQGMYLMONSSAY3MMFUW2IBOFYQHG2LOMNSSA2LUEBQWY3BAN53GK4RAORUGKIDQNRQWGZJAMFXGIIDPNZWHSIDIMVZGKIDJORZSA5DBOJTWK5DFMQ======

**Comment by LaneSh4d0w** [comment]
> 

I wouldn't think so myself.

**Comment by Daniel15** [comment]
Here's an example of a counter notice I've used before, linking to prior caselaw: https://github.com/github/dmca/blob/3ce1c9402c6b7e46dcbbea6ff866d6a44e75c72a/2020/10/2020-10-08-dfl-counternotice.md

**Pull request merged**
