### PR TITLE
Forbid paid Матч! channels

### PR DESCRIPTION
**Pull request by Dum4G**
In connection with the recent events happened to 4pda.ru

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Take off the Match TV channel we got then.

**Review by BellezaEmporium — COMMENTED** [review]
This one + the 2 others above I think.

**Comment by Dum4G** [comment]
Original Матч! is a free channel that is granted to every Russian citizen and is available on official website completely free

**Comment by LaneSh4d0w** [comment]
> 
> 
> Original Матч! is a free channel that is granted to every Russian citizen and is available on official website completely free

My bad.

**Comment by freearhey** [comment]
All of the deleted links are working and as far as I know we have not received DMCA notifications regarding these channels.

**Comment by Dum4G** [comment]
> All of the deleted links are working and as far as I know we have not received DMCA notifications regarding these channels.

But do you really want to recieve them? Most websites that have tried to stream those channels got blocked by carriers and 4pda.ru haven't recieved any DMCA either. They were just blocked without any notice because Матч! were sueing Cloudflare

**Comment by Dum4G** [comment]
@freearhey

**Pull request closed without merging**
