### PR TITLE
Update pr.m3u

### PR DESCRIPTION
**Pull request by Carlinhos027**

### CODE REVIEW

**Review by BellezaEmporium — COMMENTED** [review]
WAPA links are changing over time, the one you gave doesn't work.

**Review by BellezaEmporium — COMMENTED** [review]
WAPA links are changing over time, the one you gave doesn't work.

**Comment by BellezaEmporium** [comment]
Right now it's https://live.field59.com/t/1732093200_909ea1554be9e22571d01f2e24f8ceef7457570e_1732111320/wapa/ngrp:wapa1_all/playlist.m3u8

**Comment by BellezaEmporium** [comment]
Basically it's : https://player.field59.com/v4/channel/wapa/07679d068d54d4a6b52e3a42e27aa151d502b09a

inside "m3u8" you get the data.

**Review by BellezaEmporium — APPROVED** [review]

**Review by freearhey — APPROVED** [review]

**Pull request merged**
