### PR TITLE
Add country subdivisions codes to the country lists

### PR DESCRIPTION
**Pull request by gabrielbergeron**
I found out that some of the channels I usually watch disappeared a few weeks/months a go from the CA list. I found out that it's because the channels broadcast_area where marked to subdivisions instead of the country code.
I figured we could also load the channels from the subdivisions from the countries when creating the countries playlists.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Assigning Arhey on this PR, since it's quite a changing move, adding something more to countries.

**Comment by freearhey** [comment]
@gabrielbergeron Please add tests to make it clear what results you expect to see.

**Review by freearhey — DISMISSED** [review]

**Comment by freearhey** [comment]
@gabrielbergeron Please check the playlists again, the channels should already appear.

**Comment by gabrielbergeron** [comment]
@freearhey it works great, thank you! Also thank you for adding the tests for me, I didn't have the time since I was working.

**Pull request merged**
