### PR TITLE
Update in.m3u

### PR DESCRIPTION
**Pull request by desiflex**
desibox updates

### CODE REVIEW

**Comment by freearhey** [comment]
Link is broken.

**Comment by desiflex** [comment]
Sever restarting link will be up in 10 mins

**Comment by desiflex** [comment]
https://edge.hls.hitbox.tv/hls/desijattuk/index.m3u8?st=nuYxAHesRw4B-jHQap9LVQ;ci=mXwDmlmieHsjswZTZpoFyA



add this for second link for jatt tv please

**Comment by desiflex** [comment]
https://live600.vkuserlive.com/501706/live/556893745/82VENUSW5tRjRUIjhyPzQ5OTU5Nj8y/playlist.m3u8?extra=lO1F6M4PwjmB6ZtQkVujGrIv3dcVD_Nr42iOT1C5SmV_99WkZSXq2b0-pAyrHffJ8plgr32sW1qXfCsQLdF6T3Xa4yfOL5znC5OY6wLcR0_68Vaj3Haobg_LxqsvHblBwyuLviB2EM1tntGft-ZAdjR6

**Pull request closed without merging**
