### PR TITLE
TH: new source

### LINKED ISSUE #2752: Add: True Premier Football 2
List of requests for XXX channels from other issues:

-  True Premier Football 2

Link: 
https://www.livedoomovie.com/02_PremierHD2_720p/chunklist.m3u8

### PR DESCRIPTION
**Pull request by Dum4G**
OK, so I managed to get those links work even in VLC and took care of removing dead/DMCA ones. So now it's your turn to sort them out by origin countries, categories, add proper names and icons etc. One of them probably shows "Weak signal" and the  NBA HD has stuck on a single frame for the time of writing.

Feel free to add some more if you find from https://www.doomovie-hd.com, it's not geoblocked (at least partially?). 
**Beware there's more ads than content on the page**!
Also indexed in other Github repos for a while.

Resolves https://github.com/iptv-org/iptv/issues/2752

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Interesting... Can't look now but i'll see later.

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
(mm.m3u) If those are Thai channels, they're not supposed to be on the Myanmar channel list, they're in the Thailand one.

Nevertheless, those links work for me.

**Comment by Dum4G** [comment]
I'm done with it. If you see one frame channels - ignore them. They're literally stealing from satellite reciever and fix their sources within a few days

**Comment by Dum4G** [comment]
@sogalawson @epicmemer6 it's up to you now to keep maintaining the source and add some new ones in case your wanted channels get live on the website. You can also try https://www.we-play.tv

**Review by BellezaEmporium — COMMENTED** [review]
Last ones do not seem to work properly, is that normal ?

**Comment by Dum4G** [comment]
That periodically happens to them
image

**Comment by Dum4G** [comment]
image

**Comment by LaneSh4d0w** [comment]
I see.

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
