### PR TITLE
Add ok.ru links back

### PR DESCRIPTION
**Pull request by ghost**
I'm not sure why https://github.com/iptv-org/iptv/pull/4056/files deleted them

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]

**Comment by freearhey** [comment]
Links have been removed because they do not work at the moment and have an alternative in the same playlist. Here is a more detailed description of how it works: https://github.com/iptv-org/iptv/pull/4055

**Comment by tilfizyawn** [comment]
Thanks @freearhey that makes sense. When linkastream.co is back they can be re-added

**Comment by tilfizyawn** [comment]
@freearhey I think the delete should be done once a week with a pull request. Sometimes the links are valid but just down.

**Comment by freearhey** [comment]
@tilfizyawn I think you're right, it would be better to do just that.

**Comment by freearhey** [comment]
@tilfizyawn Done via https://github.com/iptv-org/iptv/pull/4116

**Pull request merged**
