### PR TITLE
Removing blocked channels

### PR DESCRIPTION
**Pull request by kaikyoofers**
Owned by United Media, See more: https://github.com/iptv-org/iptv/issues/6486

### CODE REVIEW

**Review by Alstruit — COMMENTED** [review]
https://github.com/iptv-org/iptv/issues/6486 indicates that N1 variants are to be removed. Please confirm if the DCMA affects all of the other channels.

**Comment by kaikyoofers** [comment]
@Alstruit Then why the United Group channels outside of N1 are blocked?

**Comment by Alstruit** [comment]
> @Alstruit Then why some United Group channels outside of N1 are blocked?

See iptv-org/database#7543

**Comment by kaikyoofers** [comment]
Reopening. https://github.com/iptv-org/database/pull/7543#issuecomment-1806942897

**Comment by kaikyoofers** [comment]
https://github.com/iptv-org/database/pull/7543#issuecomment-1806958308

**Pull request closed without merging**
