### PR TITLE
ES: Add all +tdp channels.

### PR DESCRIPTION
**Pull request by heroku-miraheze**

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
Please check the links again. None of them are working at the moment. Tested via VLC player and streamtest.in
Captura de pantalla 2021-04-26 a las 17 11 14

**Comment by heroku-miraheze** [comment]
But will work when broadcast a event. Please merge it now.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Please check the links again. None of them are working at the moment. Tested via VLC player and streamtest.in
> Captura de pantalla 2021-04-26 a las 17 11 14


Geolocked mate

**Comment by heroku-miraheze** [comment]
Geoblocked, yes, only in Spain, so, it's broadcasts only events, same as +24, so, please, commit it now.

**Comment by freearhey** [comment]
Geo-blocked links should have the `[Geo-blocked]` label in the title so we can add them to the playlist.

**Comment by heroku-miraheze** [comment]
OK.

**Comment by heroku-miraheze** [comment]
I added all [Geo-blocked] links, so, please, merge it now.

**Comment by freearhey** [comment]
Geo-blocked only links to the +tdp channel.

**Comment by heroku-miraheze** [comment]
Merge it now.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
