### PR TITLE
[in.m3u] Updated playlist for sony channels

### PR DESCRIPTION
**Pull request by javithakthar**
Updated metadata and stream links.

- SonyBBCEarthHD [Geo-blocked]
- Sony MAX 2
- Sony MAX HD
- Sony Sab HD
- Sony Sab
- Sony Six HD
- Sony Ten 1
- Sony Ten 2 HD
- Sony Ten 3 HD
- Sony YAY [Geo-blocked]

Fixes 4310 and resolves some task lists in 1934

### CODE REVIEW

**Comment by Sphinxroot** [comment]
this is extram-code  we cant add them sorry

**Comment by javithakthar** [comment]
> this is extram-code we cant add them sorry

Extram-code means?

**Comment by javithakthar** [comment]
> this is extram-code we cant add them sorry

@Sphinxroot what do you mean by extram-code?

**Comment by Sphinxroot** [comment]
as exemple  this http://wagmaott.com:8080/mag00:1A:79:6A:63:7A/fYx9iEO1Lu/7904

http://wagmaott.com:8080/  = streaming server
mag00:1A:79:6A:63:7A = user name
fYx9iEO1Lu = password
7904 =  channel

mostly its paid (hacked or leaked ) subsciption or trial  and wont last long  , so its not legitimate stream and we can`t add them to the list sorry

**Pull request closed without merging**
