### PR TITLE
Update us.m3u

### PR DESCRIPTION
**Pull request by desiflex**

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
The second link does not work.

**Comment by desiflex** [comment]
please check again

**Comment by freearhey** [comment]
@desiflex same thing

**Comment by desiflex** [comment]
1.
   https://edge.hls.hitbox.tv/hls/desijattuk/index.m3u8?st=nuYxAHesRw4B-jHQap9LVQ;ci=mXwDmlmieHsjswZTZpoFyA
   2.

**Comment by freearhey** [comment]
@desiflex The new link works, but you need to change the link in your pull request, only after that I can approve it.

**Comment by desiflex** [comment]
thanks req put in

**Pull request closed without merging**
