### PR TITLE
Add Melody FM Jordan

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by heroku-miraheze** [comment]
It works, please, @freearhey, commit it now, please.

**Comment by heroku-miraheze** [comment]
@freearhey http://www.streamtest.net/AdvancedStreamTest/httpscdn3wowzacom1zfbldulpnjrbrdzmzw90v2zwhlslivep2021-5-12-14-33-30

**Review by BellezaEmporium — COMMENTED** [review]
Does it show something else than this sometimes ? 
vlcsnap-2021-05-12-17h40m56s553

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w In the mornings it shows the presenters

Okay, I was tempted to say no to it because it would have been basically a plain radio stream that contained the logo showing, but nothing else.

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
