### PR TITLE
RU : Add channels

### PR DESCRIPTION
**Pull request by BellezaEmporium**
vlcsnap-2021-06-08-22h10m36s478

Astra stream, one of the most complete streams I've found : working teletext w/ captions including Russian subtitles available, HD quality from what I see.

### CODE REVIEW

**Comment by Dum4G** [comment]
Not bad, but most of them are Ukrainian. Especially if you see Одесса in the name

**Comment by LaneSh4d0w** [comment]
> 
> 
> Not bad, but most of them are Ukrainian. Especially if you see Одесса in the name

Moving them

**Comment by Dum4G** [comment]
You can safely move every channel without tvg-id to UA, GTV shows an Oddesite channel and Hollywood HD is such unreliable it kicks me out amost immediately

**Comment by LaneSh4d0w** [comment]
That's how Astra named their channels, but I do agree that some names do not correspond. If you had seen the playlist I had, some were tricky.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
