### PR TITLE
JP : Add lots of channels

### LINKED ISSUE #7418: NHK World Premium m3u8
### Channel Name

NHK World Premium

### Channel ID

NHKWorldPremium.jp

### Website

https://nhkworldpremium.com/

### Stream URL

https://nhkwlive-pre-in.webcdn.stream.ne.jp/hls/live/nhkwlive-pre/index_1M.m3u8

### Notes

Overseas Japanese TV
Add it on jp.m3u plz! 

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### PR DESCRIPTION
**Pull request by BellezaEmporium**
- NHK's AI-Translated channels languages
Slight latency on real-time AI-translations (from 1 to 5 seconds) and what's being said (in English), but translation is quite accurate (compared my English understanding with the French subtitles)
- NHK World Premium
Should close https://github.com/iptv-org/iptv/issues/7418

### CODE REVIEW

**Review by freearhey — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
Is BS NHK Premium OK ?

**Review by freearhey — APPROVED** [review]

**Review by Central302 — APPROVED** [review]
I Checked All JPN TV Stream. And Official Streaming of NHK World Premium.
For Moderator : Cinefil Wowow is Now Renamed to WOWOW Plus

**Comment by LaneSh4d0w** [comment]
> I Checked All JPN TV Stream. And Official Streaming of NHK World Premium. For Moderator : Cinefil Wowow is Now Renamed to WOWOW Plus

Feel free to make a PR to reflect that change. You're one of us now :)

**Comment by luongz** [comment]
Bonus

- Kansai channel btw

```
#EXTINF:-1 tvg-id="NHKGeneralTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/6/6f/NHK%E7%B7%8F%E5%90%88%E3%83%AD%E3%82%B42020-.png" group-title="KANSAI",NHK G Osaka (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_nhk_g_720/playlist.m3u8
#EXTINF:-1 tvg-id="NHKGeneralTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/6/6f/NHK%E7%B7%8F%E5%90%88%E3%83%AD%E3%82%B42020-.png" group-title="KANSAI",NHK G Osaka (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_nhk_g_540/playlist.m3u8
#EXTINF:-1 tvg-id="NHKEducationalTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/a/aa/NHKE%E3%83%86%E3%83%AC%E3%83%AD%E3%82%B42020-.png" group-title="KANSAI",NHK E Osaka (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_nhk_edu_720/playlist.m3u8
#EXTINF:-1 tvg-id="NHKEducationalTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/a/aa/NHKE%E3%83%86%E3%83%AC%E3%83%AD%E3%82%B42020-.png" group-title="KANSAI",NHK E Osaka (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_nhk_edu_540/playlist.m3u8
#EXTINF:-1 tvg-id="JORXDTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Mainichi_Broadcasting_System_logo.svg/2560px-Mainichi_Broadcasting_System_logo.svg.png" group-title="KANSAI",MBS (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_mbs_720/playlist.m3u8
#EXTINF:-1 tvg-id="JORXDTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Mainichi_Broadcasting_System_logo.svg/2560px-Mainichi_Broadcasting_System_logo.svg.png" group-title="KANSAI",MBS (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_mbs_540/playlist.m3u8
#EXTINF:-1 tvg-id="TVAsahi.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Asahi_Broadcasting_Corporation_Logo.svg/2560px-Asahi_Broadcasting_Corporation_Logo.svg.png" group-title="KANSAI",ABC (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_abc_asahi_720/playlist.m3u8
#EXTINF:-1 tvg-id="TVAsahi.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Asahi_Broadcasting_Corporation_Logo.svg/2560px-Asahi_Broadcasting_Corporation_Logo.svg.png" group-title="KANSAI",ABC (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_abc_asahi_540/playlist.m3u8
#EXTINF:-1 tvg-id="NipponTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Yomiuri_Telecasting_Corporation_Logo.svg/2560px-Yomiuri_Telecasting_Corporation_Logo.svg.png" group-title="KANSAI",YTV (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_yomiuri_720/playlist.m3u8
#EXTINF:-1 tvg-id="NipponTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Yomiuri_Telecasting_Corporation_Logo.svg/2560px-Yomiuri_Telecasting_Corporation_Logo.svg.png" group-title="KANSAI",YTV (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_yomiuri_540/playlist.m3u8
#EXTINF:-1 tvg-id="JOCXDTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/c/cf/Kantele_logo_2015.png" group-title="KANSAI",Kansai TV (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_tv_720/playlist.m3u8
#EXTINF:-1 tvg-id="JOCXDTV.jp" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/c/cf/Kantele_logo_2015.png" group-title="KANSAI",Kansai TV (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_tv_540/playlist.m3u8
#EXTINF:-1 tvg-id="JOTXDTV.jp" tvg-logo="https://asianwiki.com/images/e/e1/TV_Osaka-p1.png" group-title="KANSAI",TV Osaka (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_tv_osaka_720/playlist.m3u8
#EXTINF:-1 tvg-id="JOTXDTV.jp" tvg-logo="https://asianwiki.com/images/e/e1/TV_Osaka-p1.png" group-title="KANSAI",TV Osaka (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_tv_osaka_540/playlist.m3u8
#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/commons/b/b9/SUN-TV_wordmark_2019.png" group-title="KANSAI",SUN TV (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_sun_tv_720/playlist.m3u8
#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/commons/b/b9/SUN-TV_wordmark_2019.png" group-title="KANSAI",SUN TV (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/kansi_sun_tv_540/playlist.m3u8
```

**Comment by luongz** [comment]
I see only 1x WOWOW Channel

```
#EXTINF:-1 tvg-id="WowowPrime.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow_prime.png" group-title="BS",WOWOWプライム (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/wowprime_720/playlist.m3u8
#EXTINF:-1 tvg-id="WowowPrime.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow_prime.png" group-title="BS",WOWOWプライム (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/wowprime_540/playlist.m3u8
#EXTINF:-1 tvg-id="WowowLive.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow_live.png" group-title="BS",WOWOWライブ (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/wowlive_720/playlist.m3u8
#EXTINF:-1 tvg-id="WowowLive.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow_live.png" group-title="BS",WOWOWライブ (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/wowlive_540/playlist.m3u8
#EXTINF:-1 tvg-id="WowowCinema.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow_cinema.png" group-title="BS",WOWOWシネマ (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/wowcinema_720/playlist.m3u8
#EXTINF:-1 tvg-id="WowowCinema.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow_cinema.png" group-title="BS",WOWOWシネマ (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/wowcinema_540/playlist.m3u8
#EXTINF:-1 tvg-id="WowowPlus.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow-plus-jp.png" group-title="BS",WOWOWプラス (720p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/cinefil_wowow_720/playlist.m3u8
#EXTINF:-1 tvg-id="WowowPlus.jp" tvg-logo="https://www.lyngsat-logo.com/logo/tv/ww/wowow-plus-jp.png" group-title="BS",WOWOWプラス (540p JPNetTV US)
https://cdn.us195.jpnettv.live:1935/jptv/cinefil_wowow_540/playlist.m3u8
```

**Pull request merged**
