### PR TITLE
Move channels to specific playlist - Part 1

### PR DESCRIPTION
**Pull request by BellezaEmporium**
As we're used to do now.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
For MX : SET Television has 2 antennas: one originally in Puebla being XHPUE-TDT, confirmed both by Wikipedia and [this document](https://portalanterior.ine.mx/archivos1/DEPPP/MapasCobertura/2016/TDT/Puebla/XHPUE-TDT.pdf) from the Instituto Nacional de México

**Comment by LaneSh4d0w** [comment]
First batch ready for review, will do another batch when i'll have more time, unless someone wants to look after it and do more.

**Review by UltraHDR — DISMISSED** [review]

**Review by Alstruit — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
@UltraHDR if you can take a look over the merge issues.

**Comment by Alstruit** [comment]
I apologize, the ours merge strategty did not quite work as I expected. I think this commit should merge cleanly.

**Review by Alstruit — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
> I apologize, the ours merge strategy did not quite work as I expected. I think this commit should merge cleanly.

At first look it seems alright.

**Review by UltraHDR — APPROVED** [review]

**Pull request merged**
