### PR TITLE
Update us.m3u

### PR DESCRIPTION
**Pull request by mmkogut**
Fixed/replaced broken NBC 4 Los Angeles Link

### CODE REVIEW

**Comment by MapGuy11** [comment]
I added @LaneSh4d0w to see what he thinks I approve it though.

**Review by MapGuy11 — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Comment by mmkogut** [comment]
Thanks everyone

**Comment by LaneSh4d0w** [comment]
@MapGuy11 You're the one monitoring this stream, you don't need my approval for that, as long as the information is accurate :)

**Comment by MapGuy11** [comment]
> @MapGuy11 You're the one monitoring this stream, you don't need my approval for that, as long as the information is accurate :)

Yeah it is. :)

**Comment by jkemp814** [comment]
A new channel should have been added, and the original newscast stream fixed, not replaced. 

There are viewers who prefer the newscast over a live full schedule channel. News is what's sought after. Not only did we replace an existing channel whether broken or not, in its place, added a channel with a whole different category.

**Comment by LaneSh4d0w** [comment]
> 
> 
> A new channel should have been added, and the original newscast stream fixed, not replaced.
> 
> There are viewers who prefer the newscast over a live full schedule channel. News is what's sought after. Not only did we replace an existing channel whether broken or not, in its place, added a channel with a whole different category.

Pretty sure we should actually indicate whether the channel the end user is about to see is the Newscast or the OTA channel.
We did no indication whatsoever.

**Comment by jkemp814** [comment]
I have wondered about that as I add all these newscast channels. If you look at the ABC Los Angeles channels, one uses DT1 full schedule and the other -TV is the newscast. The end user/viewer may not notice that. 

It's best to keep both instead of replacing URL's for what viewers perceive as a better channel because it's live. We lose the newscast doing it that way. Why not have both?  With name real estate an issue sometimes, adding Newscast makes the description longer. Adding (NC) may not be understood also.

**Comment by LaneSh4d0w** [comment]
> 
> 
> I have wondered about that as I add all these newscast channels. If you look at the ABC Los Angeles channels, one uses DT1 full schedule and the other -TV is the newscast. The end user/viewer may not notice that.
> 
> It's best to keep both instead of replacing URL's for what viewers perceive as a better channel because it's live. We lose the newscast doing it that way. Why not have both? With name real estate an issue sometimes, adding Newscast makes the description longer. Adding (NC) may not be understood also.

[OTA] [News] sounds OK to me.

**Comment by mmkogut** [comment]
A user's perspective, I find it currently easy to tell between the newscast channels and OTA when they have an 'N' placed after the station or network.
i.e. "CBSN Boston" "ABC-N Los Angeles" compared to "CBS 8 San Diego" or "NBC 4 Los Angeles" which are the OTA's.

Hope that might help.

**Pull request merged**
