### PR TITLE
Update it.m3u

### PR DESCRIPTION
**Pull request by infid0**
CHANGELOG: 
- Renamed "Canale 21 Lazio" with the correct name "Canale 21" (also known as: "Canale 21 Campania") and fixed the id epg name.
- Added "Canale 21 Extra" (the real "Canale 21 Lazio") with id epg.
- Added "Gold TV", "Gold TV Italy" it was the second channel of this network.
- Added "GO-TV CHANNEL" with id epg.

Thank you so much. :3

### CODE REVIEW

**Review by BellezaEmporium — COMMENTED** [review]
Can't test both Canale 21 links as they appear offline in the moment. The last 2 others are working. Though I think GO-TV is streaming ads only ?

**Comment by infid0** [comment]
@LaneSh4d0w "Canale 21" works, i don't know why but now is offline, yesterday it worked. "Canale 21 Extra" has problems, sometime works, sometime is offline for days. "GO-TV" is a local tv, is a mix of ads, talk show, reality show, etcetera. Example now is onair a strange talk show... :/

**Review by BellezaEmporium — APPROVED** [review]
Will approve, as the links indeed do appear on the original website. Maybe a maintenance or something else.

**Comment by infid0** [comment]
Thank you so much! But if you want to change something that's fine for me. It was only for to correct "Canale 21" with the right name and for to add "Gold TV" the main channel. Because "Gold TV Italia" is a secondary channel. Thank you again! :D

**Comment by LaneSh4d0w** [comment]
I don't see any changes I could make honestly, LGTM.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
