### PR TITLE
UK: add Nick Jr. Too

### LINKED ISSUE #2816: Add: Nick Jr Too
**Channel Name:** Nick Jr Too
**Country:** Europe
**Language:** British English
**Notes (optional):** when will my requested channels be added?

### PR DESCRIPTION
**Pull request by Dum4G**
resolves #2816

### CODE REVIEW

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Nickelodeon is an American company. If we follow that, you should put the Nickelodeon UK channel to the US section.

**Review by freearhey — CHANGES_REQUESTED** [review]
https://github.com/iptv-org/iptv/pull/2821#pullrequestreview-663442312

**Comment by Dum4G** [comment]
https://en.wikipedia.org/wiki/Nick_Jr._(British_and_Irish_TV_channel)

According to wiki this channel has never been broadcasted in US and is owned and operated by a joint venture between ViacomCBS Networks UK & Australia and Sky Group. Do i have to move it into us playlist?

**Comment by LaneSh4d0w** [comment]
> 
> 
> https://en.wikipedia.org/wiki/Nick_Jr._(British_and_Irish_TV_channel)
> 
> According to wiki this channel has never been broadcasted in US and is owned and operated by a joint venture between ViacomCBS Networks UK & Australia and Sky Group. Do i have to move it into us playlist?

Well it's tricky. The ViacomCBS group is American, the UK/AUS is a subsidiary. Sky is UK-based.

However, the "Nickelodeon" stamp is American for sure.

**Comment by Dum4G** [comment]
Am I leaving tvg-id as UK one or US one?

**Comment by LaneSh4d0w** [comment]
> 
> 
> Am I leaving tvg-id as UK one or US one?

Change the TVG-ID to US.

**Comment by Dum4G** [comment]
Ok let's go

**Review by BellezaEmporium — APPROVED** [review]

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
@Dum4G Thank you!

**Pull request merged**
