### PR TITLE
Add Aghani Aghani

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Dum4G — APPROVED** [review]

**Comment by Dum4G** [comment]
Awful quality but I know that's an official link

**Comment by LaneSh4d0w** [comment]
Did you mean "Aghani HD" ?

**Comment by Dum4G** [comment]
> Did you mean "Aghani HD" ?

https://aghaniaghani.com/

**Comment by LaneSh4d0w** [comment]
Ah okay, weird website name, but the logo clearly shows "Aghani HD", that's why I ask.

**Comment by tilfizyawn** [comment]
It's just "Aghani Aghani" 

https://aghaniaghani.com/images/misc/frequencies.jpg

**Pull request merged**
