### PR TITLE
Replace old ythls URL for YouTube live streams

### LINKED ISSUE #16156: YouTube streams broken
### Describe your issue

Streams to YouTube channels with "https://ythls.armelin.one" are not working. According to the [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md), we could use a service like [abskmj/youtube-hls-m3u8](https://github.com/abskmj/youtube-hls-m3u8) to stream YouTube channels.

The URL in that repo is https://ythls-v2.onrender.com/ instead. Maybe all streams should be replaced by this URL? 

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by rodrigost23**
Fixes #16156

### CODE REVIEW

**Comment by Dum4G** [comment]
It doesn't fix the fact that many channels are Not 24/7 or no longer stream. Rather than replacing a source you can make an alternative

**Comment by rodrigost23** [comment]
Of course it doesn't. It's just meant to fix the ones that are still active but the old ythls URL is not working.

**Comment by Dum4G** [comment]
> Of course it doesn't. It's just meant to fix the ones that are still active but the old ythls URL is not working.

Can you highlight a few that will not work under current implementation but surely will be stable under alternative one?

**Comment by rodrigost23** [comment]
A few ones I found that are 24/7 and didn´t work on ythls.armelin.one but did work on ythls-v2.onrender.com:

https://ythls-v2.onrender.com/channel/UCaVp5oNNuIZVU7qqhSX0LGQ.m3u8
https://ythls.armelin.one/channel/UCaVp5oNNuIZVU7qqhSX0LGQ.m3u8

https://ythls-v2.onrender.com/channel/UCP0uG-mcMImgKnJz-VjJZmQ.m3u8
https://ythls.armelin.one/channel/UCP0uG-mcMImgKnJz-VjJZmQ.m3u8

https://ythls-v2.onrender.com/channel/UCyscVWiJELkATSuU-RF2NLg.m3u8
https://ythls.armelin.one/channel/UCP0uG-mcMImgKnJz-VjJZmQ.m3u8

 Is it possible to be some DNS or ISP restriction on my end?

**Comment by BellezaEmporium** [comment]
It's usually because certain streams are also geo-restricted. Might work from the Render server, but not on the Armelin one.

Anyway, no need to change those links as they appear to work, and confirmed on targeted issue.

**Pull request closed without merging**
