### PR TITLE
US: some general maintenance

### LINKED ISSUE #3217: Add: CNN (US)
**Channel Name:** CNN
**Country:** US
**Language:** English
**External Link (optional):** http://hlss.goodgame.ru/hls/185257.m3u8
**Notes (optional):** Link grabbed from a streaming site called Freeintertv

### LINKED ISSUE #3280: Fix: ESPN
**_Channel Name:_** ESPN
**_Broken Link (from playlist):_** http://164.68.124.111/fs2.m3u8
**_Possible Replacement (optional):_** 
**_Notes (optional):_** Stream just sits trying to connect, the other two streams work fine.

### LINKED ISSUE #3347: Add: Freeform
**Channel Name:** Freeform
**Country:** USA
**Language:** English
**External Link (optional):** https://bozztv.com/teleyupp/IxagghMvR8/playlist.m3u8
**Notes (optional):** Stream works in VLC and FFplay

### LINKED ISSUE #3348: Add: Revolt
**Channel Name:** Revolt
**Country:** USA
**Language:** English
**External Link (optional):** https://bozztv.com/teleyupp/teleup-revolt/playlist.m3u8
**Notes (optional):** Stream works both in VLC and FFplay

### PR DESCRIPTION
**Pull request by Dum4G**
Removed some CNN duplicates, dead chinese link and an MPD
Added CNN from Warner source. Closes https://github.com/iptv-org/iptv/issues/3217
Added some more ESPN sources (wmsAuth link dates from April, should last for some time). Closes https://github.com/iptv-org/iptv/issues/3280
Added alternate TVBiz source
Added Loop channels from Roku
Added Freeform Closes https://github.com/iptv-org/iptv/issues/3347
Added Revolt Closes https://github.com/iptv-org/iptv/issues/3348
Special thanks to @fotvnetwork and @trancer1994

### CODE REVIEW

**Comment by jkemp814** [comment]
Should we title those Warner links as 'CNN go' to distinguish them from regular CNN? Works great. High resolution and clear audio.

**Comment by Dum4G** [comment]
CNNgo is just their own platform broadcasting regular US CNN that was requested

**Comment by jkemp814** [comment]
I know, but it is different stream. Post banner for commercial breaks.

**Comment by jkemp814** [comment]
Streams: Report 'No such file or directory in FFplay

#EXTINF:-1 tvg-id="CNN.us" tvg-name="CNN" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/Ivyl5SQ.gif" group-title="News",CNN
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_4_1064000.m3u8
#EXTINF:-1 tvg-id="CNN.us" tvg-name="CNN" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/Ivyl5SQ.gif" group-title="News",CNN
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_3_1464000.m3u8

**Comment by Dum4G** [comment]
image
It's glitching out sometimes if you do too many requests but the link actually works

**Comment by jkemp814** [comment]
Let me try that using VLC

**Comment by jkemp814** [comment]
You are correct, they work in VLC, but not FFplay.

**Comment by jkemp814** [comment]
Disregard, I found out what was wrong with FFplay. Extra characters. Sorry bout that.

**Comment by Dum4G** [comment]
Let's add everything we can and figure Fox Business source later

**Comment by jkemp814** [comment]
Too many 'eee' in Freeform

**Comment by Dum4G** [comment]
> Too many 'eee' in Freeform. It's correct in the file though

I see only two. If I missed something you can review a single line, so I could see it

**Comment by jkemp814** [comment]
i think it's just the description on this page 432c30d just under loop

**Comment by Dum4G** [comment]
image

**Comment by jkemp814** [comment]
I don't think it matters much. Maybe the title of the commit

**Comment by Dum4G** [comment]
> I don't think it matters much. Maybe the title of the commit

Oh, now I see. Indeed, it's just for commit history and won't reflect the playlist anyhow

**Comment by jkemp814** [comment]
It's right above this line on this page: Dum4G requested review from LaneSh4d0w and MapGuy11 1 hour ago

**Comment by jkemp814** [comment]
Okay, I'm still learning. LOL

**Review by MapGuy11 — APPROVED** [review]

**Pull request merged**
