### PR TITLE
[ro] Add TVR and Pro suite of channels

### PR DESCRIPTION
**Pull request by alin-antohe**
- Add unofficial channel streams for TVR 1, TVR 1 HD, TVR 2, TVR 3, TVR International, TVR Cluj, TVR Craiova, TVR Iasi, TVR Targu-Mures and TVR Timisoara.
- Add official channel streams for Pro TV, Pro 2, Pro X, Pro Gold, Pro Cinema and Pro TV News.
- Removed TVR 1, TVR 1 HD, TVR 2 and TVR 3 channel streams from the unsorted playlist.

### CODE REVIEW

**Comment by freearhey** [comment]
Thank you for your help!

And by the way, there is no need to change the channel order inside the playlist, as all playlists are automatically sorted by channel name after each update.

**Comment by SileC** [comment]
Excelent, mii de multumiri.

**Comment by iulian-antohe** [comment]
> Thank you for your help!

You're welcome!

> And by the way, there is no need to change the channel order inside the playlist, as all playlists are automatically sorted by channel name after each update.

@freearhey  I wasn't aware of that. May I ask about the reason behind the automated sorting in alphabetical order (I presume)?

**Comment by freearhey** [comment]
@iulian-antohe It's the easiest way to keep all the playlists in order.

**Comment by iulian-antohe** [comment]
It's a little bit unusual because public service and main commercial broadcasters are listed at the top. By ordering all playlists in alphabetical order, sometimes obscure or regional channels are listed at the top and the important ones are listed at the bottom. This makes it cumbersome when using smart TV players such as [HomeIPTV](https://www.homeiptv.com/) as one might have to scroll through several pages to access the popular channels in countries such as the USA, China or Russia.
I would suggest removing the automatic ordering to allow the custom order based on government directives, popularity, broadcaster/channel market share etc.

**Comment by freearhey** [comment]
Unfortunately, we cannot track changes in government directives for 8000 channels to keep playlists up to date. The same applies to using popularity and broadcaster/channel market share etc.

**Comment by iulian-antohe** [comment]
Fair enough.

**Pull request merged**
