### PR TITLE
Update ro.m3u

### LINKED ISSUE #11391: Add: RadioZu.ro
### Channel ID

RadioZu.ro

### Stream URL

https://rundle.deta.dev/hls/LIVE$RadioZu/6.m3u8/Level(19012010)?start=LIVE&end=END

### Notes

It's not ZuTV.ro

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #11402: Add: Observator News (Antena News)
### Channel ID

ObservatorNews.ro

### Stream URL

https://live1ag.antenaplay.ro/live_ObservatorNews/live_ObservatorNews_3000k.m3u8

### Notes

Antena 1 News (Observator News)

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #11404: Add: ProArena.ro
### Channel ID

ProArena.ro

### Stream URL

https://rundle.deta.dev/hls/LIVE$PROArena/6.m3u8/Level(19012010)?start=LIVE&end=END

### Notes

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #11422: Replace: ProTv.ro
### Broken Link

https://hlsrundle-stream-iptv.gq/api/hls/protv.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://rundle.deta.dev/hls/LIVE$PROTV.ro/6.m3u8/Level(19012010)?start=LIVE&end=END

### Notes

24/7

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #11424: Add: CineMaraton.ro
### Channel ID

CineMaraton.ro

### Stream URL

https://rundle.deta.dev/hls/LIVE$CineMaraton/6.m3u8/Level(19012010)?start=LIVE&end=END

### Notes

Restreaming from primaplay.ro/live/cinemaraton

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #11458: Replace: UTV.ro
### Broken Link

https://hlsrundle-stream-iptv.gq/api/hls/utv.m3u8

### What happened to the stream?

Not loading

### Possible Replacement

https://rundle.deta.dev/hls/LIVE$UTV.ro/6.m3u8/Level(19012010)?start=LIVE&end=END

### Notes

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Adaptive playlist for Digi 24 + more updates courtesy of @ovidiuux

Close #11458
Close #11422 
Close #11424
Close #11404 
Close #11402 
Close #11391

### CODE REVIEW

**Comment by trincowski** [comment]
> Adaptive playlist for Digi 24 + more updates courtesy of @ovidiuux
> 
> Close #11458 Close #11422 Close #11424 Close #11404 Close #11402 Close #11391

Some channels from the https://rundle.deta.dev links are showing a 403 error. Could it be they are Not 24/7?

**Comment by LaneSh4d0w** [comment]
> > Adaptive playlist for Digi 24 + more updates courtesy of @ovidiuux
> > 
> > Close #11458 Close #11422 Close #11424 Close #11404 Close #11402 Close #11391
> 
> Some channels from the https://rundle.deta.dev links are showing a 403 error. Could it be they are Not 24/7?

Nope, he filters the user-agents. You need to load it via a video player.

**Comment by trincowski** [comment]
> > > Adaptive playlist for Digi 24 + more updates courtesy of @ovidiuux
> > > Close #11458 Close #11422 Close #11424 Close #11404 Close #11402 Close #11391
> > 
> > 
> > Some channels from the https://rundle.deta.dev links are showing a 403 error. Could it be they are Not 24/7?
> 
> Nope, he filters the user-agents. You need to load it via a video player.

Hmmm... But why do some work while others don't?

**Comment by LaneSh4d0w** [comment]
> > > > Adaptive playlist for Digi 24 + more updates courtesy of @ovidiuux
> > > > Close #11458 Close #11422 Close #11424 Close #11404 Close #11402 Close #11391
> > > 
> > > 
> > > Some channels from the https://rundle.deta.dev links are showing a 403 error. Could it be they are Not 24/7?
> > 
> > 
> > Nope, he filters the user-agents. You need to load it via a video player.
> 
> Hmmm... But why do some work while others don't?
> 
> Ah, this is funny, I'm using Brave Browser on Android to open the links. This one will work:
> 
>     * https://rundle.deta.dev/hls/LIVE$Antena1/6.m3u8/Level(19012010)?end=END&start=LIVE
> 
> 
> But this won't:
> 
>     * https://rundle.deta.dev/hls/LIVE$Antena1/6.m3u8/Level(19012010)?start=LIVE&end=END
> 
> 
> The only difference is the order of the arguments. 😆

@ovidiuux ?

**Comment by ovidiuux** [comment]
> > > > > Adaptive playlist for Digi 24 + more updates courtesy of @ovidiuux
> > > > > Close #11458 Close #11422 Close #11424 Close #11404 Close #11402 Close #11391
> > > > 
> > > > 
> > > > Some channels from the https://rundle.deta.dev links are showing a 403 error. Could it be they are Not 24/7?
> > > 
> > > 
> > > Nope, he filters the user-agents. You need to load it via a video player.
> > 
> > 
> > Hmmm... But why do some work while others don't?
> > Ah, this is funny, I'm using Brave Browser on Android to open the links. This one will work:
> > ```
> > * https://rundle.deta.dev/hls/LIVE$Antena1/6.m3u8/Level(19012010)?end=END&start=LIVE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But this won't:
> > ```
> > * https://rundle.deta.dev/hls/LIVE$Antena1/6.m3u8/Level(19012010)?start=LIVE&end=END
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The only difference is the order of the arguments. 😆
> 
> @ovidiuux ?

No, the end parameters have nothing to do with it 
It also works if they are just like this "&start&end" 
The referrer "iptv" is blocked, when you open directly from here it does not work, no matter how much you refresh.
Possibly he just changed the parameters and accessed.
That is, just copy the link and paste.

The referrer here is https://github.com/iptv-org/iptv, it contains IPTV and that's why it doesn't work. It only works from new tab.

**Review by UltraHDR — APPROVED** [review]

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
