### PR TITLE
MX : Add alternative Azteca Uno stream found

### PR DESCRIPTION
**Pull request by BellezaEmporium**

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Review by jkemp814 — COMMENTED** [review]
FFPLAY: 190.122.96.187:8888/http/002: Protocol not found
VLC: VLC is unable to open the MRL '190.122.96.187:8888/http/002'

**Comment by LaneSh4d0w** [comment]
http://190.122.96.187:8888/http/002

vlcsnap-2021-10-02-22h34m28s130

**Comment by jkemp814** [comment]
What player are you using?

**Comment by LaneSh4d0w** [comment]
VLC. This stream is giving a .ts file.

**Review by jkemp814 — APPROVED** [review]

**Pull request merged**
