### PR TITLE
Fixed QA dead streams

### PR DESCRIPTION
**Pull request by themak1985**
Removed - both no longer stream channels - beinsports News is just a repeating clip. AJ arabic has moved to youtube livestreams - https://www.youtube.com/watch?v=YwxAMjL_JFs
#EXTINF:-1 tvg-id="beIN Sports News ARB" tvg-name="beIN Sports News ARB" tvg-language="Arabic" tvg-logo="https://www.satlogo.com/hires/bb/be_in_mena_sports_news.png" group-title="Sport",beIN Sports News
http://95.170.215.120/hls/m3u8/Bein-Sport-News-ALI-MCR-NGC.m3u8
#EXTINF:-1 tvg-id="Al Jazeera Arabic ARB" tvg-name="Al Jazeera Arabic ARB" tvg-language="Arabic" tvg-logo="https://i.imgur.com/sJM9Tic.jpg" group-title="News",Al Jazeera
http://aljazeera-ara-hd-live.hls.adaptive.level3.net/aljazeera/arabic2/index.m3u8
#EXTINF:-1 tvg-id="Al Jazeera Arabic ARB" tvg-name="Al Jazeera Arabic ARB" tvg-language="Arabic" tvg-logo="https://i.imgur.com/sJM9Tic.jpg" group-title="News",Al Jazeera
http://aljazeera-ara-hd-live.hls.adaptive.level3.net/aljazeera/arabic2/index2073.m3u8
#EXTINF:-1 tvg-id="Al Jazeera Arabic ARB" tvg-name="Al Jazeera Arabic ARB" tvg-language="Arabic" tvg-logo="https://i.imgur.com/sJM9Tic.jpg" group-title="News",Al Jazeera
http://aljazeera-ara-hd-live.hls.adaptive.level3.net/aljazeera/arabic2/index255.m3u8
#EXTINF:-1 tvg-id="Al Jazeera Arabic ARB" tvg-name="Al Jazeera Arabic ARB" tvg-language="Arabic" tvg-logo="https://i.imgur.com/sJM9Tic.jpg" group-title="News",Al Jazeera
https://aja-hd-web-hls-live.secure.footprint.net/egress/chandler/aljazeera2/arabichd/index.m3u8

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
Honestly, I didn't understand why you decided to remove the working Al Jazeera broadcasts?

**Comment by themak1985** [comment]
They must be geo blocked. In USA its a black screen that says to subscribe to SlingTV to watch the channel. It didn't always, it's something recent.

**Comment by freearhey** [comment]
Very strange! I just checked these links again with https://streamtest.in/ using an American server and everything still works fine.
Captura de pantalla 2019-12-20 a las 18 10 58

**Comment by themak1985** [comment]
This is what I get:
Annotation 2019-12-20 193212

**Review by freearhey — APPROVED** [review]
It's an odd situation. But you were right, we'll have to delete the links.

**Pull request merged**
