### PR TITLE
Proposal : Update Channel Request Template

### PR DESCRIPTION
**Pull request by BellezaEmporium**
This change is aimed to make issues easier to handle.
Since we now got several querying servers available to parse YouTube, Dailymotion, Twitch, OK.ru etc... links, it is better to actually propose them on issue so that every poster can test them before submitting the issue.

### CODE REVIEW

**Comment by freearhey** [comment]
Didn't we move all the suggestions to Discussions?

**Comment by LaneSh4d0w** [comment]
> 
> 
> Didn't we move all the suggestions to Discussions?

Since I thought it was useful for everyone, I didn't think about making a discussion about it.

**Comment by freearhey** [comment]
Can we just add these links to [iptv-org/awesome-iptv](https://github.com/iptv-org/awesome-iptv)? I just personally do not see the point of adding these links to the channel request form. If a person has any link to the channel, he should do PR, not create a new issue. But once again, you can get opinions from other members of the community through Discussions.

**Comment by LaneSh4d0w** [comment]
> 
> 
> Can we just add these links to [iptv-org/awesome-iptv](https://github.com/iptv-org/awesome-iptv)? I just personally do not see the point of adding these links to the channel request form. If a person has any link to the channel, he should do PR, not create a new issue. But once again, you can get opinions from other members of the community through Discussions.

We can indeed. Doing a PR for that.

**Pull request closed without merging**
