### PR TITLE
IN : Add some channels

### PR DESCRIPTION
**Pull request by BellezaEmporium**

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
image
Hesitated about calling it Malayalam Naaptol, due to the little something over the logo

@Niyasmkkv thoughts ?

**Comment by Niyasmkkv** [comment]
It's Malayalam only. But it's crapy shopping channel.

**Comment by LaneSh4d0w** [comment]
> 
> 
> It's Malayalam only. But it's crapy shopping channel.

Okay, preferred asking to you directly since you know lots of things around.

Haha, well, at least we got a trace of this channel here x)

**Comment by Niyasmkkv** [comment]
> > It's Malayalam only. But it's crapy shopping channel.
> 
> Okay, preferred asking to you directly since you know lots of things around.
> 
> Haha, well, at least we got a trace of this channel here x)

There are many Naaptol channels in almost all Indian languages.

**Comment by LaneSh4d0w** [comment]
> 
> 
> > > It's Malayalam only. But it's crapy shopping channel.
> > 
> > 
> > Okay, preferred asking to you directly since you know lots of things around.
> > Haha, well, at least we got a trace of this channel here x)
> 
> There are many Naaptol channels in almost all Indian languages.

For now i've only stumbled upon the Malayalam one.

**Comment by LaneSh4d0w** [comment]
image

Added Fakt Marathi from MXPlayer source. Interesting how we still can dig stuff up that website. Interestingly not geo-blocked.

**Comment by Niyasmkkv** [comment]
> image
> 
> Added Fakt Marathi from MXPlayer source. Interesting how we still can dig stuff up that website. Interestingly not geo-blocked.

This is already in the list. I added it from the source that you gave me. @Dum4G

**Comment by LaneSh4d0w** [comment]
I know there's already a version available in the playlists, but I've added the other one in case that Astra version disappears

**Comment by LaneSh4d0w** [comment]
> 
> 
> This source has unpopular channels. And few IPTV channels are only available through IPTV.

The way Astra is being used is to restream satellite channels to m3u8 files, so yup, I do agree that some channels are very rare (Naaptol as an example)

**Review by Dum4G — APPROVED** [review]

**Comment by Niyasmkkv** [comment]
But Naptol is a satellite channel. It's available as a the default channel in most of the local cable network. They pay the carriage fee well enough.

**Pull request merged**
