### PR TITLE
Update sa, kw, ae

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by BountyChocolate123456** [comment]
Thanks @LaneSh4d0w for updating streamlink

**Comment by LaneSh4d0w** [comment]
> Thanks @LaneSh4d0w for updating streamlink

I'm not behind this implementation =) @dct-infra takes care of this server. Tested some links, some do not work, but answer with a single file on mine.

**Comment by BountyChocolate123456** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://rotana.net/live-cinema

"Unable to open URL: https://pubads.g.doubleclick.net/ssai/event..."

I think it's because @dct-infra has an adblocker on the server

**Comment by LaneSh4d0w** [comment]
> http://free.fullspeed.tv/iptv-query?streaming-ip=https://rotana.net/live-cinema
> 
> "Unable to open URL: https://pubads.g.doubleclick.net/ssai/event..."
> 
> I think it's because @dct-infra has an adblocker on the server

Works on mine, but it bases itself on Google's DAI, there's no token.

**Comment by BountyChocolate123456** [comment]
@LaneSh4d0w http://free.fullspeed.tv/iptv-query?streaming-ip=https://rotana.net/live-elressalah works for me

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w http://free.fullspeed.tv/iptv-query?streaming-ip=https://rotana.net/live-elressalah works for me

image

**Comment by BountyChocolate123456** [comment]
@LaneSh4d0w https://streamtest.in/logs/http-free-fullspeed-tv-iptv-query-streaming-ip-https-rotana-net-live-elressalah

**Comment by LaneSh4d0w** [comment]
Might be geo-blocked idk.

**Review by freearhey — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]
Funnily enough, I've used a VPN and they work.

**Pull request merged**
