### PR TITLE
Update id.m3u

### PR DESCRIPTION
**Pull request by antosatriani**
update to transtv playlist streaming location

### CODE REVIEW

**Comment by singkie** [comment]
bad update, i dont recommend this MR

**Comment by antosatriani** [comment]
> bad update, i dont recommend this MR

how could you said bad update, I ve tested old playlist.m3u8 didn't working on most of hls player. but the new update to https://video.detik.com/transtv/smil:transtv.smil/chunklist_w525804931_b744100_sleng.m3u8 is working fine.. so what the...

**Comment by singkie** [comment]
> > bad update, i dont recommend this MR
> 
> how could you said bad update, I ve tested old playlist.m3u8 didn't working on most of hls player. but the new update to https://video.detik.com/transtv/smil:transtv.smil/chunklist_w525804931_b744100_sleng.m3u8 is working fine.. so what the...

what hls player you use? i've try current link on VLC and work without any problems.

**Comment by antosatriani** [comment]
> > > bad update, i dont recommend this MR
> > 
> > 
> > how could you said bad update, I ve tested old playlist.m3u8 didn't working on most of hls player. but the new update to https://video.detik.com/transtv/smil:transtv.smil/chunklist_w525804931_b744100_sleng.m3u8 is working fine.. so what the...
> 
> what hls player you use? i've try current link on VLC and work without any problems.

i'm working on video.js. most of playlist.m3u8 can be played with this player. but some playlist's type not supported on this player. (eg: playlist.mpd). I dont know . may be video.js need some plugin.

**Comment by singkie** [comment]
> > > > bad update, i dont recommend this MR
> > > 
> > > 
> > > how could you said bad update, I ve tested old playlist.m3u8 didn't working on most of hls player. but the new update to https://video.detik.com/transtv/smil:transtv.smil/chunklist_w525804931_b744100_sleng.m3u8 is working fine.. so what the...
> > 
> > 
> > what hls player you use? i've try current link on VLC and work without any problems.
> 
> i'm working on video.js. most of playlist.m3u8 can be played with this player. but some playlist's type not supported on this player. (eg: playlist.mpd). I dont know . may be video.js need some plugin.

you might add referer to that playlist.m3u8, it protected when you use that streamlink outside the official website. i dont know that video.js can add referer or not.
for your update, you might add the referer, not the link

**Pull request closed without merging**
