### PR TITLE
PE: Add TV Mundo Arequipa

### PR DESCRIPTION
**Pull request by sguinetti**
From Official Youtube channel.

### CODE REVIEW

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — COMMENTED** [review]
Streamlink having issues right now with this kind of links, cannot approve nor request changes.

EDIT : It seems the issue was fixed on Streamlink's side in terms of code, i'll see if I can compile a version ready to use for query-streamlink.

**Review by dct-infra — COMMENTED** [review]
doesn't work for me even though the stream is valid and working on YT
_getting {"Error":"Unable to validate result: Unable to validate key_ through the api

**Comment by LaneSh4d0w** [comment]
> doesn't work for me even though the stream is valid and working on YT _getting {"Error":"Unable to validate result: Unable to validate key_ through the api

Yep, see https://github.com/streamlink/streamlink/commit/5e4707844fa3dd8eaf89dc16a400d21ff19d15c5

**Comment by dct-infra** [comment]
> > doesn't work for me even though the stream is valid and working on YT _getting {"Error":"Unable to validate result: Unable to validate key_ through the api
> 
> Yep, see [streamlink/streamlink@5e47078](https://github.com/streamlink/streamlink/commit/5e4707844fa3dd8eaf89dc16a400d21ff19d15c5)

Less time to follow currently...
I understand why I was having issues with my own playlists
Upgraded streamlink from the master branch, seems to be working, less code 200 "garbage" in the logs. Thanks for the hint.

**Review by dct-infra — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]
Now works.

**Pull request merged**
