### PR TITLE
GE : Scrape channels from Tulix

### PR DESCRIPTION
**Pull request by BellezaEmporium**

### CODE REVIEW

**Review by Dum4G — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
Channels come from there : https://giniko.tv/package-channels.php?id=20

**Review by freearhey — CHANGES_REQUESTED** [review]
None of the links work for me.
image

**Comment by LaneSh4d0w** [comment]
Playlist retrieval works, AES Key retrieval blocks on certain programs, but works using browser extension...

Weird. Gonna draft this the time i'm searching for the solution.

**Comment by LaneSh4d0w** [comment]
OK, after some fiddling I've found the issue. The AES server requires a session cookie to get the link, something that VLC and/or Streamlink do not gather over the requests, causing the AES server to constantly reject the requests.

I can inject cookies over headers before request redirection, thanks to my iptv-all server. I'll see what I can do.

**Pull request closed without merging**
