### PR TITLE
Update mx.m3u

### LINKED ISSUE #12339: Add: NMás
### Channel ID

NPlus.mx

### Stream URL (optional)

_No response_

### Notes (optional)

Original request: #10631

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### PR DESCRIPTION
**Pull request by freearhey**
Closes #12339

### CODE REVIEW

**Comment by Carlinhos027** [comment]
N+ channels works on my side

**Review by BellezaEmporium — COMMENTED** [review]
Doesn't need to be Geo for me, works from a French IP.

**Comment by freearhey** [comment]
Updated.

**Comment by PopeyeTheSai10r** [comment]
I think we should tag them as GeoBlocked. They won't work from American IPs.

**Comment by freearhey** [comment]
Updated again.

**Review by PopeyeTheSai10r — APPROVED** [review]

**Review by Carlinhos027 — APPROVED** [review]

**Pull request merged**
