### PR TITLE
Testing PR -> Anti v master

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Test

### CODE REVIEW

**Comment by freearhey** [comment]
@LaneSh4d0w Please change the title of the PR.

**Comment by AntiPontifex** [comment]
I thought the original title - albeit naughty - was rather fitting.

**Comment by LaneSh4d0w** [comment]
watch out, the same link but on different names.

**Comment by AntiPontifex** [comment]
Can't make commits: says page is out of date.

**Comment by AntiPontifex** [comment]
Same comment two weeks later.

**Comment by BellezaEmporium** [comment]
108 conflicts to be solved.

**Comment by BellezaEmporium** [comment]
Original fork was terminated, can't do much.

**Comment by AntiPontifex** [comment]
Thanks for the answer.

**Comment by BellezaEmporium** [comment]
Cannot push the changes in.

**Comment by AntiPontifex** [comment]
Well, I'd say close it, bit it's up to the community. A lot of time wasted.

**Comment by BellezaEmporium** [comment]
> Well, I'd say close it, but it's up to the community. A lot of time wasted.

You can refork the project, I have the changes up in local.

**Comment by AntiPontifex** [comment]
I've tried: no can do (or I'm not doing it properly). Up to you, my friend.

**Pull request closed without merging**
