### PR TITLE
Update uk.m3u

### LINKED ISSUE #13698: Broken: CBS Reality EMEA [UK]
### Broken Link

http://st02.lab.cho01.iptv.grapesc.cz/720-tv-stb.m3u8

### What happened to the stream?

Other

### Possible Replacement (optional)

_No response_

### Notes (optional)

While the stream itself is working, it is not the correct channel. This is the UK version of CBS Reality with a voiceover in the Czech language. It is not CBS Reality EMEA channel.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### PR DESCRIPTION
**Pull request by eurohunter**
closes #13698

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
> While the stream itself is working, it is not the correct channel. This is the UK version of CBS Reality with a voiceover in the Czech language. It is not CBS Reality EMEA channel.

https://github.com/iptv-org/iptv/issues/13698

It would be better to just remove the wrong `tvg-id` and update the title.

**Comment by eurohunter** [comment]
> > While the stream itself is working, it is not the correct channel. This is the UK version of CBS Reality with a voiceover in the Czech language. It is not CBS Reality EMEA channel.
> 
> #13698
> 
> It would be better to just remove the wrong `tvg-id` and update the title.

I updated the Pull Request by readding the link and removing the tvg-id and updating the title.

**Review by freearhey — DISMISSED** [review]

**Review by kaikyoofers — COMMENTED** [review]
Change the name "CBS Reality CZ" to "CBS Reality Czech".

**Comment by eurohunter** [comment]
> Change the name "CBS Reality CZ" to "CBS Reality Czech".

I just changed the name to CBS Reality Czech

**Review by freearhey — APPROVED** [review]

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
