### PR TITLE
Fix auto-update action

### LINKED ISSUE #2894: Fix: Auto-update bug
https://github.com/iptv-org/iptv/runs/2670519706?check_suite_focus=true
Please fix the bug and run it manually.

### PR DESCRIPTION
**Pull request by freearhey**
Fixes #2894

This update adds another step to the `auto-update` process. Now all changes will be combined into a separate pull request, and then automatically merged with the `master` branch. This will allow us to continue to make automatic updates and protect the main branch at the same time.

Also this update removes unnecessary files: `.readme/_categories.md`, `.readme/_countries.md`, `.readme/_languages.md`.

### CODE REVIEW

**Comment by Dum4G** [comment]
>Also this update removes unnecessary files

These files can be referenced to show which categories, languages and countries are supported and how to reference them

**Comment by freearhey** [comment]
@Dum4G you can still refer directly to the lists in README.md, like so: https://github.com/iptv-org/iptv#playlists-by-category

**Review by heroku-miraheze — APPROVED** [review]

**Comment by themak1985** [comment]
Hey @freearhey - sorry I have been away - had to deal with some life stuff.  This is a bit beyond my expertise, but looks like great work.

**Review by Sphinxroot — APPROVED** [review]
since im not a pro whit the github actions .. as i read it it seem all good :)

**Comment by freearhey** [comment]
@themak1985 It's okay, I haven't had enough time for this project lately either.

**Pull request merged**
