### PR TITLE
Add link to Open Collective

### PR DESCRIPTION
**Pull request by freearhey**
This update adds a link to the [iptv-org](https://opencollective.com/iptv-org) page on Open Collective. It is a service which allows to collect donations for open source projects like ours and then distribute them transparently among all members.

All funds collected through this service will be distributed among all members of iptv-org to compensate them for their time spent maintaining the project.

To iptv-org members: please provide your email address in your GitHub profile so I can send you an invitation from Open Collective.

### CODE REVIEW

**Review by BellezaEmporium — COMMENTED** [review]
Is it useful to keep the other ways of funding where we only have Open-Collective for now ?

**Comment by freearhey** [comment]
@LaneSh4d0w Yes.

**Review by BellezaEmporium — APPROVED** [review]

**Review by Sphinxroot — APPROVED** [review]

**Review by themak1985 — APPROVED** [review]

**Comment by freearhey** [comment]
@Daniel15 Sent.

@LaneSh4d0w Please check your email, there should already be an invite there.

@Sphinxroot @MapGuy11 Please add your email address to GitHub profile or create an account on Open Collective and write your username here so I can send you the invites.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @Daniel15 Sent.
> 
> @LaneSh4d0w Please check your email, there should already be an invite.
> 
> @Sphinxroot @MapGuy11 Please add your email address to GitHub profile or create an account on Open Collective and write your username here so I can send you the invites.

It's good for me.

**Comment by MapGuy11** [comment]
I think this is what you want: https://opencollective.com/mapguy11

**Review by MapGuy11 — APPROVED** [review]

**Comment by freearhey** [comment]
@MapGuy11 Yeah.

**Comment by freearhey** [comment]
@Sphinxroot When you create an Open Collective account, post your nickname here and I'll also send you an invite.

**Comment by freearhey** [comment]
@Dum4G Please add your email address to GitHub profile or create an account on Open Collective and write your username here so I can send you the invite.

**Comment by Dum4G** [comment]
saadm@yandex.ru

> @Dum4G Please add your email address to GitHub profile or create an account on Open Collective and write your username here so I can send you the invite.

**Comment by freearhey** [comment]
@Central302 @dct-infra @sguinetti @what-a Please add your email address to GitHub profile or create an account on [Open Collective](https://opencollective.com/) and write your username here so I can send you the invite.


To all @iptv-org/members: Any of you can get your share of the funds from our Open Collective [account](https://opencollective.com/iptv-org#category-BUDGET). Right now, each member can request up to 9.09% (100% / 11 members) of the organization's total budget. To do this, you just need to submit an invoice for the desired amount through this [form](https://opencollective.com/iptv-org/expenses/new). This process is described in more detail [here](https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses). Without such a request, unfortunately, it is not possible to transfer money to you. 

If you have any questions on this subject, leave them below and I will try to find an answer to them.

**Comment by what-a** [comment]
My email address is now added to my GitHub profile.

**Comment by dct-infra** [comment]
Username is: dct-infra

**Comment by sguinetti** [comment]
Username is: `diegouser`

**Pull request merged**
