### PR TITLE
Update ba.m3u, hr.m3u, rs.m3u, si.m3u

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by Dum4G** [comment]
We respect origin countries of every channel and then specify where those intended to be broadcasted in tvg-country tag. If you want Balkan channels you should download autogenerated playlists from this repo description

**Comment by muzena** [comment]
@Dum4G 
Now I don't understand anything.
Can you at least add N1 channel on those playlists?

**Comment by Dum4G** [comment]
https://github.com/iptv-org/iptv#playlists-by-language
https://github.com/iptv-org/iptv#playlists-by-country

Just check those links and you'll understand how this repo works. Will add N1 later today

**Comment by muzena** [comment]
@Dum4G 
Can you add in Croatia.m3u  for streams with [NO KODI]; user agent.
Without user agent those streams do not work, eg:
#EXTINF:-1 tvg-id="htv1.hr" tvg-name="HTV1" tvg-country="HR" tvg-language="Croatian" tvg-logo="https://i.imgur.com/W3FBVwT.png" group-title="",HRT 1 (720p) [NO KODI]
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (X11; Linux i686; rv:90.0) Gecko/20100101 Firefox/90.0
http://195.29.70.67/PLTV/88888888/224/3221226139/index.m3u8

**Pull request closed without merging**
