### PR TITLE
Pluto: Update all channels

### PR DESCRIPTION
**Pull request by BellezaEmporium**
New channels went in for Pluto, doing the necessary changes. Massive PR, I know, but it's for the best of those channels.

NOTE : channels are updated using Pluto.tv's API with VPN set on all available countries possible. M3U generation made possible thanks to PlutoIPTV.

Changelog : 
- Updated all existent Pluto.tv channels with fresh links from API (incl. no server side ads)
- Added countries : DK, SE, NO, CH, IT, AR, CL, CR.

TODO ; Change channel name to fit those in the database.

### CODE REVIEW

**Comment by theraveztv** [comment]
#EXTINF:-1 tvg-id="RAVE-Z TV " tvg-logo="https://i.imgur.com/eJXfMh0.png" group-title="Undefined",RAVE-Z 8K (4320p)
https://theraveztv.page.link/iptv

**Comment by theraveztv** [comment]
#EXTINF:-1 tvg-id="RAVE-Z " tvg-logo="https://i.ibb.co/Jnq9SXQ/rave-pn5w.png" group-title="Undefined",RAVE-Z TV 8K (4320p)
https://raveztv.page.link/stream

**Comment by Epictyphlosion** [comment]
Any updates?

**Comment by kaikyoofers** [comment]
@BellezaEmporium anymore updates?

**Comment by BellezaEmporium** [comment]
Haven't had time to check again, and with the recent Pluto lock-ins, i'm thinking about this being necessary or not...

**Comment by Sphinxroot** [comment]
PLUTO TEMPLATE 
http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/xxxxxxxxxxxx/master.m3u8?deviceType=0&deviceModel=0&deviceMake=0&appVersion=0&deviceVersion=0&deviceDNT=0

**Comment by freearhey** [comment]
Closed due to a conflict in the files. Feel free to create a new PR when it is ready.

**Pull request closed without merging**
