### PR TITLE
Remove broken links

### PR DESCRIPTION
**Pull request by freearhey**
All links were tested with the built-in script and VLC player at different times of the day.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
dang, the timing ! I also was checking links x)

I need to fix things on my checker, but it's saying that we got 56 duplicate streams, and i've seen radio streams.

**Comment by Sphinxroot** [comment]
@freearhey  i wonder if if will break the playlist if you put a update link in it ?

maybe 
# update url : http://URL to live stream 
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="" group-title="",
link to stream .m3u8

**Comment by LaneSh4d0w** [comment]
> 
> 
> @freearhey i wonder if if will break the playlist if you put a update link in it ?
> 
> maybey add # update url : http://URL to live stream
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-country="" tvg-language="" tvg-logo="" group-title="",
> link to stream .m3u8

Depends on whether he decides to merge his PR before another one.

**Review by Sphinxroot — COMMENTED** [review]
ANQ channel we be back the 13 that why its offline for now

**Comment by freearhey** [comment]
@Sphinxroot I'm sorry, but I don't understand your question.

**Comment by Free-IPTV** [comment]
Ohh... i am so sad, so many italian streams are gone but we has all new stream-address from Mediaset... und you can´t grab it from us!!! It´s in private repo!!! Haha... Happy day!!!

**Comment by Sphinxroot** [comment]
@freearhey   here a exemple of what iim trying to say https://i.imgur.com/6RGuxa5.png  if you add a # update link to stream ,  it could be easier to get the news link  when they change  .. for me when i use it in kodi i dont see this because the #  is hiding in the playlist  .. 

and i got a request also  .. if you want for sure .. if possible to add a playlist  KodiOnly.m3u  .. il would put  link that need referrer in it + whit proper tag in name for country  
exemple :
# Update link :
#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="CU" tvg-language="" tvg-logo="https://www.tvcubana.icrt.cu/images/canaleslogo/cubavision-internacional.jpg" group-title="",CU | Cubavisión Internacional (480p)
https://cdn.teveo.cu/live/video/A36pWmuWvZBQskuZ/ngrp:gppfydfzpSUn9Udy.stream/playlist.m3u8|Referer=https://teveo.cu/live/video/AKDdWvMTYzfsfnNJ/embed?auto=false

i got a kodi plugin that handle the index file it would be cool to have it 

thanks :)

**Comment by freearhey** [comment]
@Sphinxroot Now I see. 

I personally think this will cause playlists to become too cluttered, but I would suggest that you create a separate [issue](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=discussion&template=feature-request.md&title=Propose%3A+xxx) on this topic so others can give their opinions on this too.

**Pull request merged**
