### PR TITLE
Update us_local.m3u

### LINKED ISSUE #17443: Chariton valley Cable channels
### Your full legal name

Chariton Cable Customer  Service

### Are you the copyright holder or authorized to act on the copyright owner's behalf?

Yes, I am the copyright holder.

### Please describe the nature of your copyright ownership or authorization to act on the owner's behalf.

channels scanned and stolen from our TVanywhere platform ! 

### Please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.

https://github.com/iptv-org/iptv/commit/8ade035f3c41909de02968ccfaa580725a4956bd

### What content should be removed? Please specify the URL for each item or, if it is an entire file, the file's URL.

#EXTINF:-1 tvg-id="KOMUDT1.us",KOMU-DT1 (720p)
https://cvtv.cvalley.net/hls/KOMUNBC/KOMUNBC.m3u8
#EXTINF:-1 tvg-id="KMOSDT1.us",KMOS-DT1 (720p)
https://cvtv.cvalley.net/hls/KMOSPBS/KMOSPBS.m3u8
#EXTINF:-1 tvg-id="KOMUDT3.us",KOMU-DT3 (720p)
https://cvtv.cvalley.net/hls/KOMUCW/KOMUCW.m3u8
#EXTINF:-1 tvg-id="KRCGDT1.us",KRCG-DT1 (720p)
https://cvtv.cvalley.net/hls/KRCGCBS/KRCGCBS.m3u8
#EXTINF:-1 tvg-id="KMIZDT1.us",KMIZ-DT1 (720p)
https://cvtv.cvalley.net/hls/KMIZABC/KMIZABC.m3u8
#EXTINF:-1 tvg-id="KQFXLD1.us",KQFX-LD1 (720p)
https://cvtv.cvalley.net/hls/KQFXFOX/KQFXFOX.m3u8
#EXTINF:-1 tvg-id="KCTVDT1.us",KCTV-DT1 (720p)
https://cvtv.cvalley.net/hls/KCTVCBS/KCTVCBS.m3u8
#EXTINF:-1 tvg-id="KSHBDT1.us",KSHB-DT1 (720p)
https://cvtv.cvalley.net/hls/KSHBNBC/KSHBNBC.m3u8
#EXTINF:-1 tvg-id="KMBCDT1.us",KMBC-DT1 (720p)
https://cvtv.cvalley.net/hls/KMBCABC/KMBCABC.m3u8
#EXTINF:-1 tvg-id="WDAFDT2.us",WDAF-DT2 (720p)
https://cvtv.cvalley.net/hls/WDAFAntenna/WDAFAntenna.m3u8
#EXTINF:-1 tvg-id="KMIZDT3.us",KMIZ-DT3 (720p)
https://cvtv.cvalley.net/hls/KZOUMYZOU/KZOUMYZOU.m3u8
#EXTINF:-1 tvg-id="KYOUDT4.us",KYOU-DT4 (720p)
https://cvtv.cvalley.net/hls/KYOUDT4/KYOUDT4.m3u8
#EXTINF:-1 tvg-id="KYOUDT5.us",KYOU-DT5 (720p)
https://cvtv.cvalley.net/hls/KYOUGrit/KYOUGrit.m3u8
#EXTINF:-1 tvg-id="KYOUDT2.us",KYOU-DT2 (720p)
https://cvtv.cvalley.net/hls/KYOUNBC2/KYOUNBC2.m3u8
#EXTINF:-1 tvg-id="KYOUDT2.us",KYOU-DT2 (480p)
https://cvtv.cvalley.net/hls/KYOUNBC/KYOUNBC.m3u8
#EXTINF:-1 tvg-id="KTVODT3.us",KTVO-DT3 (720p)
https://cvtv.cvalley.net/hls/KTVOComet/KTVOComet.m3u8
#EXTINF:-1 tvg-id="KSMODT1.us",KSMO-DT1 (720p)
https://cvtv.cvalley.net/hls/KSMOIND/KSMOIND.m3u8
#EXTINF:-1 tvg-id="KSHBDT3.us",KSHB-DT3 (720p)
https://cvtv.cvalley.net/hls/KSHBLaff/KSHBLaff.m3u8
#EXTINF:-1 tvg-id="KSHBDT2.us",KSHB-DT2 (720p)
https://cvtv.cvalley.net/hls/KSHBCozi/KSHBCozi.m3u8
#EXTINF:-1 tvg-id="KRCGDT2.us",KRCG-DT2 (720p)
https://cvtv.cvalley.net/hls/KRCGComet/KRCGComet.m3u8
#EXTINF:-1 tvg-id="KPXEDT1.us",KPXE-DT1 (720p)
https://cvtv.cvalley.net/hls/KPXEION/KPXEION.m3u8
#EXTINF:-1 tvg-id="KMIZDT2.us",KMIZ-DT2 (720p)
https://cvtv.cvalley.net/hls/KMIZMeTV/KMIZMeTV.m3u8
#EXTINF:-1 tvg-id="KMCIDT2.us",KMCI-DT1 (720p)
https://cvtv.cvalley.net/hls/KMCIBounceTV/KMCIBounceTV.m3u8
#EXTINF:-1 tvg-id="KMBCDT2.us",KMBC-DT2 (720p)
https://cvtv.cvalley.net/hls/KMBCMeTV/KMBCMeTV.m3u8
#EXTINF:-1 tvg-id="KCWEDT1.us",KCWE-DT1 (720p)
https://cvtv.cvalley.net/hls/KCWECW/KCWECW.m3u8
#EXTINF:-1 tvg-id="KCPTDT1.us",KCPT-DT1 (720p)
https://cvtv.cvalley.net/hls/KCPTPBS/KCPTPBS.m3u8
#EXTINF:-1 tvg-id="WDAFDT1.us",WDAF-DT1 (720p)
https://cvtv.cvalley.net/hls/WDAFFox/WDAFFox.m3u8
#EXTINF:-1 tvg-id="KNLJDT1.us",KNLJ-DT1 (720p)
https://cvtv.cvalley.net/hls/KNLJ/KNLJ.m3u8
#EXTINF:-1 tvg-id="KTVODT2.us",KTVO-DT2 (720p)
https://cvtv.cvalley.net/hls/KTVOCBS/KTVOCBS.m3u8
#EXTINF:-1 tvg-id="KTVODT1.us",KTVO-DT1 (720p)
https://cvtv.cvalley.net/hls/KTVOABC/KTVOABC.m3u8
#EXTINF:-1 tvg-id="KMCIDT1.us",KMCI-DT1 (720p)
https://cvtv.cvalley.net/hls/KMCIIND/KMCIIND.m3u8

### Any additional information we need to know?

we will offer a bounty soon for the help in persecution of the github users posting and stealing our content.

more information on our website and facebook page :  www.cvalley.net & https://www.facebook.com/CharitonValley/

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Comply with, and fix #17443. That's the issue of being the "known" repository while a few others got it for years. Won't epilogate on this furthermore.

Also remove us_moveonjoy as I feel something similar will come in a few days.

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
> is moveonjoy the Chariton Valley Cable?

Nope, but it seems it belongs to another cable company. Whatever happens shouldn't happen if we remove it before.

**Review by Sphinxroot — APPROVED** [review]

**Review by Alstruit — COMMENTED** [review]
I've yet to see a valid claim.

**Comment by BellezaEmporium** [comment]
> I've yet to see a valid claim.

I've yet do to a ping/pong challenge on adding and removing links.
Linked issue might be real, but well, as said, we're the known repository. It would happen sooner or later.
Even if we have nothing against MOJ, it's, again, yet to happen.

**Comment by Sphinxroot** [comment]
yes the  claim look strange ,  since 2019 they are out , cable company is in missouri  and the user claim is in kansas , but before thing get out of hand , its better to remove them  , and let see if all links get dmca  , sadly its to easy to make dmca claim on github   and repo get closed with ease

**Comment by Chariton-ValleyCable** [comment]
> yes the claim look strange , since 2019 they are out , cable company is in missouri and the user claim is in kansas , but before thing get out of hand , its better to remove them , and let see if all links get dmca , sadly its to easy to make dmca claim on github and repo get closed with ease


Most of the premium channels URL have been changed and locked we are now working on the locals one which will be complete in next few hours

Sphinxroot you proved to be ignorant and not really intelligent. 
Please refrain from commenting and proving you lack cognitive functions and basic geography skills. 

Kansas Missouri https://en.wikipedia.org/wiki/Kansas_City,_Missouri

**Comment by Sphinxroot** [comment]
> > yes the claim look strange , since 2019 they are out , cable company is in missouri and the user claim is in kansas , but before thing get out of hand , its better to remove them , and let see if all links get dmca , sadly its to easy to make dmca claim on github and repo get closed with ease
> 
> Most of the premium channels URL have been changed and locked we are now working on the locals one which will be complete in next few hours
> 
> Sphinxroot you proved to be ignorant and not really intelligent. Please refrain from commenting and proving you lack cognitive functions and basic geography skills.
> 
> Kansas Missouri https://en.wikipedia.org/wiki/Kansas_City,_Missouri

i dont mind ... the fact is  .. ur 5 years late mate , why  now  ?  and not then  ... because its here ?  there are everywhere now ... just a reminder .. 

this is a dream   ... free for all , no geo stream , no dmr , no token , and get ur money , from ads you get from unique ip viewer ,  and most of all , let people choose the  apps  they want to use  ...  utopia .. it might be .  we are far . from a free world

**Pull request closed without merging**
