### PR TITLE
Update kr.m3u

### PR DESCRIPTION
**Pull request by AVGCFan1995**
I was reordering the MBC TV regional feeds in the alphabetical order in order to make less confusing. Likewise, I'm switching the order between SBS and G1 in order to match the other SBS feeds.

### CODE REVIEW

**Review by Alstruit — COMMENTED** [review]
Should the order be not in alphabetical order using the tvg-id instead of the Channel ID?

**Comment by AVGCFan1995** [comment]
> 

Why we're using the tvg-id of alphabetical order.

**Comment by BellezaEmporium** [comment]
> I was reordering the MBC TV regional feeds in the alphabetical order in order to make less confusing. Likewise, I'm switching the order between SBS and G1 in order to match the other SBS feeds.

Won't be useful, as the bot will sort them again where they were before. TVG-ID before channel naming.

**Comment by freearhey** [comment]
I created the poll to find a general consensus: https://github.com/orgs/iptv-org/discussions/1452 After the survey is over, the selected rule will be added to the Contribution Guide and the script responsible for sorting will be updated accordingly.

**Review by freearhey — APPROVED** [review]

**Review by Alstruit — APPROVED** [review]

**Pull request merged**
