### PR TITLE
Update in.m3u

### PR DESCRIPTION
**Pull request by desiflex**
new link

### CODE REVIEW

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
...

It redirects to a Twitch link, but why ? The link you've replaced is still working.

**Review by Sphinxroot — COMMENTED** [review]
this link is still good why change it for a url shortner and whit a token link



masterManifest | http://newsjatt.camdvr.org:1935/newsjatt/myStream/playlist.m3u8

mediaManifest | http://newsjatt.camdvr.org:1935/newsjatt/myStream/chunklist_w837951016.m3u8

**Comment by desiflex** [comment]
Old link going offline soon

**Comment by LaneSh4d0w** [comment]
> 
> Old link going offline soon

Are you the maintainer of this channel ?

**Comment by desiflex** [comment]
Yes and it’s renamed newsdons and language Punjabi

**Comment by LaneSh4d0w** [comment]
I see the channel that is linked to the stream is : https://www.twitch.tv/newsjatt and is indeed tagged Newsdons.

We can add it as a backup link, and we'll delete it when it's not functional anymore.

**Comment by desiflex** [comment]
Cheers thanks mate

**Comment by themak1985** [comment]
Closed in favor of #3001

**Comment by desiflex** [comment]
https://live20.bozztv.com/giatv/giatv-jattvibe/jattvibe/chunks.m3u8

**Pull request closed without merging**
