### PR TITLE
Update us.m3u

### LINKED ISSUE #5200: Fox Türkiye
**Channel Name:** FOX
**Channel ID:** FoxTurkey.us
**Country:** tr
**Language:** tr
**Website:** https://www.fox.com.tr/
**Stream URL (optional):** xxx
**Notes (optional):** livestream: https://www.fox.com.tr/canli-yayin

### LINKED ISSUE #5266: Rewind TV
**Channel Name:rewindtv 
**Country:usa
**Language: English 
**Website: https://rewindtv.com/
**Stream URL (optional):https://rewindtv.com/
**Notes (optional):please bring this channel back

### LINKED ISSUE #5277: FOX Weather
**Channel Name:** FOX Weather
**Country:** USA
**Language:** English
**Website:** https://www.foxweather.com/
**Stream URL (optional):** https://247wlive.foxweather.com/stream/index.m3u8
**Notes (optional):** FOX Weather is New Free Streaming Channel
for USA National Weather. This Channel was Opened in October.
Notice That Working on Pot player in 720p.

### LINKED ISSUE #5440: BabyFirst TV
**Channel Name:** BabyFirst TV
**Country:** United States
**Language:** English
**Website:** https://www.babyfirsttv.com/
**Stream URL (optional):** https://babyfirst.akamaized.net/hls/live/2028842/bftvusaott/playlist.m3u8
**Notes (optional):** Grabbed from their mobile app by proxying.

### LINKED ISSUE #5509: Newsmax TV
**_Channel Name:_** Newsmax TV
**_Country:_** US
**_Broken Link (from playlist):_** http://nmxlive.akamaized.net/hls/live/529965/Live_1/master.m3u8
**_Possible Replacement (optional):_** https://nmxlive.akamaized.net/hls/live/529965/Live_1/index_720.m3u8 https://nmxlive.akamaized.net/hls/live/529965/Live_1/index_288.m3u8 https://nmxlive.akamaized.net/hls/live/529965/Live_1/index.m3u8
**_Notes (optional):_** There was three Newsmax TV streams on the playlist, but only one remains, and it isn't working. I've added the XUMO stream (one of the two that have been removed) in my favorites on SSIPTV and it works. The three replacement links are different resolutions, but they are from the same sever. Consider also adding back the XUMO stream.

### PR DESCRIPTION
**Pull request by freearhey**
Closes #5440
Closes #5277
Closes #5509

### CODE REVIEW

**Review by Dum4G — DISMISSED** [review]

**Review by MapGuy11 — CHANGES_REQUESTED** [review]
Remove Rewind TV that will be coming later #5296

**Review by Dum4G — DISMISSED** [review]

**Comment by freearhey** [comment]
@MapGuy11 why?

**Comment by MapGuy11** [comment]
> @MapGuy11 why?

We are currently working with all the streams to get them ready and add them that is why I linked #5296. With inserting the link this way not all players can play these streams. If you could just please wait and we will have all of these ready soon. @LaneSh4d0w would you agree?

**Comment by LaneSh4d0w** [comment]
> > @MapGuy11 why?
> 
> We are currently working with all the streams to get them ready and add them that is why I linked #5296. With inserting the link this way not all players can play these streams. If you could just please wait and we will have all of these ready soon. @LaneSh4d0w would you agree?

To be honest this one is the only quality we have for Rewind. We can safely put the 432p links in the playlists as they're the "isolated" ones. As for the ones beginning with 480p to 1080p, better wait, yes.

**Comment by MapGuy11** [comment]
> > > @MapGuy11 why?
> > 
> > 
> > We are currently working with all the streams to get them ready and add them that is why I linked #5296. With inserting the link this way not all players can play these streams. If you could just please wait and we will have all of these ready soon. @LaneSh4d0w would you agree?
> 
> To be honest this one is the only quality we have for Rewind. We can safely put the 432p links in the playlists as they're the "isolated" ones. As for the ones beginning with 480p to 1080p, better wait, yes.

Here is the issue though, not putting the stream behind something it won't work on some players. If we could just have @freearhey wait so then all the links are behind the same domain and it's all clean.

**Comment by LaneSh4d0w** [comment]
> > > > @MapGuy11 why?
> > > 
> > > 
> > > We are currently working with all the streams to get them ready and add them that is why I linked #5296. With inserting the link this way not all players can play these streams. If you could just please wait and we will have all of these ready soon. @LaneSh4d0w would you agree?
> > 
> > To be honest this one is the only quality we have for Rewind. We can safely put the 432p links in the playlists as they're the "isolated" ones. As for the ones beginning with 480p to 1080p, better wait, yes.
> 
> Here is the issue though, not putting the stream behind something it won't work on some players. If we could just have @freearhey wait so then all the links are behind the same domain and it's all clean.

Precise "behind something". You mean, in a .m3u file with this as an entry ?

**Comment by MapGuy11** [comment]
> > > > > @MapGuy11 why?
> > > > 
> > > > 
> > > > We are currently working with all the streams to get them ready and add them that is why I linked #5296. With inserting the link this way not all players can play these streams. If you could just please wait and we will have all of these ready soon. @LaneSh4d0w would you agree?
> > > 
> > > 
> > > To be honest this one is the only quality we have for Rewind. We can safely put the 432p links in the playlists as they're the "isolated" ones. As for the ones beginning with 480p to 1080p, better wait, yes.
> > 
> > 
> > Here is the issue though, not putting the stream behind something it won't work on some players. If we could just have @freearhey wait so then all the links are behind the same domain and it's all clean.
> 
> Precise "behind something". You mean, in a .m3u file with this as an entry ?

A .m3u8 file on a webhost

**Comment by freearhey** [comment]
I still don't see how adding this link would interfere, but whatever.

**Review by MapGuy11 — APPROVED** [review]

**Comment by MapGuy11** [comment]
> I still don't see how adding this link would interfere, but whatever.

Thanks :) Approved.

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
