### PR TITLE
PE: Add La República TV

### PR DESCRIPTION
**Pull request by sguinetti**
This PR adds stream from https://www.youtube.com/c/RTVLaRep%C3%BAblica This streams monday to friday. See https://www.youtube.com/c/RTVLaRep%C3%BAblica/videos?view=2&live_view=503

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Can't confirm if channel works : offline for the moment.

I'll check in a few hours.

**Comment by yonee77** [comment]
Review required

**Comment by LaneSh4d0w** [comment]
Couldn't confirm so far that channel was working. Always came in when no live was on.

**Review by BellezaEmporium — COMMENTED** [review]
Still cannot confirm. No live seen since publication of the stream.

**Comment by sguinetti** [comment]
> Still cannot confirm. No live seen since publication of the stream.

The stream was live 1 hour ago. I think of the stream have some pauses into programs.

**Comment by sguinetti** [comment]
Also, the query-streamlink-us.herokuapp.com service is working for other streams?

**Comment by LaneSh4d0w** [comment]
> 
> 
> Also, the query-streamlink-us.herokuapp.com service is working for other streams?

Down until next month. 550 hours reached. REPL is safe to go.

**Review by BellezaEmporium — DISMISSED** [review]

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by Dum4G** [comment]
image
Finally caught it live

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
Same.

**Pull request merged**
