### PR TITLE
Sort unsorted

### PR DESCRIPTION
**Pull request by AntiPontifex**

### CODE REVIEW

**Comment by freearhey** [comment]
@AntiPontifex Please send a new PR with the same changes, just change the target branch from "iptv-org:Sort-Unsorted" to "iptv-org:master" before so we can approve it.

**Comment by AntiPontifex** [comment]
I'll try, but - to say the least - I'm a n00b at this. Thanks. If I cannot figure it out, feel free to delete.

**Comment by AntiPontifex** [comment]
Can't figure it out: sorry, but I guess I've hit my learning limit. All the best.

**Comment by freearhey** [comment]
@AntiPontifex no problem, I've already made changes to the playlist based on your edits.

Thank you for your help!

**Comment by AntiPontifex** [comment]
No problem: my pleasure! If you don't mind this workflow, I'll keep on submitting.
I try, but what can I say: I'm slow at these things. LOL!

**Comment by freearhey** [comment]
Sure, go ahead!

**Pull request closed without merging**
