### PR TITLE
Update kg.m3u

### PR DESCRIPTION
**Pull request by Emilselimli**
Added: Balastan [KG]
Added: Madaniyat [KG

### CODE REVIEW

**Comment by picoluna1969** [comment]
super

**Review by BellezaEmporium — APPROVED** [review]
LGTM.

**Comment by BellezaEmporium** [comment]
Other streams : 

http://onlinetv.ktrk.kg:1935/live/myStream/playlist.m3u8
http://onlinetv.ktrk.kg:1935/live/myStream2/playlist.m3u8
http://onlinetv.ktrk.kg:1935/live/myStream3/playlist.m3u8
http://onlinetv.ktrk.kg:1935/live/myStream4/playlist.m3u8

**Comment by Emilselimli** [comment]
geo blocked

**Comment by BellezaEmporium** [comment]
> geo blocked

They're taken from the website. Maybe they're not 24/7.

myStream3 = Background 24 (roughly translated by Yandex from the image)
myStream2 = Muzika
myStream4 = KTRK Sport

myStream1 is not playable per their website, says to be KTRK 1

**Review by freearhey — APPROVED** [review]

**Pull request merged**
