### PR TITLE
Update th.m3u

### PR DESCRIPTION
**Pull request by Soponwit19997**

### CODE REVIEW

**Comment by Dum4G** [comment]
cdn6.goprimetime.info links seem to be geo-blocked, needs confirmation

**Review by BellezaEmporium — COMMENTED** [review]
Can't confirm it either. Says connection aborted/timed out.

**Comment by BellezaEmporium** [comment]
The only CDN that answers on my side is http://cdn7.goprimetime.info/

All the others are "blank" per-se. Possibly needing a specific DNS or something.

**Comment by BellezaEmporium** [comment]
OK, it's not GEO, but it has *very VERY* specific ways to make it load.

Only accepts specific user-agents it seems...

image

**Comment by Dum4G** [comment]
@Soponwit19997 is the source http://183.89.246.119:8010 entirely dead? Because I see that you havent deleted some channels from there

**Comment by Dum4G** [comment]
@Soponwit19997

**Review by BellezaEmporium — APPROVED** [review]

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
