### PR TITLE
KR : Add specific quality

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Prevent having only one link available when there's 3 of them for each.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Another server : https://apichvod33.seezntv.com/

**Review by freearhey — COMMENTED** [review]
Titles are not used when filtering links.

**Comment by LaneSh4d0w** [comment]
> Titles are not used when filtering links.

Then it's the tvg-id part... that I can't change due to the EPG.

**Comment by freearhey** [comment]
I guess so.

**Pull request closed without merging**
