### PR TITLE
Update my.m3u

### PR DESCRIPTION
**Pull request by AzeemHadzrie**

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
The last added links (Astro + others) shows 404. Were they tested ?

**Comment by AzeemHadzrie** [comment]
Some of them were offline, I use streamtest.in to test which stream is working.

**Comment by LaneSh4d0w** [comment]
> Some of them were offline, I use streamtest.in to test which stream is working.

Noted, i'll wait for a few hours then.

**Comment by AzeemHadzrie** [comment]
Shall be fixed now. Try if it works or not.

**Review by BellezaEmporium — APPROVED** [review]
Works now.

**Pull request closed without merging**
