### PR TITLE
Update in.m3u

### PR DESCRIPTION
**Pull request by KumarX12**
Added POGO and Cartoon Network

### CODE REVIEW

**Comment by KumarX12** [comment]
#EXTINF:-1 tvg-id="POGO","POGO"
https://amg01448-samsungin-pogo-samsungin-dzccl.amagi.tv/playlist/amg01448-samsungin-pogo-samsungin/playlist.m3u8
#EXTINF:-1 tvg-id="Cartoon Network INDIA","Cartoon Network INDIA"
https://amg01448-samsungin-cartoonnw-samsungin-1y8kz.amagi.tv/playlist/amg01448-samsungin-cartoonnw-samsungin/playlist.m3u8

added for pogo and CN india

**Comment by Mavijak** [comment]
CN Is blocked

**Comment by KumarX12** [comment]
working

**Comment by Mavijak** [comment]
>  working

Not the link see:  https://github.com/iptv-org/iptv/issues/16839

**Comment by Mavijak** [comment]
> image It is working .

 Read this issue: https://github.com/iptv-org/iptv/issues/16839 im not talking about the stream url i know it's working by the way

**Comment by KumarX12** [comment]
Okay.. understood

> > image It is working .
> 
> Read this issue: #16839 im not talking about the stream url i know it's working by the way

Okay understood. POGO is live btw.

**Comment by Mavijak** [comment]
> Okay.. understood
> 
> > > image It is working .
> > 
> > 
> > Read this issue: #16839 im not talking about the stream url i know it's working by the way
> 
> Okay understood. POGO is live btw.

yeah ik

**Comment by Dum4G** [comment]
Cartoon Network is Warner Bros belonging. Can't add it because of DMCA. Also please set tvg-id according to https://github.com/iptv-org/database repo or leave it blank

**Comment by Dum4G** [comment]
POGO is also blocked by DMCA

**Pull request closed without merging**
