### PR TITLE
Update us.m3u

### LINKED ISSUE #8735: Add: WPVI-DT1
### Channel ID

WPVIDT1.us

### Stream URL

http://v-pi.theus6tv.duckdns.org/hls/6.1/playlist.m3u8

### Notes

This feed dropped out of the following playlists the other day - please add back to these playlists:
https://iptv-org.github.io/iptv/index.m3u
https://iptv-org.github.io/iptv/languages/eng.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #8736: Add: WABC-DT1
### Channel ID

WABCDT1.us

### Stream URL

http://v-ny.theus6tv.duckdns.org/hls/7.1/playlist.m3u8

### Notes

This feed dropped out of the following playlists the other day - please add back to these playlists:
https://iptv-org.github.io/iptv/index.m3u
https://iptv-org.github.io/iptv/languages/eng.m3u

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### PR DESCRIPTION
**Pull request by freearhey**
Fixes #8736, fixes #8735

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
I see none of these channels added, did you confuse with another channel ?

**Review by MapGuy11 — CHANGES_REQUESTED** [review]
Why are you changing this It's WPVI news

**Review by MapGuy11 — CHANGES_REQUESTED** [review]
Same thing for NY

**Comment by freearhey** [comment]
The thing is that several different channels were marked with the same ID, which is why the correct variant disappeared from the public playlists.

__WABCDT1.us__

https://github.com/iptv-org/iptv/blob/2af103c5e5c3e8514b9b0db95a1e6fc24ccdcc27/streams/us_localbtv.m3u#L8-L10
https://github.com/iptv-org/iptv/blob/2af103c5e5c3e8514b9b0db95a1e6fc24ccdcc27/streams/us.m3u#L1334-L1335

__WPVIDT1.us__

https://github.com/iptv-org/iptv/blob/2af103c5e5c3e8514b9b0db95a1e6fc24ccdcc27/streams/us_localbtv.m3u#L182-L184
https://github.com/iptv-org/iptv/blob/2af103c5e5c3e8514b9b0db95a1e6fc24ccdcc27/streams/us.m3u#L1462-L1463

And when I checked both uplynk.com links today I saw "ABC Localish" broadcasts, so I renamed them. But I guess it was temporary.

**Comment by robwest1** [comment]
Would it be possible to add the Bally Regional Sports Networks to the playlist?

**Pull request closed without merging**
