### PR TITLE
Update ir.m3u

### PR DESCRIPTION
**Pull request by data14a**
Added new channels from Persiana group and removed channels that no longer available.

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Persiana Group = French company

Links are already available in the French playlist.

**Comment by data14a** [comment]
They are Persian speaking channels and they should not be int the French playlist.

**Comment by LaneSh4d0w** [comment]
As @freearhey said, we do not classify the channels on their spoken language, but from where do they come from. Persiana being a French company, it's in the French playlist.

**Comment by data14a** [comment]
Because of the political climate in Iran, majority of the TV production is outside Iran. In Iran's playlist there are only 12 channels that are actually broadcast from Iran.

**Comment by LaneSh4d0w** [comment]
That for sure is something Interesting to know. What are they, if I may ask ? We will relocate them to their correct location.

**Comment by data14a** [comment]
I have tried to contribute to this project but is getting impossible if each time the request is denied because the channel is not from Iran. Iran is a country of multiple languages including: Persian (Farsi), Arabic, Kurdish, Azerbaijani and some other languages. There are no private TV stations in Iran. TV and radio stations are run by the government of Iran (IRIB), So any other channels is broadcasted from outside of Iran (US, UK, France, etc.) targeting the people of Iran. It would make sense to keep this TV station Under the country of Iran regardless of where they are located.

**Comment by LaneSh4d0w** [comment]
@freearhey thoughts ?

**Comment by freearhey** [comment]
@data14a My advice would be before you add a channel just check what country is listed in [lyngsat.com](https://www.lyngsat.com/search.html).

**Comment by data14a** [comment]
As I explained before, almost are Iranian channels are operated outside Iran. So, listing Iranian (Persian) channels under France, US or UK does not make any sense because they are not intended for people in those countries.

**Comment by freearhey** [comment]
@data14a I understand, but you also understand me, you just state the problem and do not give any solution. In addition to the Iranian playlist there are almost 200 other playlists and we have to somehow keep them in order. 

If you have an idea how to better organize all 5000 channels then please post your proposal [here](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=discussion&template=feature-request.md&title=Propose%3A+xxx) first, so that the rest of the community can give their opinion as well.

**Comment by data14a** [comment]
I just do not understand the inconsistency in applying the rules. There are 64 channels under country of Iran, out of those only 16 (some repeat channels) are broadcasted from Iran. The other 48 from multiple countries.

**Comment by freearhey** [comment]
@data14a Which ones?

**Comment by data14a** [comment]
Any channel that is not labeled IRIB.

**Comment by LaneSh4d0w** [comment]
> @data14a Which ones?

Maybe we should classify channels in their language...

**Comment by data14a** [comment]
I do not know the right path for the entire site but personally I would like to keep all the channels that are intended for people of Iran under the same m3u list regardless of the language of the TV station.

**Pull request closed without merging**
