### PR TITLE
WPSG (The CW 57) HEVC and H264

### PR DESCRIPTION
**Pull request by MapGuy11**
Try Out The Streams Before Pushing Please.

### CODE REVIEW

**Comment by MapGuy11** [comment]
I am limited to the bitrate due to bandwidth cap on internet at home.

**Review by Dum4G — APPROVED** [review]

**Comment by Dum4G** [comment]
Bitrate looks a bit limited but both did work for me, don't you worry

**Comment by MapGuy11** [comment]
> Bitrate looks a bit limited but both did work for me, don't you worry

I could drop the h264 to 576p and hevc to 720p

**Comment by Dum4G** [comment]
It's fine as it is, just isn't perfect

**Comment by MapGuy11** [comment]
> It's fine as it is, just isn't perfect

Yeah sorry I could probably do  alot better if I could send it to a Amazon aws streaming server or something but I don't have the money to do that and self hosting is virtually free (-power,etc.)

**Pull request merged**
