### PR TITLE
Update fr.m3u

### PR DESCRIPTION
**Pull request by exyanis**

### CODE REVIEW

**Review by Sphinxroot — DISMISSED** [review]
add the appropriate #EXTINF:-1 tvg-id="TF1.fr" tvg-name="TF1" tvg-country="FR" tvg-language="French" tvg-logo="" group-title="Entertainment",TF1  and to the appropriate line in list please near line 405

**Comment by Dum4G** [comment]
Can someone check gledai links? Looks like we can remove them and use this link as a replacement

**Comment by LaneSh4d0w** [comment]
Gledai links are off.

**Review by BellezaEmporium — COMMENTED** [review]
This link works for me.

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
