### PR TITLE
Invalidate NSFW channels, Rewrite README.

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Everything is in the title.

Add references to issue #15723

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
I suggest waiting for Arhey to give the green flag before approving this PR, as he knows everything about the scripts.

**Comment by BellezaEmporium** [comment]
I thought this was a better idea than to move all of them to the blocklist.

**Comment by Sphinxroot** [comment]
i wonder if 1.7m of  post in github that have x channel will be deleted ;/

**Comment by BellezaEmporium** [comment]
> i wonder if 1.7m of post in github that have x channel will be deleted ;/

Maybe. We may never know the answer.

**Review by Alstruit — DISMISSED** [review]

**Review by Dum4G — DISMISSED** [review]

**Comment by Dum4G** [comment]
You'll revert script if something goes wrong ig

**Comment by BellezaEmporium** [comment]
Well there's one way to finding out : running a format action in the branch. If it goes well i'm approving this PR.

**Comment by BellezaEmporium** [comment]
Needs a bit of tweaking. Please wait.

**Comment by BellezaEmporium** [comment]
Now works nicely.

**Review by Dum4G — APPROVED** [review]

**Review by Alstruit — APPROVED** [review]

**Pull request merged**
