### PR TITLE
Update to the Official Stream Link

### PR DESCRIPTION
**Pull request by VoXaN24**

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
It would work if there wasn't any token. sadly it always changes. The only way it could work is basically creating a Streamlink plugin for TegoTV.

**Review by its0x08 — APPROVED** [review]

**Comment by taodicakhia** [comment]
> It would work if there wasn't any token. sadly it always changes. The only way it could work is basically creating a Streamlink plugin for TegoTV.

Streamlink doesn't support TegoTV stream, and token of stream contains IP so you can't play stream in other IP

**Comment by LaneSh4d0w** [comment]
> > It would work if there wasn't any token. sadly it always changes. The only way it could work is basically creating a Streamlink plugin for TegoTV.
> 
> Streamlink doesn't support TegoTV stream, and token of stream contains IP so you can't play stream in other IP

Good point. It would only work locally then.

**Comment by LaneSh4d0w** [comment]
Cannot be added to the playlists, due to @taodicakhia's answer mentioning the tokens being IP-locked.

**Pull request closed without merging**
