### PR TITLE
Disney Channel Hindi, Marvel HQ, Hungama and Cartoon Network

### PR DESCRIPTION
**Pull request by Nintendocustom**
#854 
test123

### CODE REVIEW

**Comment by Nintendocustom** [comment]
I added ABC Spark too(#746).

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
Thank you for your help!

**Review by SileC — COMMENTED** [review]
They are GEO blocked to India. You need VPN.

**Comment by Nintendocustom** [comment]
They are not blocked.
test123

**Comment by SileC** [comment]
I said GEO blocked, not Not working. 
It works only only from India (IP from India), everywhere else show playlist error.

**Comment by Nintendocustom** [comment]
image
It's working in Germany too.

**Comment by freearhey** [comment]
For me, all channels are working fine at the moment, too. 

Captura de pantalla 2020-05-17 a las 19 27 39

And I am definitely not in India.

**Comment by SileC** [comment]
Then OK. I tried with vpn here and works. Maybe it is just the ISP blocking.

**Pull request merged**
