### PR TITLE
Remove broken links

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Dum4G — CHANGES_REQUESTED** [review]
Tele Liban first link refers the same dead resource.

**Comment by tilfizyawn** [comment]
@Dum4G Fixed in https://github.com/iptv-org/iptv/pull/2850 as I accidentally deleted that branch

**Comment by LaneSh4d0w** [comment]
Patch branch does not seem to be available on my side. I'll let the others see, but I don't know if it will pass.

**Review by freearhey — APPROVED** [review]

**Comment by Dum4G** [comment]
@MapGuy11 would you be kind to merge this too? Aleksandr has approved

**Comment by MapGuy11** [comment]
Let me see

**Review by MapGuy11 — APPROVED** [review]
_Looks Good!_

**Review by BellezaEmporium — APPROVED** [review]
LGTM

**Comment by freearhey** [comment]
I don't know why, but at the moment this PR cannot be merged. I will try to find out what the problem is and merge it later if I can.

**Comment by LaneSh4d0w** [comment]
His branch was deleted.

**Comment by freearhey** [comment]
@LaneSh4d0w You're probably right and that's the problem. Then I think we can close it.

**Comment by LaneSh4d0w** [comment]
I think so too. @tilfizyawn I suggest you to remake this PR using a branch that we can consult. I think you did something wrong and falsely deleted this patch branch.

**Comment by tilfizyawn** [comment]
Thanks everyone!

**Pull request closed without merging**
