### PR TITLE
Update my.m3u

### PR DESCRIPTION
**Pull request by Jerrie-Aries**
Add TV3 channel.

### CODE REVIEW

**Comment by Dum4G** [comment]
Does the first link work for you with the refferer?

**Comment by Jerrie-Aries** [comment]
The first link actually worked when I tested it using MX Player and Kodi Player. But when I used TiviMate, it said `Error: code 403`. I have no idea why.

The second link works on TiviMate.

**Comment by Dum4G** [comment]
Please verify if it works for you in Tivimate
https://gist.githubusercontent.com/Dum4G/43cdf6a2d0c486f9c86634480b7ce64d/raw/a986defe65b9e638c188c529be76d86373e65d72/gistfile1.txt

If so, we can add both with no problem

**Comment by Jerrie-Aries** [comment]
It didn't work on first try.
Then I removed the double quotes from the `#EXTVLCOPT:http-user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.4044.138 Safari/537.36"` bit (by looking at the format on other channels).

Now it's working flawlessly. 😃

**Comment by Dum4G** [comment]
Yeah, just add those lines and we're good to go

**Comment by Jerrie-Aries** [comment]
Done.

**Review by Dum4G — APPROVED** [review]

**Review by Alstruit — APPROVED** [review]

**Pull request merged**
