### PR TITLE
Update hu.m3u

### PR DESCRIPTION
**Pull request by kristoft13**
Added M4 Sport (720p)

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Due to the nature of the channel, I don't think it'll be accepted. @freearhey ?

**Comment by benevenstanciano** [comment]
The channel has two versions - one that's available across Europe and blacks out international sport, and one internal version. The first would probably be fine. In any case, looks like the stream isn't working.

**Comment by LaneSh4d0w** [comment]
> The channel has two versions - one that's available across Europe and blacks out international sport, and one internal version. The first would probably be fine. In any case, looks like the stream isn't working.

Well the last time i've tested it streamed live matches of the UEFA Champions League.

**Comment by LaneSh4d0w** [comment]
Not working anymore, and due to no answer from OP since then + no change, closing this PR.

**Pull request closed without merging**
