### PR TITLE
CO : Add Telecaribe (adaptive link)

### PR DESCRIPTION
**Pull request by BellezaEmporium**
From an Anvato API.

Might have a second card if this one doesn't stay over the time.

### CODE REVIEW

**Comment by jkemp814** [comment]
streamlink reports:

error: No plugin can handle URL: https://tkx.apis.anvato.net/rest/v2/mcp/video/adstB64MXYxqLZwy?anvack=4gXmVVoVIp3YeECJWm6af3j0mlHwl6vO

ffplay reports:

[https @ 0x7f05b0001780] HTTP error 403 Forbidden
https://tkx.apis.anvato.net/rest/v2/mcp/video/adstB64MXYxqLZwy?anvack=4gXmVVoVIp3YeECJWm6af3j0mlHwl6vO: Server returned 403 Forbidden (access denied)

Is it [Geo-blocked]?

**Comment by LaneSh4d0w** [comment]
> 
> 
> streamlink reports:
> 
> error: No plugin can handle URL: https://tkx.apis.anvato.net/rest/v2/mcp/video/adstB64MXYxqLZwy?anvack=4gXmVVoVIp3YeECJWm6af3j0mlHwl6vO
> 
> ffplay reports:
> 
> [https @ 0x7f05b0001780] HTTP error 403 Forbidden
> https://tkx.apis.anvato.net/rest/v2/mcp/video/adstB64MXYxqLZwy?anvack=4gXmVVoVIp3YeECJWm6af3j0mlHwl6vO: Server returned 403 Forbidden (access denied)
> 
> Is it [Geo-blocked]?

Nope, token expired. I wanted to make sure that token was expiring over time or not. I got a second card though. Give me a few minutes to implement the solution.

**Comment by LaneSh4d0w** [comment]
There we go, after some battling with regular expressions, we got it.

**Comment by Dum4G** [comment]
Doesn't play in mobile VLC but since it sucks I'm gonna check it later today

**Comment by LaneSh4d0w** [comment]
Yup, just tested on mine and works fine.

vlcsnap-2021-07-09-09h17m01s078
vlcsnap-2021-07-09-09h17m15s399

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
