### PR TITLE
Update us.m3u

### PR DESCRIPTION
**Pull request by Carterlion13**
.

### CODE REVIEW

**Comment by PopeyeTheSai10r** [comment]
Won't load for me

**Comment by Carterlion13** [comment]
> Won't load for me

Maybe it’s geo blocked

**Comment by Dum4G** [comment]
This kind of switch doesn't resolve the problem and makes things worse in VLC. This source can simply fallback to http

**Comment by BellezaEmporium** [comment]
http instead of https

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
