### PR TITLE
Update kr.m3u

### PR DESCRIPTION
**Pull request by Alstruit**

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
The SeeZN links might disappear soon as they've implemented their payment services. The Beta access still give you the links but the app doesn't.

**Comment by Alstruit** [comment]
In that case, once SeeZN implements the changes, the links will be removed.

**Comment by LaneSh4d0w** [comment]
> In that case, once SeeZN implements the changes, the links will be removed.

I'm actually looking to replace the adaptive links with a similar solution that scrapes SeeZN's links from their API.

**Comment by Alstruit** [comment]
I think the reason why some links are generated that aren't laggy beacause that one particular token is still accessable on one particaular server handling most of the requests.

**Comment by LaneSh4d0w** [comment]
Please try this : https://kr-streams.onrender.com/scraper?channel=215, you should have the AsiaN channel.

**Comment by Alstruit** [comment]
> Please try this : https://kr-streams.onrender.com/scraper?channel=215, you should have the AsiaN channel.
> 
> I've located the server in Singapore to make sure it was close to South Korea. Seems the link redirection goes smoothly.

Looks very good. Did you also managed to create the medium (720p) and low quality (404p) as well? I'm not sure if it's possible to use the same token.

**Comment by LaneSh4d0w** [comment]
> > Please try this : https://kr-streams.onrender.com/scraper?channel=215, you should have the AsiaN channel.
> > I've located the server in Singapore to make sure it was close to South Korea. Seems the link redirection goes smoothly.
> 
> Looks very good. Did you also managed to create the medium (720p) and low quality (404p) as well? I'm not sure if it's possible to use the same token. I did see some improvements on using different CDNs, but it can vary with some little to no stutters.

Since i'm relying on SeeZN's API for playlist retrieval, it seems it gets the High setting immediately.

**Comment by Alstruit** [comment]
> > > Please try this : https://kr-streams.onrender.com/scraper?channel=215, you should have the AsiaN channel.
> > > I've located the server in Singapore to make sure it was close to South Korea. Seems the link redirection goes smoothly.
> > 
> > 
> > Looks very good. Did you also managed to create the medium (720p) and low quality (404p) as well? I'm not sure if it's possible to use the same token. I did see some improvements on using different CDNs, but it can vary with some little to no stutters.
> 
> Since i'm relying on SeeZN's API for playlist retrieval, it seems it gets the High setting immediately. Though I don't know if I can generate a M3U file in-memory that has all qualities.

Not a problem. For now I'll include the 1080p scrapper and keep the adaptive streams (404p).

**Review by freearhey — DISMISSED** [review]

**Pull request closed without merging**
