### PR TITLE
US: Add Pluto.TV VH1 Classics.

### PR DESCRIPTION
**Pull request by heroku-miraheze**

### CODE REVIEW

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Please change the tvg-id of this channel to correspond to what it actually is.

**Comment by heroku-miraheze** [comment]
@LaneSh4d0w please, give me a contributor to merge it.

**Comment by heroku-miraheze** [comment]
Because main contributor is offline.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w please, give me a contributor to merge it.

I do not have the rights to do so, sorry.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by heroku-miraheze** [comment]
@LaneSh4d0w So, i need a merge branch right to merge it. One time.

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w So, i need a merge branch permission to merge it. One time.

I cannot do this either. Only the founding members can deliver permissions.

**Comment by heroku-miraheze** [comment]
OK.

**Comment by heroku-miraheze** [comment]
@freearhey Please, instead of merge it you, give me a contributor, and i will merge it now.

**Comment by heroku-miraheze** [comment]
@Sphinxroot

**Comment by freearhey** [comment]
@heroku-miraheze Please stop spamming.

**Comment by heroku-miraheze** [comment]
OK.

**Pull request merged**
