### PR TITLE
Remove Duplicates + cleanup

### PR DESCRIPTION
**Pull request by Link4K**
- remove ?fluxustv.m3u8 from the ends of urls as that causes duplicates
- Cleanup tvanywhere.ae links
- Run npm run format to remove duplicates

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
@Link4K For the future, there is no need to run scripts manually as they are triggered automatically every day.

**Comment by Link4K** [comment]
Thanks. I was using it as a way to remove duplicates :)

**Comment by khedernahar** [comment]
Es ist fantastic super

**Comment by khedernahar** [comment]
Super ihr seid heros

**Pull request merged**
