### PR TITLE
CO : Reinstate the hvtrafico links

### PR DESCRIPTION
**Pull request by BellezaEmporium**
After a severe downtime, it seems they came back.

We'll need to have a deep look over Cinema+ around the 23:00 / 5:00 period, as it might be like Rouge TV : stream family friendly content over daytime, and 18+ content over night time.

(it seems they're highly unstable. they're using DDNS, most certainly is a self-hosted stream (computer or server)

### CODE REVIEW

**Review by its0x08 — DISMISSED** [review]

**Comment by what-a** [comment]
None work for me. Geo-blocked or perhaps down?

**Comment by LaneSh4d0w** [comment]
It seems their streams are highly unstable. Used to have them working last time.

**Comment by LaneSh4d0w** [comment]
Confirmed, Cinema+ having 18+ content, are affiliated with Colombian X studio https://www.switchpremium.com/

**Comment by LaneSh4d0w** [comment]
The weirdest thing is : the server isn't even **down**, it answers to pings but fails to give proper response.

**Comment by LaneSh4d0w** [comment]
It is now working... for now.

**Comment by LaneSh4d0w** [comment]
Closing since it seems they didn't came back over. Not removing the branch because if they do appear again (and are stable), we could pull them over.

**Pull request closed without merging**
