### PR TITLE
Update ni.m3u

### PR DESCRIPTION
**Pull request by fershady**
Replace a Stream

### CODE REVIEW

**Comment by Dum4G** [comment]
Error 403. May be geo-blocked

**Comment by fershady** [comment]
No, It don't have geo-blocked.

**Comment by LaneSh4d0w** [comment]
Works for me. I suspect a Not 24/7 stream.

**Comment by Dum4G** [comment]
> Works for me. I suspect a Not 24/7 stream.

I don't have 403 with VPN, maybe restricted for my region or something is wrong with my IP domain

**Comment by LaneSh4d0w** [comment]
> > Works for me. I suspect a Not 24/7 stream.
> 
> I don't have 403 with VPN, maybe restricted for my region or something is wrong with my IP domain

That, I can't tell.

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
