### PR TITLE
EG : Add Quran TV

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Quite confused by the origin of *this* specific channel. Got it called "Quran TV", but it isn't the Saudi version. I think it is the Iranian version, but it is streaming in Arabic, not in Persian. To confirm.

EDIT : As I've thought, the confusion took me and it also isn't the Iranian version. For those who know, please move this channel to it's correct place.

(Proof picture)

vlcsnap-2021-10-09-12h29m20s466

### CODE REVIEW

**Comment by dct-infra** [comment]
Reading/reciting the Quran is always done in arabic and there is only one version no matter the country's official or spoken language.
This one can be from ir tr my id or any other non arabic speaking country, will be difficult to know.

**Comment by jkemp814** [comment]
IP address from Spain

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w Reading/reciting the Quran is always done in arabic and there is only one version no matter the country's official or spoken language. After some searches the channel streams live on youtube, the owner is a renowned egyptian scholar, so channel is probably EG.

Nice. Moving it to EG.

**Comment by LaneSh4d0w** [comment]
> 
> 
> IP address from Spain

Also right : https://search.censys.io/hosts/213.162.202.5

**Review by Dum4G — APPROVED** [review]

**Review by jkemp814 — APPROVED** [review]

**Pull request merged**
