### PR TITLE
Update us.m3u

### PR DESCRIPTION
**Pull request by boomski**
Added 1 Channel

### CODE REVIEW

**Comment by freearhey** [comment]
@boomski Hi, do you have a PayPal account? I'd like to transfer you some money for your support of the project.

**Comment by boomski** [comment]
> 
> 
> @boomski Hi, do you have a PayPal account? I'd like to transfer you some money for your support of the project.

Yes i have , 
boomski2222@gmail.com

**Comment by freearhey** [comment]
@boomski sent

**Comment by boomski** [comment]
> 
> 
> @boomski sent

Thanks!

**Pull request merged**
