### PR TITLE
Update dz.m3u

### PR DESCRIPTION
**Pull request by UltraHDR**

### CODE REVIEW

**Comment by UltraHDR** [comment]
I don't understand why it fails. Can someone help please? Thankyou

**Comment by LaneSh4d0w** [comment]
Multiple channels had the ending of the useragent + El Djazair N1 added just above the link, which destroyed the playlist's structure. Fixed.

**Review by BellezaEmporium — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Review by freearhey — COMMENTED** [review]
I have not been able to run any broadcasts from the cdn02.hta.dz

First a protocol error appears:
image

Then:
image

VPN doesn't help.

**Comment by UltraHDR** [comment]
> I have not been able to run any broadcasts from the cdn02.hta.dz
> 
> First a protocol error appears: image
> 
> Then: image
> 
> VPN doesn't help.

Thanks for checking.

It looks like the website is down temporarily

https://www.htatv.com/channel/138

**Review by MapGuy11 — APPROVED** [review]

**Pull request merged**
