### PR TITLE
Update US.m3u (USTVNOW Channels)

### LINKED ISSUE #6054: Replace: Fox News Channel
### Channel Name

Fox News Channel

### What happened to the stream?

Poor bandwidth server-side (Long buffering in stream)

### Playlist

https://iptv-org.github.io/iptv/countries/us.m3u

### Broken Link

_No response_

### Possible Replacement

_No response_

### Notes

Picture quality is great. Buffering every 5-10-15 seconds. Gigabit internet, fibre optic to the flat, ethernet to android box. Other channels such as Fox 32 are fine without buffering

### LINKED ISSUE #6233: Add: National Geographic East
### Channel Name

National Graphic 

### What happened to the stream?

It is disappeared from the playlist

### Playlist

https://livecdn.fptplay.net/foxlive/natgeohd_hls.smil/playlist.m3u8

### Broken Link

_No response_

### Possible Replacement

_No response_

### Notes

_No response_

### LINKED ISSUE #6308: Fox News Channel
### Channel Name

Fox News Channel 

### Country

US

### Language

English

### Website

https://www.peacocktv.com/

### Stream URL

http://38.91.57.12:2082/foxnews/tracks-v1a1/mono.m3u8

### Notes

The WWE,NHL,NFL Channels Are From Peacock

### PR DESCRIPTION
**Pull request by Central302**
This Patch Will 
●Add USTVNOW Related Channel. (close #6233)
●Add CNBC (USA Version)
●Add 480p 4:3 Version of MSNBC and FOX News
●Add Alternate Source of FOX NEWS (close #6054 close #6308 )

Link Includes "teleuptv" are Reqired to User-Agent. (In This Style, Works on Most of Media Player. Tested in Potplayer, GSE IPTV, VLC,  iptvnator)

### CODE REVIEW

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
404 Not Found on all Teleup 7P cdn links on my side. 4P links work.

**Comment by Central302** [comment]
After Re-Check in photocalltv , Link Has Changed Only These Channel. maybe Tokened only 7p?

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by Central302** [comment]
(Fixed Fluxing, Please Approve Again)

**Comment by what-a** [comment]
Testing in California; CNBC plays fine. The rest stutter and rebuffer.

**Comment by Central302** [comment]
Due to #6345 ,Close The Issue, Stay Tuned for freearhey's Action.

**Pull request closed without merging**
