### PR TITLE
[in.m3u] Fixed offline links. Updated tvg-logo, tvg-language, group-title attributes.

### PR DESCRIPTION
**Pull request by javithakthar**
- [Polimer News] Updated tvg-logo, new stream (720p)
- [Sony Pix HD] Updated tvg-language, tvg-logo, group-title, stream link.
- [Star Vijay] - Updated group-title, stream link, new stream (1080p)

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
Thanks for the help!

**Comment by javithakthar** [comment]
Can mark Sony Pix in following checklist https://github.com/iptv-org/iptv/issues/1934

**Comment by freearhey** [comment]
Marked.

**Comment by Niyasmkkv** [comment]
Not working these newly added channels in kodi. Only Sony SAB HD is playing. I think geo blocked.

**Pull request merged**
