### PR TITLE
Update ca.m3u

### PR DESCRIPTION
**Pull request by Sphinxroot**

### CODE REVIEW

**Comment by Central302** [comment]
Thanks, But Sportsnet and TSN are in block-list.

**Comment by Central302** [comment]
Removing Discovery Owned Channel and Sportsnet (DMCA)

**Comment by Central302** [comment]
(Removing Sportsnet and Discovery Owned channel).

**Comment by Central302** [comment]
added "Canada" in Some Channel Name for Country Identify.

**Review by Sphinxroot — COMMENTED** [review]
Why removing working channel ?

**Comment by Central302** [comment]
All Sportsnet Channels and Discovery Owned Channels are in Blocklist(Not Allowed to add to Playlist)

**Review by Dum4G — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
