### PR TITLE
Add 2 Vietnamese VTV channels

### PR DESCRIPTION
**Pull request by ghost**
Stream links are grabbed from CVmedia and plays fine with MPV

### CODE REVIEW

**Comment by Dum4G** [comment]
Plays for one second and disconnects. Need confirmation if it's the VLC issue or protection of a kind

**Comment by luutuyen2k9** [comment]
It just possibly an VLC issue
Maybe can we play streams with mpv?

**Comment by Dum4G** [comment]
Previously I have raised a discussion on the topic
https://github.com/orgs/iptv-org/discussions/1632

Currently I'm rejecting links that do not work in VLC because we were historically using it for stream checks. many IPTV players use it in it's core, it is platform agnostic etc. Anyway, this topic is still debatable

**Comment by luutuyen2k9** [comment]
I'm closing this pull request here and I don't want to contribute to iptv-org/iptv here

**Pull request closed without merging**
