### PR TITLE
MN : Host names for MNB links + add MNB World

### PR DESCRIPTION
**Pull request by BBBURENEEBB**
,mn

### CODE REVIEW

**Comment by BBBURENEEBB** [comment]
hghgg

**Comment by BBBURENEEBB** [comment]
fhdgfghghf

**Review by BellezaEmporium — APPROVED** [review]

**Review by its0x08 — APPROVED** [review]

**Review by dct-infra — COMMENTED** [review]
Black screen

**Review by what-a — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
they might not be 24/7 if we see a black screen.

**Pull request merged**
