### PR TITLE
Arabic Updates

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]
First time I see a vertical stream, however it works.

**Comment by LaneSh4d0w** [comment]
Ah wait, this channel seems to block after 3 seconds... is it trying to bump quality ?

**Comment by tilfizyawn** [comment]
> First time I see a vertical stream, however it works.
There's another here
https://github.com/iptv-org/iptv/blob/master/channels/sa.m3u#L38

**Comment by tilfizyawn** [comment]
> Ah wait, this channel seems to block after 3 seconds... is it trying to bump quality ?

Works fine for me.

Also works on http://www.streamtest.net/?launch=true#newTest?streamurl=https%3a%2f%2fstream.skynewsarabia.com%2fvertical%2fvertical.m3u8&launch=true

**Comment by LaneSh4d0w** [comment]
image

**Comment by tilfizyawn** [comment]
Does https://stream.skynewsarabia.com/vertical/vertical_1080.m3u8 work?

**Comment by tilfizyawn** [comment]
streamlink hls://https://stream.skynewsarabia.com/vertical/vertical.m3u8 best

works fine

**Comment by LaneSh4d0w** [comment]
Yup, the 1080 work.

I think there's an issue when bumping quality.

**Comment by Dum4G** [comment]
> https://iptv-all.lanesh4d0w.codes/m3u8/sky_arabia.m3u8.

Is that an alternate link or fixed playlist?

**Review by Dum4G — APPROVED** [review]

**Comment by tilfizyawn** [comment]
@LaneSh4d0w Thanks

**Pull request merged**
