### PR TITLE
Update al.m3u

### PR DESCRIPTION
**Pull request by eurohunter**
Addressing the following issues:
#11846 
#11847 
#11848 
#11849

### CODE REVIEW

**Review by UltraHDR — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]
For a first PR, it's a flawless one. Thanks for contributing.

**Comment by trincowski** [comment]
> This is the first time i'm trying a pull request, so please let me know if I'm doing something wrong :)

Great stuff.

How did you find these links? Is it possible that the remaining channels are also available, for example, RTSH2, RTSH3, RTSH4... TringJolly, TringWorld... etc?

**Comment by eurohunter** [comment]
> 

It was simple. For the Tring channels, I simply took the links that were available for Vizion Plus and the other channels (ex. https://mfe01.tring.al/delta/105/out/u/621_13.m3u8), and I created a txt file with a list of links that replaced the numbers 621_13 with numbers from 1_1 (or 1_3) to 1200_1 (or 1200_3). I also tried it with 106 instead of 105. I ran these files in VLC, and all these channels popped up. There were also several other channels that popped up, but they were mainly international channels for which links are already available. I did not see those other channels like trying world or Jolly. Maybe they have numbers in their links that go higher than 1200, but I stopped there. As for RTSH 2, 3, etc, they probably don't have them because they don't even advertise them on their platform. We just have to wait until RTSH updates their servers and make these channel available again. 

I have to say though. Except for Vizion Plus and Kanali 7, I don't think Tring intends to make all these other channels publicly available. Once they figure out that they have left their servers accessible by anyone, they will probably add some security layer.

**Comment by trincowski** [comment]
Wow, thanks a lot for that work!

**Comment by trincowski** [comment]
> > 
> 
> It was simple. For the Tring channels, I simply took the links that were available for Vizion Plus and the other channels (ex. https://mfe01.tring.al/delta/105/out/u/621_13.m3u8), and I created a txt file with a list of links that replaced the numbers 621_13 with numbers from 1_1 (or 1_3) to 1200_1 (or 1200_3). I also tried it with 106 instead of 105. I ran these files in VLC, and all these channels popped up. There were also several other channels that popped up, but they were mainly international channels for which links are already available. I did not see those other channels like trying world or Jolly. Maybe they have numbers in their links that go higher than 1200, but I stopped there. As for RTSH 2, 3, etc, they probably don't have them because they don't even advertise them on their platform. We just have to wait until RTSH updates their servers and make these channel available again.
> 
> I have to say though. Except for Vizion Plus and Kanali 7, I don't think Tring intends to make all these other channels publicly available. Once they figure out that they have left their servers accessible by anyone, they will probably add some security layer.

Hi again!

I've just found this link which should be useful the next time you do something like that! :-)
http://www.iptvtools.net/

**Comment by eurohunter** [comment]
> > > 
> > 
> > 
> > It was simple. For the Tring channels, I simply took the links that were available for Vizion Plus and the other channels (ex. https://mfe01.tring.al/delta/105/out/u/621_13.m3u8), and I created a txt file with a list of links that replaced the numbers 621_13 with numbers from 1_1 (or 1_3) to 1200_1 (or 1200_3). I also tried it with 106 instead of 105. I ran these files in VLC, and all these channels popped up. There were also several other channels that popped up, but they were mainly international channels for which links are already available. I did not see those other channels like trying world or Jolly. Maybe they have numbers in their links that go higher than 1200, but I stopped there. As for RTSH 2, 3, etc, they probably don't have them because they don't even advertise them on their platform. We just have to wait until RTSH updates their servers and make these channel available again.
> > I have to say though. Except for Vizion Plus and Kanali 7, I don't think Tring intends to make all these other channels publicly available. Once they figure out that they have left their servers accessible by anyone, they will probably add some security layer.
> 
> Hi again!
> 
> I've just found this link which should be useful the next time you do something like that! :-) http://www.iptvtools.net/

That's actually quite useful! Thank you. It seems to do the job faster than VLC, and I don't have to manually search for the resolution on each link :)

**Pull request merged**
