### PR TITLE
Update fr.m3u

### PR DESCRIPTION
**Pull request by LeWarpy**
Added "Dreamsee Télévision"

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Thank you for adding your channel to our playlists. Is it 24/7 ? Cannot access it right now.

**Comment by LeWarpy** [comment]
Hi @LaneSh4d0w, we only broadcast on weekends and mondays.
I just put an testcard on this stream, check it :)

**Comment by LaneSh4d0w** [comment]
> Hi @LaneSh4d0w, we only broadcast on weekends and mondays.
> I just put an testcard on this stream, check it :)

Confirmed working 👍

**Review by BellezaEmporium — APPROVED** [review]

**Comment by LaneSh4d0w** [comment]
as an alternative link we can use Dreamsee's Twitch channel : http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/dreamseetv

**Review by what-a — APPROVED** [review]

**Pull request merged**
