### PR TITLE
JP : The Grand Cleaning

### LINKED ISSUE #12851: Broken: Animax
### Broken Link

https://redlabmcdn.s.llnwi.net/nv02/bs14hd/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12924: Broken:  NHK BS1 (480p)
### Stream Title

NHK BS1 (480p)

### Playlist Link

https://redlabmcdn.s.llnwi.net/nv02/bs01hd/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12925: Broken: NHK BSP (480p)
### Stream Title

NHK BSP (480p)

### Playlist Link

https://redlabmcdn.s.llnwi.net/nv02/bs02hd/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12926: Broken: NHK E (480p) [Not 24/7]
### Stream Title

NHK E (480p) [Not 24/7]

### Playlist Link

https://redlabmcdn.s.llnwi.net/nv02/ryowa1hd/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12927: Broken: NHK G (480p) [Not 24/7]
### Stream Title

NHK G (480p) [Not 24/7]

### Playlist Link

https://redlabmcdn.s.llnwi.net/nv02/ryowa2hd/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12928: Broken: TV Asahi (480p)
### Stream Title

TV Asahi (480p)

### Playlist Link

https://iptv-org.github.io/iptv/languages/jpn.m3u

### What happened to the stream?

Not loading

### Notes (optional)

https://redlabmcdn.s.llnwi.net/nv02/ryowa4hd/index.m3u8

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12930: Broken: BS 12 (480p)
### Stream Title

BS 12 (480p)

### Playlist Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12931: Broken: BS Asahi (480p)
### Stream Title

BS Asahi (480p)

### Playlist Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12932: Broken: BS Fuji TV (480p)
### Stream Title

BS Fuji TV (480p)

### Playlist Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12933: Broken: BS Nippon TV (480p)
### Stream Title

BS Nippon TV (480p)

### Playlist Link

https://iptv-org.github.io/iptv/countries/jp.m3u

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12934: Broken: BS TBS (480p)
### Stream Title

BS TBS (480p)

### Playlist Link

https://github.com/iptv-org/iptv/blob/master/streams/jp.m3u
https://redlabmcdn.s.llnwi.net/nv02/bs05hd/index.m3u8

### What happened to the stream?

Not loading

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### LINKED ISSUE #12960: Broken: TV Tokyo
### Stream Title

TV Tokyo (480p)

### Playlist Link

https://iptv-org.github.io/iptv/languages/jpn.m3u

### What happened to the stream?

Not loading

### Notes (optional)

Hasn't been working for 4 days.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Remove non-working links

closes #12934, closes #12933, closes #12932, closes #12931, closes #12930, closes #12928, closes #12927, closes #12926, closes #12925, closes #12924, closes #12960, closes #12851

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Review by UltraHDR — APPROVED** [review]

**Comment by solo489** [comment]
When will it be fixed?

**Comment by BellezaEmporium** [comment]
Fixed on removal, basically saying : "it doesn't exist anymore".

**Comment by baliebox4916** [comment]
aww thats too bad

i loved watching anime on those channels (even without the english subs)

these were the only channels that had real anime imo

the pluto tv anime stream has good anime for a minute or so and then it cuts out and switches to the feed with the crappy 4kids style anime we have here in canada

but it could be worst
i could be watching canadian pluto tv and forced to watch old crap from the 70s and 80s, shows like cash cab and call of duty lets plays

still wish there was a good anime stream on here though

**Comment by trincowski** [comment]
> still wish there was a good anime stream on here though

You've got AnimeTV.br (Japanese Audio / Portuguese Subtitles) and Geekdot.br (Portuguese Dubbed, I'm afraid).

**Pull request merged**
