### PR TITLE
Update us_localbtv.m3u

### LINKED ISSUE #6248: getTV
### Channel Name

getV

### Country

USA

### Language

English

### Website

https://www.get.tv

### Stream URL

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by what-a**
Adding GetTV.  Closes iptv-org/iptv#6248

### CODE REVIEW

**Comment by MapGuy11** [comment]
I would approve it but I can't admin removed my ability to do anything after I think I made a country tag wrong.

**Review by Sphinxroot — APPROVED** [review]

**Comment by Sphinxroot** [comment]
> I would approve it but I can't admin removed my ability to do anything after I think I made a country tag wrong which I assume pissed him off idk?

ive had this issue a couple time ago   couldnt do anything at all  , edit or approve pr  or closing  and it came back

**Review by Central302 — APPROVED** [review]

**Comment by Dum4G** [comment]
> I would approve it but I can't admin removed my ability to do anything after I think I made a country tag wrong which I assume pissed him off idk?

@freearhey is that an accident or your final decision?

**Comment by freearhey** [comment]
@Dum4G I already explained that the role change is temporary: https://github.com/iptv-org/iptv/issues/6078#issuecomment-1014840955 Reason: https://github.com/iptv-org/iptv/issues/6103#issuecomment-1014532501

**Comment by MapGuy11** [comment]
> @Dum4G I already explained that the role change is temporary: https://github.com/iptv-org/iptv/issues/6078#issuecomment-1014840955 Reason: https://github.com/iptv-org/iptv/issues/6103#issuecomment-1014532501

Oh I wasn't told it was temporary I just assumed I kind of ticked you off or something. My apologies 😊

**Pull request merged**
