### PR TITLE
Update fr.m3u

### PR DESCRIPTION
**Pull request by exyanis**

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]
Works for me, however I can't tell if those are geo-locked. Calling someone else to verify.

**Review by Sphinxroot — COMMENTED** [review]
all here .. was about to finish the update and PR here 

https://github.com/Sphinxroot/IPTVM3U/blob/master/France.m3u

#EXTINF:-1 tvg-id="AB1.fr" tvg-name="AB 1 FR" tvg-logo="https://i.imgur.com/alYq7vX.png" group-title="généraliste",AB1
http://flusonic-4.platinum-tv.com/AB1/tracks-v1a1/mono.m3u8?token=test

#EXTINF:-1 tvg-id="Animaux.fr" tvg-name="Animaux FR" tvg-logo="https://i.imgur.com/VIMEnFM.png" group-title="documentaires",Animaux
http://212.224.98.210:2200/EX/ANIMAUX-fr/tracks-v1a1/mono.m3u8?token=null

#EXTINF:-1 tvg-id="ARTE.fr" tvg-name="Arte FR" tvg-logo="https://i.imgur.com/zthzjPs.png"group-title="documentaires",Arte
http://stream.tvtap.live:8081/live/fr-arte.stream/playlist.m3u8

#EXTINF:-1 tvg-id="Automoto.fr" tvg-name="Automoto FR" tvg-logo="https://i.imgur.com/LJX8OLD.jpg" group-title="Sport",AutoMoto
http://flusonic-4.platinum-tv.com/AUTOMOTO/tracks-v1a1/mono.m3u8?token=test

#EXTINF:-1 tvg-id="BET.fr" tvg-name="BET FR" tvg-logo="https://i.imgur.com/5y8LIzB.png" group-title="thématique",BET
http://212.224.98.210:2200/EX/BET-fr/tracks-v1a1/mono.m3u8?token=null

#EXTINF:-1 tvg-id="C8.fr" tvg-name="C8 FR" tvg-logo="https://i.imgur.com/C4ApWGr.jpg" group-title="généraliste",C8
http://stream.tvtap.live:8081/live/fr-c8.stream/playlist.m3u8

#EXTINF:-1 tvg-id="CanalJ.fr" tvg-name="Canal J FR" tvg-logo="https://i.imgur.com/uNE046N.png" group-title="Anime",Canal J
http://212.224.98.210:2200/EX/CANAL_J-fr/tracks-v1a1/mono.m3u8?token=null

#EXTINF:-1 tvg-id="CanalPlus.fr" tvg-name="Canal+ FR" tvg-logo="https://i.imgur.com/9FP1MyZ.png" group-title="généraliste",Canal+ 
http://flusonic-4.platinum-tv.com/canal+/tracks-v1a1/mono.m3u8?token=test

#EXTINF:-1 tvg-id="ChassePeche.fr" tvg-name="Chasse et pêche FR" tvg-logo="https://i.imgur.com/THErPIU.jpg" group-title="documentaires",Chasse & Peche
http://212.224.98.210:2200/EX/CHASSE_ET_PECHE-fr/tracks-v1a1/mono.m3u8?token=null

#EXTINF:-1 tvg-id="CNews.fr" tvg-name="CNews FR" tvg-logo="https://i.imgur.com/q5TOZ29.png" group-title="actualités",CNEWS
http://stream.tvtap.live:8081/live/cnews.stream/playlist.m3u8

#EXTINF:-1 tvg-id="CStar.fr" tvg-name="CStar FR" tvg-logo="https://i.imgur.com/4fLTTUm.jpg" group-title="généraliste",CStar
http://stream.tvtap.live:8081/live/fr-cstar.stream/playlist.m3u8

#EXTINF:-1 tvg-id="CStar.fr" tvg-name="CStar FR" tvg-logo="https://i.imgur.com/4fLTTUm.jpg" group-title="généraliste",CStar
http://flusonic-4.platinum-tv.com/D17/tracks-v1a1/mono.m3u8?token=test

#EXTINF:-1 tvg-id="GameOne.fr" tvg-name="Game One FR" tvg-logo="https://i.imgur.com/3rShsL5.png" group-title="Anime",GAME ONE
http://212.224.98.210:2200/EX/GAME_ONE-fr/tracks-v1a1/mono.m3u8?token=null

#EXTINF:-1 tvg-id="Gulli.fr" tvg-name="Gulli FR" tvg-logo="https://i.imgur.com/U2KsDA0.png" group-title="Anime",Gulli
http://stream.tvtap.live:8081/live/fr-gulli.stream/playlist.m3u8

#EXTINF:-1 tvg-id="Histoire.fr" tvg-name="Histoire FR" tvg-logo="https://i.imgur.com/vspU8Zl.png" group-title="documentaires",Histoire TV
http://212.224.98.210:2200/EX/HISTOIRE-fr/tracks-v1a1/mono.m3u8?token=null

#EXTINF:-1 tvg-id="InfosportPlus.fr" tvg-name="Infosport+ FR" tvg-logo="https://i.imgur.com/0wA4IwG.png" group-title="Sport",Infosport+
http://stream.tvtap.live:8081/live/fr-infosports.stream/playlist.m3u8

#EXTINF:-1 tvg-id="LCI.fr" tvg-name="LCI FR" tvg-logo="https://i.ibb.co/42qRB2Y/lci.png" group-title="actualités",LCI
http://flusonic-4.platinum-tv.com/LCI/tracks-v1a1/mono.m3u8?token=test

#EXTINF:-1 tvg-id="LCI.fr" tvg-name="LCI FR" tvg-logo="https://i.ibb.co/42qRB2Y/lci.png" group-title="actualités",LCI
http://stream.tvtap.live:8081/live/lci.stream/playlist.m3u8

#EXTINF:-1 tvg-id="M6.fr" tvg-name="M6 FR" tvg-logo="https://i.imgur.com/FNonACy.png" group-title="généraliste",M6
http://stream.tvtap.live:8081/live/fr-m6.stream/playlist.m3u8

#EXTINF:-1 tvg-id="M6.fr" tvg-name="M6 FR" tvg-logo="https://i.imgur.com/FNonACy.png" group-title="généraliste",M6
http://flusonic-4.platinum-tv.com/M6/tracks-v1a1/mono.m3u8?token=test

**Comment by Dum4G** [comment]
not geoblocked

**Comment by LaneSh4d0w** [comment]
> 
> 
> not geoblocked

Perfect. Will be merged when Arhey will have done its report.

**Comment by Sphinxroot** [comment]
hint  http://stream.tvtap.live:8081/live/   country(or Not)  channel name  .stream/playlist.m3u8

ex:
#EXTINF:-1,bbc
http://stream.tvtap.live:8081/live/bbc1.stream/playlist.m3u8
#EXTINF:-1,cnn
http://stream.tvtap.live:8081/live/us-cnn.stream/playlist.m3u8

have fun :)

**Comment by exyanis** [comment]
> http://stream.tvtap.live:8081/live/bbc1.stream/playlist.m3u8

**Pull request closed without merging**
