### PR TITLE
Add Swedish channels

### PR DESCRIPTION
**Pull request by freearhey**
Adds links to Swedish channels from the issues: https://github.com/iptv-org/iptv/issues?q=is%3Aissue+is%3Aopen+label%3A%22channel+request%22+label%3Aapproved+.se

### CODE REVIEW

**Review by PopeyeTheSai10r — APPROVED** [review]

**Comment by Sphinxroot** [comment]
looked at the pattern  found 3 more unknow yet
#EXTINF:-1 ,tx1
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx1/playlist.m3u8
#EXTINF:-1 tvg-id="ExpressenTV.se",Expressen TV
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx2/playlist.m3u8
#EXTINF:-1 ,tx3
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx3/playlist.m3u8
#EXTINF:-1 tvg-id="DiTV.se",Di TV
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx4/playlist.m3u8
#EXTINF:-1 ,tx5
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx5/playlist.m3u8

dont seem to go further

**Comment by freearhey** [comment]
@Sphinxroot Can't add links without the proper channel name.

**Comment by Sphinxroot** [comment]
#EXTINF:-1 ,Expressen TV Group channel pub in loop  to re-check
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx1/playlist.m3u8
#EXTINF:-1 tvg-id="ExpressenTV.se",Expressen TV
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx2/playlist.m3u8
#EXTINF:-1 ,Expressen TV Group channel pub in loop to re-check
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx3/playlist.m3u8
#EXTINF:-1 tvg-id="DiTV.se",Di TV
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx4/playlist.m3u8
#EXTINF:-1 tvg-id="NojeTV.se",,Noje TV
https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx5/playlist.m3u8

**Comment by BellezaEmporium** [comment]
> #EXTINF:-1 ,Expressen TV Group channel pub in loop to re-check https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx1/playlist.m3u8 #EXTINF:-1 tvg-id="ExpressenTV.se",Expressen TV https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx2/playlist.m3u8 #EXTINF:-1 ,Expressen TV Group channel pub in loop to re-check https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx3/playlist.m3u8 #EXTINF:-1 tvg-id="DiTV.se",Di TV https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx4/playlist.m3u8 #EXTINF:-1 tvg-id="NojeTV.se",Noje TV https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx5/playlist.m3u8

3 is Expressen Lifestyle

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
