### PR TITLE
Various updates.m3u

### LINKED ISSUE #12558: Add: M6 Music [FR]
### Channel ID

M6Music.fr

### Stream URL (optional)

http://178.170.47.109/M6MUSIC/index.m3u8

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #12559: Add: Boomerang France [FR]
### Channel ID

BoomerangFrance.fr

### Stream URL (optional)

http://51.81.185.2/BOOMERANG/index.m3u8

### Notes (optional)

_No response_

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### LINKED ISSUE #12561: Add: TiJi [FR]
### Channel ID

TiJi.fr

### Stream URL (optional)

https://shls-tiji-tv-prod-dub.shahid.net/out/v1/98f46736bd8c4404b67e4b7a38cc8976/index.m3u8

### Notes (optional)

This one is working.

### Please confirm the following

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)

### PR DESCRIPTION
**Pull request by Carlinhos027**
From DJ1999-max's issues

Closes #12558
Closes #12561

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Review by Sphinxroot — COMMENTED** [review]
working now

**Review by Sphinxroot — COMMENTED** [review]
working

**Review by Sphinxroot — COMMENTED** [review]
#EXTINF:-1 tvg-id="DuckTV.sk",Duck TV (576p)
http://85.11.144.8:5666/DuckTV?token=test

not working here

**Review by Sphinxroot — COMMENTED** [review]
#EXTINF:-1 tvg-id="MTVHitsFrance.fr",MTV Hits France (720p)
http://178.170.47.109/MTVHITS/index.m3u8
#EXTINF:-1 tvg-id="BoomerangFrance.fr",Boomerang France (720p)
http://51.81.185.2/BOOMERANG/index.m3u8

working

**Comment by DJ1999-max** [comment]
> #EXTINF:-1 tvg-id="DuckTV.sk",Duck TV (576p) http://85.11.144.8:5666/DuckTV?token=test
> 
> not working here



> #EXTINF:-1 tvg-id="DuckTV.sk",Duck TV (576p) http://85.11.144.8:5666/DuckTV?token=test
> 
> not working here

Sometimes works, because error.

**Comment by DJ1999-max** [comment]
This stream not 24/7.

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
