### PR TITLE
Update ve.m3u

### PR DESCRIPTION
**Pull request by sguinetti**
This add new streams from Venezuela

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Review by dct-infra — APPROVED** [review]

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Didn't we say we do not accept accents in tvg-id ?

**Comment by freearhey** [comment]
@LaneSh4d0w you are right, the correct id is `MundoMas.co`. I'm going to correct that now.

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w you are right, the correct id is `MundoMas.co`. I'm going to correct that now.

Moreover, this link is already available in mx.m3u.

**Comment by freearhey** [comment]
@LaneSh4d0w I removed that link.

**Pull request merged**
